SUBROUTINE ABOR1(CDTEXT)

! USE PARKIND1  ,ONLY : JPIM     ,JPRB
! USE YOMLUN_IFSAUX, ONLY : NULOUT,NULERR

IMPLICIT NONE

CHARACTER(LEN=*), INTENT(IN) :: CDTEXT
INTEGER :: ILEN

ILEN=LEN(CDTEXT)

WRITE(*,*) "ABORT : ", CDTEXT
! IF (NULOUT >= 0) WRITE(NULOUT,'(1X,A)') 'ABOR1 CALLED'

! IF(ILEN <= 512) THEN
!   IF (NULOUT >= 0) WRITE(NULOUT,'(1X,A)') CDTEXT
!   IF (NULERR >= 0) WRITE(NULERR,'(1X,A,1X,I3,1X,A)') 'ABORT! ',MPL_RANK,CDTEXT
! ELSE
!   IF (NULERR >= 0) WRITE(NULERR,'(1X,A,1X,I3,1X,A)') 'ABORT! ',MPL_RANK,&
!    & 'ABOR1 CALLED WITHOUT TEXT STRING'
! ENDIF

! IF (NULOUT >= 0) THEN
!   CALL FLUSH(NULOUT)
!   IF (NULOUT /= 0 .AND. NULOUT /= 6) CLOSE(NULOUT)
! ENDIF

! CALL BREXIT(CDTEXT)

CALL EXIT(1)

END SUBROUTINE ABOR1
