MODULE GETDATA_MOD

USE OMP_LIB
USE PARKIND1

INTERFACE REPLICATE
  MODULE PROCEDURE REPLICATE1
  MODULE PROCEDURE REPLICATE2
END INTERFACE

INTERFACE NPROMIZE
  MODULE PROCEDURE NPROMIZE2
  MODULE PROCEDURE NPROMIZE3
END INTERFACE

CONTAINS

SUBROUTINE GETDATA (CLCASE, CLCASE_NUM, CLCASE_MIN, CLCASE_MAX, KLONTOT, KLEV, NPROMA, NGPBLKS, &
  PAPHI_B, PAPHIF_B, PAPRS_B, PAPRSF_B, PDELP_B, PR_B, PT_B, PU_B, PV_B, PQ_B, &
  PQICONV_B, PQLCONV_B, PLSCPE_B, PCD_B, PCH_B, PGZ0_B, PTS_B, & 
  PQS_B, PQICE_B, PQLI_B, PECT_B, PPRODTH_B, PNLAB_B, PNLABCVP_B, &
  PQICE_REF_B, PQLI_REF_B, PECT_REF_B, PPRODTH_REF_B, PNLAB_REF_B, PNLABCVP_REF_B, &
  PKTROV_REF_B, PKQROV_REF_B, PKQLROV_REF_B, PKUROV_REF_B, PXTROV_REF_B, PXUROV_REF_B, &
  PNBVNO_REF_B, PNEBS_REF_B, PQCS_REF_B, PNEBS0_REF_B, PQCS0_REF_B, PCOEFN_REF_B, &
  PECT1_REF_B, PFECT_REF_B, PFECTI_REF_B, PTPRDY_REF_B, PEDR_REF_B)
!& LDVERBOSE)




USE IEEE_ARITHMETIC, ONLY : IEEE_SIGNALING_NAN, IEEE_VALUE

IMPLICIT NONE

INTEGER, PARAMETER :: IFILE = 77

! CHARACTER (LEN=*) :: CDCASE

CHARACTER*32 :: CLCASE
INTEGER :: CLCASE_NUM, CLCASE_MIN, CLCASE_MAX
INTEGER      :: KLONTOT, NPROMA, NGPBLKS
INTEGER      :: KLON 
INTEGER      :: KTDIAT 
INTEGER      :: KTDIAN 
INTEGER      :: KLEV  

INTEGER ::  I
CHARACTER*64 :: FILENAME


! INPUT DATA
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PAPHI(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PAPHIF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PAPRS(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PAPRSF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PDELP(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PR(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PT(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PU(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PV(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PQ(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PQICONV(:,:,:)
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PQLCONV(:,:,:)
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PLSCPE(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PCD(:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PCH(:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PGZ0(:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PTS(:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PQS(:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PQICE(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PQLI(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PECT(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PPRODTH(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PNLAB(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PNLABCVP(:,:,:) 


REAL(KIND=JPRB)   ,ALLOCATABLE    :: PAPHI_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PAPHIF_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PAPRS_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PAPRSF_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PDELP_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PR_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PT_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PU_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PV_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PQ_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PQICONV_B(:,:,:)
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PQLCONV_B(:,:,:)
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PLSCPE_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PCD_B(:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PCH_B(:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PGZ0_B(:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PTS_B(:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PQS_B(:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PQICE_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PQLI_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PECT_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PPRODTH_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PNLAB_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PNLABCVP_B(:,:,:) 

! OUTPUT REFERENCE


REAL(KIND=JPRB)   ,ALLOCATABLE    :: PQICE_REF_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PQLI_REF_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PECT_REF_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PPRODTH_REF_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PNLAB_REF_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PNLABCVP_REF_B(:,:,:) 


REAL(KIND=JPRB)   ,ALLOCATABLE   :: PKTROV_REF_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PKQROV_REF_B(:,:,:)
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PKQLROV_REF_B(:,:,:)
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PKUROV_REF_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PXTROV_REF_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PXUROV_REF_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PNBVNO_REF_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PNEBS_REF_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PQCS_REF_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PNEBS0_REF_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PQCS0_REF_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PCOEFN_REF_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PECT1_REF_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PFECT_REF_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PFECTI_REF_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PTPRDY_REF_B(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PEDR_REF_B(:,:,:) 


REAL(KIND=JPRB)   ,ALLOCATABLE    :: PQICE_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PQLI_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PECT_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PPRODTH_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PNLAB_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PNLABCVP_REF(:,:,:) 


REAL(KIND=JPRB)   ,ALLOCATABLE   :: PKTROV_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PKQROV_REF(:,:,:)
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PKQLROV_REF(:,:,:)
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PKUROV_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PXTROV_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PXUROV_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PNBVNO_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PNEBS_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PQCS_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PNEBS0_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PQCS0_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PCOEFN_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PECT1_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PFECT_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PFECTI_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PTPRDY_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PEDR_REF(:,:,:) 



REAL, ALLOCATABLE :: test(:,:)

LOGICAL :: LDVERBOSE


LOGICAL :: LLEXIST
CHARACTER(LEN=32) :: CLFILE
INTEGER :: ILUN, ILUNI, ILUNO, NGPTOT, IOFF, IBL
REAL (KIND=JPRB) :: ZNAN


ILUN = 77

ZNAN = IEEE_VALUE (ZNAN, IEEE_SIGNALING_NAN)

NGPTOT = NPROMA * NGPBLKS

ALLOCATE(PAPHI(NGPTOT,0:KLEV,1) )
ALLOCATE(PAPHIF(NGPTOT,KLEV,1) )
ALLOCATE(PAPRS(NGPTOT,0:KLEV,1) )
ALLOCATE(PAPRSF(NGPTOT,KLEV,1) )
ALLOCATE(PDELP(NGPTOT,KLEV,1) )
ALLOCATE(PR(NGPTOT,KLEV,1) )
ALLOCATE(PT(NGPTOT,KLEV,1) )
ALLOCATE(PU(NGPTOT,KLEV,1) )
ALLOCATE(PV(NGPTOT,KLEV,1) )
ALLOCATE(PQ(NGPTOT,KLEV,1) )
ALLOCATE(PQICONV(NGPTOT,KLEV,1))
ALLOCATE(PQLCONV(NGPTOT,KLEV,1))
ALLOCATE(PLSCPE(NGPTOT,KLEV,1) )
ALLOCATE(PCD(NGPTOT,1) )
ALLOCATE(PCH(NGPTOT,1) )
ALLOCATE(PGZ0(NGPTOT,1) )
ALLOCATE(PTS(NGPTOT,1) )
ALLOCATE(PQS(NGPTOT,1) )
ALLOCATE(PQICE(NGPTOT,KLEV,1) )
ALLOCATE(PQLI(NGPTOT,KLEV,1) )
ALLOCATE(PECT(NGPTOT,KLEV,1) )
ALLOCATE(PPRODTH(NGPTOT,0:KLEV,1) )
ALLOCATE(PNLAB(NGPTOT,KLEV,1) )
ALLOCATE(PNLABCVP(NGPTOT,KLEV,1) )



ALLOCATE(PAPHI_B(NPROMA, 0:KLEV, NGPBLKS))
ALLOCATE(PAPHIF_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PAPRS_B(NPROMA, 0:KLEV, NGPBLKS))
ALLOCATE(PAPRSF_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PDELP_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PR_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PT_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PU_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PV_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PQ_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PQICONV_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PQLCONV_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PLSCPE_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PCD_B(NPROMA, NGPBLKS))
ALLOCATE(PCH_B(NPROMA, NGPBLKS))
ALLOCATE(PGZ0_B(NPROMA, NGPBLKS))
ALLOCATE(PTS_B(NPROMA, NGPBLKS))
ALLOCATE(PQS_B(NPROMA, NGPBLKS))
ALLOCATE(PQICE_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PQLI_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PECT_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PPRODTH_B(NPROMA, 0:KLEV, NGPBLKS))
ALLOCATE(PNLAB_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PNLABCVP_B(NPROMA, 1:KLEV, NGPBLKS))



IOFF = 0
DO I = CLCASE_MIN, CLCASE_MAX
  write(FILENAME, '(A,I0.4,A,I0.4)' ) TRIM(CLCASE)//"."//"IN.",CLCASE_NUM, ".", I
  !write(*,*) FILENAME

  OPEN (ILUN, FILE=FILENAME, FORM="UNFORMATTED")
  READ (ILUN) KLON
  !write(*,*) "KLON : ", KLON
  READ (ILUN) KTDIAT
  READ (ILUN) KTDIAN
  READ (ILUN) KLEV
  
  READ(ILUN) PAPHI(1+IOFF:KLON+IOFF,0:KLEV,1)
  READ(ILUN) PAPHIF(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PAPRS(1+IOFF:KLON+IOFF,0:KLEV,1)
  READ(ILUN) PAPRSF(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PDELP(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PR(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PT(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PU(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PV(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PQ(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PQICONV(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PQLCONV(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PLSCPE(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PCD(1+IOFF:KLON+IOFF,1)
  READ(ILUN) PCH(1+IOFF:KLON+IOFF,1)
  READ(ILUN) PGZ0(1+IOFF:KLON+IOFF,1)
  READ(ILUN) PTS(1+IOFF:KLON+IOFF,1)
  READ(ILUN) PQS(1+IOFF:KLON+IOFF,1)
  READ(ILUN) PQICE(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PQLI(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PECT(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PPRODTH(1+IOFF:KLON+IOFF,0:KLEV,1)
  READ(ILUN) PNLAB(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PNLABCVP(1+IOFF:KLON+IOFF,1:KLEV,1)

  CLOSE(ILUN)

  IOFF = IOFF + KLON
END DO


  CALL REPLICATE(KLONTOT, PAPHI(:,:,1))
  CALL NPROMIZE(NPROMA, PAPHI, PAPHI_B)

  CALL REPLICATE(KLONTOT, PAPHIF(:,:,1))
  CALL NPROMIZE(NPROMA, PAPHIF, PAPHIF_B)

  CALL REPLICATE(KLONTOT, PAPRS(:,:,1))
  CALL NPROMIZE(NPROMA, PAPRS, PAPRS_B)

  CALL REPLICATE(KLONTOT, PAPRSF(:,:,1))
  CALL NPROMIZE(NPROMA, PAPRSF, PAPRSF_B)

  CALL REPLICATE(KLONTOT, PDELP(:,:,1))
  CALL NPROMIZE(NPROMA, PDELP, PDELP_B)

  CALL REPLICATE(KLONTOT, PR(:,:,1))
  CALL NPROMIZE(NPROMA, PR, PR_B)

  CALL REPLICATE(KLONTOT, PT(:,:,1))
  CALL NPROMIZE(NPROMA, PT, PT_B)

  CALL REPLICATE(KLONTOT, PU(:,:,1))
  CALL NPROMIZE(NPROMA, PU, PU_B)

  CALL REPLICATE(KLONTOT, PV(:,:,1))
  CALL NPROMIZE(NPROMA, PV, PV_B)

  CALL REPLICATE(KLONTOT, PQ(:,:,1))
  CALL NPROMIZE(NPROMA, PQ, PQ_B)

  CALL REPLICATE(KLONTOT, PQICONV(:,:,1))
  CALL NPROMIZE(NPROMA, PQICONV, PQICONV_B)

  CALL REPLICATE(KLONTOT, PQLCONV(:,:,1))
  CALL NPROMIZE(NPROMA, PQLCONV, PQLCONV_B)


  CALL REPLICATE(KLONTOT, PLSCPE(:,:,1))
  CALL NPROMIZE(NPROMA, PLSCPE, PLSCPE_B)

  CALL REPLICATE(KLONTOT, PCD(:,1))
  CALL NPROMIZE(NPROMA, PCD, PCD_B)

  CALL REPLICATE(KLONTOT, PCH(:,1))
  CALL NPROMIZE(NPROMA, PCH, PCH_B)


  CALL REPLICATE(KLONTOT, PGZ0(:,1))
  CALL NPROMIZE(NPROMA, PGZ0, PGZ0_B)

  CALL REPLICATE(KLONTOT, PTS(:,1))
  CALL NPROMIZE(NPROMA, PTS, PTS_B)


  CALL REPLICATE(KLONTOT, PQS(:,1))
  CALL NPROMIZE(NPROMA, PQS, PQS_B)


  CALL REPLICATE(KLONTOT, PQICE(:,:,1))
  CALL NPROMIZE(NPROMA, PQICE, PQICE_B)


  CALL REPLICATE(KLONTOT, PQLI(:,:,1))
  CALL NPROMIZE(NPROMA, PQLI, PQLI_B)


  CALL REPLICATE(KLONTOT, PECT(:,:,1))
  CALL NPROMIZE(NPROMA, PECT, PECT_B)


  CALL REPLICATE(KLONTOT, PPRODTH(:,:,1))
  CALL NPROMIZE(NPROMA, PPRODTH, PPRODTH_B)


  CALL REPLICATE(KLONTOT, PNLAB(:,:,1))
  CALL NPROMIZE(NPROMA, PNLAB, PNLAB_B)


  CALL REPLICATE(KLONTOT, PNLABCVP(:,:,1))
  CALL NPROMIZE(NPROMA, PNLABCVP, PNLABCVP_B)


ALLOCATE(PQICE_REF(NGPTOT,KLEV,1) )
ALLOCATE(PQLI_REF(NGPTOT,KLEV,1) )
ALLOCATE(PECT_REF(NGPTOT,KLEV,1) )
ALLOCATE(PPRODTH_REF(NGPTOT,0:KLEV,1) )
ALLOCATE(PNLAB_REF(NGPTOT,KLEV,1) )
ALLOCATE(PNLABCVP_REF(NGPTOT,KLEV,1) )
ALLOCATE (PKTROV_REF(NGPTOT,0:KLEV,1) ) 
ALLOCATE (PKQROV_REF(NGPTOT,0:KLEV,1)) 
ALLOCATE (PKQLROV_REF(NGPTOT,0:KLEV,1)) 
ALLOCATE (PKUROV_REF(NGPTOT,0:KLEV,1) ) 
ALLOCATE (PXTROV_REF(NGPTOT,0:KLEV,1) ) 
ALLOCATE (PXUROV_REF(NGPTOT,0:KLEV,1) ) 
ALLOCATE (PNBVNO_REF(NGPTOT,0:KLEV,1) ) 
ALLOCATE (PNEBS_REF(NGPTOT,KLEV,1) ) 
ALLOCATE (PQCS_REF(NGPTOT,KLEV,1) ) 
ALLOCATE (PNEBS0_REF(NGPTOT,KLEV,1) ) 
ALLOCATE (PQCS0_REF(NGPTOT,KLEV,1) ) 
ALLOCATE (PCOEFN_REF(NGPTOT,KLEV,1) ) 
ALLOCATE (PECT1_REF(NGPTOT,KLEV,1) ) 
ALLOCATE (PFECT_REF(NGPTOT,0:KLEV,1) ) 
ALLOCATE (PFECTI_REF(NGPTOT,0:KLEV,1) ) 
ALLOCATE (PTPRDY_REF(NGPTOT,KLEV,1) ) 
ALLOCATE (PEDR_REF(NGPTOT,KLEV,1) ) 

ALLOCATE(PQICE_REF_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PQLI_REF_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PECT_REF_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PPRODTH_REF_B(NPROMA, 0:KLEV, NGPBLKS))
ALLOCATE(PNLAB_REF_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PNLABCVP_REF_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PKTROV_REF_B(NPROMA, 0:KLEV, NGPBLKS))
ALLOCATE(PKQROV_REF_B(NPROMA, 0:KLEV, NGPBLKS))
ALLOCATE(PKQLROV_REF_B(NPROMA, 0:KLEV, NGPBLKS))
ALLOCATE(PKUROV_REF_B(NPROMA, 0:KLEV, NGPBLKS))
ALLOCATE(PXTROV_REF_B(NPROMA, 0:KLEV, NGPBLKS))
ALLOCATE(PXUROV_REF_B(NPROMA, 0:KLEV, NGPBLKS))
ALLOCATE(PNBVNO_REF_B(NPROMA, 0:KLEV, NGPBLKS))
ALLOCATE(PNEBS_REF_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PQCS_REF_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PNEBS0_REF_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PQCS0_REF_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PCOEFN_REF_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PECT1_REF_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PFECT_REF_B(NPROMA, 0:KLEV, NGPBLKS))
ALLOCATE(PFECTI_REF_B(NPROMA, 0:KLEV, NGPBLKS))
ALLOCATE(PTPRDY_REF_B(NPROMA, 1:KLEV, NGPBLKS))
ALLOCATE(PEDR_REF_B(NPROMA, 1:KLEV, NGPBLKS))



IOFF = 0
DO I = CLCASE_MIN, CLCASE_MAX
  write(FILENAME, '(A,I0.4,A,I0.4)' ) TRIM(CLCASE)//"."//"OUT.",CLCASE_NUM, ".", I
  write(*,*) FILENAME

  OPEN (ILUN, FILE=FILENAME, FORM="UNFORMATTED")
  READ (ILUN) KLON
  READ (ILUN) KTDIAT
  READ (ILUN) KTDIAN

  READ(ILUN) PQICE_REF(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PQLI_REF(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PECT_REF(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PPRODTH_REF(1+IOFF:KLON+IOFF,0:KLEV,1)
  READ(ILUN) PNLAB_REF(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PNLABCVP_REF(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PKTROV_REF(1+IOFF:KLON+IOFF,0:KLEV,1)
  READ(ILUN) PKQROV_REF(1+IOFF:KLON+IOFF,0:KLEV,1)
  READ(ILUN) PKQLROV_REF(1+IOFF:KLON+IOFF,0:KLEV,1)
  READ(ILUN) PKUROV_REF(1+IOFF:KLON+IOFF,0:KLEV,1)
  READ(ILUN) PXTROV_REF(1+IOFF:KLON+IOFF,0:KLEV,1)
  READ(ILUN) PXUROV_REF(1+IOFF:KLON+IOFF,0:KLEV,1)
  READ(ILUN) PNBVNO_REF(1+IOFF:KLON+IOFF,0:KLEV,1)
  READ(ILUN) PNEBS_REF(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PQCS_REF(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PNEBS0_REF(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PQCS0_REF(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PCOEFN_REF(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PECT1_REF(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PFECT_REF(1+IOFF:KLON+IOFF,0:KLEV,1)
  READ(ILUN) PFECTI_REF(1+IOFF:KLON+IOFF,0:KLEV,1)
  READ(ILUN) PTPRDY_REF(1+IOFF:KLON+IOFF,1:KLEV,1)
  READ(ILUN) PEDR_REF(1+IOFF:KLON+IOFF,1:KLEV,1)
 
  CLOSE(ILUN)

  IOFF = IOFF + KLON
END DO


  CALL REPLICATE(KLONTOT, PQICE_REF(:,:,1))
  CALL NPROMIZE(NPROMA, PQICE_REF, PQICE_REF_B)

  CALL REPLICATE(KLONTOT, PQLI_REF(:,:,1))
  CALL NPROMIZE(NPROMA, PQLI_REF, PQLI_REF_B)

  CALL REPLICATE(KLONTOT, PECT_REF(:,:,1))
  CALL NPROMIZE(NPROMA, PECT_REF, PECT_REF_B)

  CALL REPLICATE(KLONTOT, PPRODTH_REF(:,:,1))
  CALL NPROMIZE(NPROMA, PPRODTH_REF, PPRODTH_REF_B)

  CALL REPLICATE(KLONTOT, PNLAB_REF(:,:,1))
  CALL NPROMIZE(NPROMA, PNLAB_REF, PNLAB_REF_B)

  CALL REPLICATE(KLONTOT, PNLABCVP_REF(:,:,1))
  CALL NPROMIZE(NPROMA, PNLABCVP_REF, PNLABCVP_REF_B)

  CALL REPLICATE(KLONTOT, PKTROV_REF(:,:,1))
  CALL NPROMIZE(NPROMA, PKTROV_REF, PKTROV_REF_B)

  CALL REPLICATE(KLONTOT, PKQROV_REF(:,:,1))
  CALL NPROMIZE(NPROMA, PKQROV_REF, PKQROV_REF_B)

  CALL REPLICATE(KLONTOT, PKQLROV_REF(:,:,1))
  CALL NPROMIZE(NPROMA, PKQLROV_REF, PKQLROV_REF_B)

  CALL REPLICATE(KLONTOT, PKUROV_REF(:,:,1))
  CALL NPROMIZE(NPROMA, PKUROV_REF, PKUROV_REF_B)

  CALL REPLICATE(KLONTOT, PXTROV_REF(:,:,1))
  CALL NPROMIZE(NPROMA, PXTROV_REF, PXTROV_REF_B)

  CALL REPLICATE(KLONTOT, PXUROV_REF(:,:,1))
  CALL NPROMIZE(NPROMA, PXUROV_REF, PXUROV_REF_B)

  CALL REPLICATE(KLONTOT, PNBVNO_REF(:,:,1))
  CALL NPROMIZE(NPROMA, PNBVNO_REF, PNBVNO_REF_B)

  CALL REPLICATE(KLONTOT, PNEBS_REF(:,:,1))
  CALL NPROMIZE(NPROMA, PNEBS_REF, PNEBS_REF_B)

  CALL REPLICATE(KLONTOT, PQCS_REF(:,:,1))
  CALL NPROMIZE(NPROMA, PQCS_REF, PQCS_REF_B)

  CALL REPLICATE(KLONTOT, PNEBS0_REF(:,:,1))
  CALL NPROMIZE(NPROMA, PNEBS0_REF, PNEBS0_REF_B)

  CALL REPLICATE(KLONTOT, PQCS0_REF(:,:,1))
  CALL NPROMIZE(NPROMA, PQCS0_REF, PQCS0_REF_B)

  CALL REPLICATE(KLONTOT, PCOEFN_REF(:,:,1))
  CALL NPROMIZE(NPROMA, PCOEFN_REF, PCOEFN_REF_B)

  CALL REPLICATE(KLONTOT, PECT1_REF(:,:,1))
  CALL NPROMIZE(NPROMA, PECT1_REF, PECT1_REF_B)

  CALL REPLICATE(KLONTOT, PFECT_REF(:,:,1))
  CALL NPROMIZE(NPROMA, PFECT_REF, PFECT_REF_B)

  CALL REPLICATE(KLONTOT, PFECTI_REF(:,:,1))
  CALL NPROMIZE(NPROMA, PFECTI_REF, PFECTI_REF_B)

  CALL REPLICATE(KLONTOT, PTPRDY_REF(:,:,1))
  CALL NPROMIZE(NPROMA, PTPRDY_REF, PTPRDY_REF_B)

  CALL REPLICATE(KLONTOT, PEDR_REF(:,:,1))
  CALL NPROMIZE(NPROMA, PEDR_REF, PEDR_REF_B)


END SUBROUTINE 

SUBROUTINE REPLICATE2 (KOFF, P)

INTEGER :: KOFF
REAL (KIND=JPRB)    :: P (:,:)

INTEGER :: I, J

DO I = KOFF+1, SIZE (P, 1)
  J = 1 + MODULO (I - 1, KOFF)
  P (I, :) = P (J, :)
ENDDO

END SUBROUTINE

SUBROUTINE REPLICATE1 (KOFF, P)

INTEGER :: KOFF
REAL (KIND=JPRB)    :: P (:)

INTEGER :: I, J

DO I = KOFF+1, SIZE (P, 1)
  J = 1 + MODULO (I - 1, KOFF)
  P (I) = P (J)
ENDDO

END SUBROUTINE

SUBROUTINE NPROMIZE2 (KPROMA, PI, PO)

INTEGER :: KPROMA
REAL (KIND=JPRB),  INTENT (IN)  :: PI (:,:) 
REAL (KIND=JPRB),  INTENT (OUT) :: PO (:,:)

INTEGER :: I, J, IGPBLK, IGPTOT, IGP, JLON, JIDIA, JFDIA

IF (SIZE (PI, 2) /= 1) STOP 1

IGPTOT = SIZE (PI, 1)
IGPBLK = 1 + (IGPTOT-1) / KPROMA

DO IGP = 1, IGPTOT, KPROMA
  IBL = 1 + (IGP - 1) / KPROMA
  JIDIA = 1
  JFDIA = MIN (KPROMA, IGPTOT - (IBL - 1) * KPROMA)

  DO JLON = JIDIA, JFDIA
    PO (JLON, IBL) = PI (IGP + (JLON - 1), 1)
  ENDDO

  DO JLON = JFDIA+1, KPROMA
    PO (JLON, IBL) = PO (JFDIA, IBL)
  ENDDO

ENDDO

END SUBROUTINE

SUBROUTINE NPROMIZE3 (KPROMA, PI, PO)

INTEGER :: KPROMA
REAL (KIND=JPRB),  INTENT (IN)  :: PI (:,:,:) 
REAL (KIND=JPRB),  INTENT (OUT) :: PO (:,:,:)

INTEGER :: I, J, IGPBLK, IGPTOT, IGP, JLON, JIDIA, JFDIA

IF (SIZE (PI, 3) /= 1) STOP 1

IGPTOT = SIZE (PI, 1)
IGPBLK = 1 + (IGPTOT-1) / KPROMA

DO IGP = 1, IGPTOT, KPROMA
  IBL = 1 + (IGP - 1) / KPROMA
  JIDIA = 1
  JFDIA = MIN (KPROMA, IGPTOT - (IBL - 1) * KPROMA)

  DO JLON = JIDIA, JFDIA
    PO (JLON, :, IBL) = PI (IGP + (JLON - 1), :, 1)
  ENDDO

  DO JLON = JFDIA+1, KPROMA
    PO (JLON, :, IBL) = PI (JFDIA, :, IBL)
  ENDDO

ENDDO

END SUBROUTINE

END  MODULE
