MODULE UTIL_TPHY3_MOD

USE YOMPHY3, ONLY : TPHY3

INTERFACE SAVE
MODULE PROCEDURE SAVE_TPHY3
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TPHY3
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TPHY3
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TPHY3
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TPHY3 (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPHY3), INTENT (IN) :: YD

WRITE (KLUN) YD%N_SPBAND
WRITE (KLUN) YD%RTL
WRITE (KLUN) YD%BSFSA
WRITE (KLUN) YD%BSFSI
WRITE (KLUN) YD%BSFSN
WRITE (KLUN) YD%BSFTA
WRITE (KLUN) YD%BSFTI
WRITE (KLUN) YD%BSFTN
WRITE (KLUN) YD%EARRT
WRITE (KLUN) YD%EOASA
WRITE (KLUN) YD%EOASI
WRITE (KLUN) YD%EOASN
WRITE (KLUN) YD%EOATA
WRITE (KLUN) YD%EOATI
WRITE (KLUN) YD%EOATN
WRITE (KLUN) YD%EODSA
WRITE (KLUN) YD%EODSI
WRITE (KLUN) YD%EODSN
WRITE (KLUN) YD%EODTA
WRITE (KLUN) YD%EODTI
WRITE (KLUN) YD%EODTN
WRITE (KLUN) YD%EORAY
WRITE (KLUN) YD%GCA
WRITE (KLUN) YD%GCB
WRITE (KLUN) YD%GCC
WRITE (KLUN) YD%GCD4
WRITE (KLUN) YD%GCE4
WRITE (KLUN) YD%GIREC1
WRITE (KLUN) YD%GIREC2
WRITE (KLUN) YD%GIREC3
WRITE (KLUN) YD%GIREC4
WRITE (KLUN) YD%QCO2
WRITE (KLUN) YD%RII0
WRITE (KLUN) YD%USAA
WRITE (KLUN) YD%USAI
WRITE (KLUN) YD%USAN
WRITE (KLUN) YD%USBA
WRITE (KLUN) YD%USBI
WRITE (KLUN) YD%USBN
WRITE (KLUN) YD%VDP
WRITE (KLUN) YD%VNP
WRITE (KLUN) YD%REXP_NEB
WRITE (KLUN) YD%FCM_DEL_A
WRITE (KLUN) YD%FCM_DEL_D
WRITE (KLUN) YD%FCM_MU_A
WRITE (KLUN) YD%FCM_MU_D
WRITE (KLUN) YD%FCM_N_I
WRITE (KLUN) YD%FCM_N_L
WRITE (KLUN) YD%FCM_AI
WRITE (KLUN) YD%FCM_AL
WRITE (KLUN) YD%FCM_B_AI
WRITE (KLUN) YD%FCM_B_AL
WRITE (KLUN) YD%FCM_B_BI
WRITE (KLUN) YD%FCM_B_BL
WRITE (KLUN) YD%FCM_DEL_AI
WRITE (KLUN) YD%FCM_DEL_AL
WRITE (KLUN) YD%FCM_DEL_DI
WRITE (KLUN) YD%FCM_DEL_DL
WRITE (KLUN) YD%FCM_MU_AI
WRITE (KLUN) YD%FCM_MU_AL
WRITE (KLUN) YD%FCM_MU_DI
WRITE (KLUN) YD%FCM_MU_DL
WRITE (KLUN) YD%FCM_NU_AI
WRITE (KLUN) YD%FCM_NU_AL
WRITE (KLUN) YD%FCM_NU_DI
WRITE (KLUN) YD%FCM_NU_DL
WRITE (KLUN) YD%FCM_IWC2DE
WRITE (KLUN) YD%FCM_LWC2RE
WRITE (KLUN) YD%FCM_P_AI
WRITE (KLUN) YD%FCM_P_AL
WRITE (KLUN) YD%FCM_P_DI
WRITE (KLUN) YD%FCM_P_DL
WRITE (KLUN) YD%FCM_P_GI
WRITE (KLUN) YD%FCM_P_GL
WRITE (KLUN) YD%FCM_Q_AI
WRITE (KLUN) YD%FCM_Q_AL
WRITE (KLUN) YD%FCM_Q_DI
WRITE (KLUN) YD%FCM_Q_DL
WRITE (KLUN) YD%FCM_Q_GI
WRITE (KLUN) YD%FCM_Q_GL
WRITE (KLUN) YD%FSM_AA
WRITE (KLUN) YD%FSM_BB
WRITE (KLUN) YD%FSM_CC
WRITE (KLUN) YD%FSM_DD
WRITE (KLUN) YD%FSM_EE
WRITE (KLUN) YD%FSM_FF
WRITE (KLUN) YD%FSM_GG
WRITE (KLUN) YD%FSM_HH
WRITE (KLUN) YD%FSM_II
WRITE (KLUN) YD%GOLCA
WRITE (KLUN) YD%GOLCB
WRITE (KLUN) YD%GOLCC
WRITE (KLUN) YD%FGTS_A
WRITE (KLUN) YD%FGTS_B
WRITE (KLUN) YD%FGTS_C
WRITE (KLUN) YD%FGTS_ALPHA
WRITE (KLUN) YD%FGTS_DELTA0
WRITE (KLUN) YD%FGTS_D
WRITE (KLUN) YD%FGTS_P00
WRITE (KLUN) YD%FGTS_P
WRITE (KLUN) YD%FGTS_Q
WRITE (KLUN) YD%FGTS_OA
WRITE (KLUN) YD%FGTS_OB
WRITE (KLUN) YD%FGTS_OC
WRITE (KLUN) YD%FGTS_OD
WRITE (KLUN) YD%FGTC_A
WRITE (KLUN) YD%FGTC_B
WRITE (KLUN) YD%FGTC_C
WRITE (KLUN) YD%FGTC_ALPHA
WRITE (KLUN) YD%FGTC_DELTA0
WRITE (KLUN) YD%FGTC_D
WRITE (KLUN) YD%FGTC_P00
WRITE (KLUN) YD%FGTC_P
WRITE (KLUN) YD%FGTC_Q
WRITE (KLUN) YD%FGTC_OA
WRITE (KLUN) YD%FGTC_OB
WRITE (KLUN) YD%FGTC_OC
WRITE (KLUN) YD%FGTC_OD
WRITE (KLUN) YD%FGTT_A
WRITE (KLUN) YD%FGTT_B
WRITE (KLUN) YD%FGTT_C
WRITE (KLUN) YD%FGTT_ALPHA
WRITE (KLUN) YD%FGTT_DELTA0
WRITE (KLUN) YD%FGTT_D
WRITE (KLUN) YD%FGTT_P00
WRITE (KLUN) YD%FGTT_P
WRITE (KLUN) YD%FGTT_Q
WRITE (KLUN) YD%FGTT_OA
WRITE (KLUN) YD%FGTT_OB
WRITE (KLUN) YD%FGTT_OC
WRITE (KLUN) YD%FGTT_OD
WRITE (KLUN) YD%FRS_K_SCAT0
WRITE (KLUN) YD%FRS_P_CRIT
WRITE (KLUN) YD%FRS_BETA
WRITE (KLUN) YD%RLAMB_SOLID
WRITE (KLUN) YD%RLAMB_WATER
WRITE (KLUN) YD%RMIXD
WRITE (KLUN) YD%RMIXP0
END SUBROUTINE
SUBROUTINE LOAD_TPHY3 (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPHY3), INTENT (OUT) :: YD

READ (KLUN) YD%N_SPBAND
READ (KLUN) YD%RTL
READ (KLUN) YD%BSFSA
READ (KLUN) YD%BSFSI
READ (KLUN) YD%BSFSN
READ (KLUN) YD%BSFTA
READ (KLUN) YD%BSFTI
READ (KLUN) YD%BSFTN
READ (KLUN) YD%EARRT
READ (KLUN) YD%EOASA
READ (KLUN) YD%EOASI
READ (KLUN) YD%EOASN
READ (KLUN) YD%EOATA
READ (KLUN) YD%EOATI
READ (KLUN) YD%EOATN
READ (KLUN) YD%EODSA
READ (KLUN) YD%EODSI
READ (KLUN) YD%EODSN
READ (KLUN) YD%EODTA
READ (KLUN) YD%EODTI
READ (KLUN) YD%EODTN
READ (KLUN) YD%EORAY
READ (KLUN) YD%GCA
READ (KLUN) YD%GCB
READ (KLUN) YD%GCC
READ (KLUN) YD%GCD4
READ (KLUN) YD%GCE4
READ (KLUN) YD%GIREC1
READ (KLUN) YD%GIREC2
READ (KLUN) YD%GIREC3
READ (KLUN) YD%GIREC4
READ (KLUN) YD%QCO2
READ (KLUN) YD%RII0
READ (KLUN) YD%USAA
READ (KLUN) YD%USAI
READ (KLUN) YD%USAN
READ (KLUN) YD%USBA
READ (KLUN) YD%USBI
READ (KLUN) YD%USBN
READ (KLUN) YD%VDP
READ (KLUN) YD%VNP
READ (KLUN) YD%REXP_NEB
READ (KLUN) YD%FCM_DEL_A
READ (KLUN) YD%FCM_DEL_D
READ (KLUN) YD%FCM_MU_A
READ (KLUN) YD%FCM_MU_D
READ (KLUN) YD%FCM_N_I
READ (KLUN) YD%FCM_N_L
READ (KLUN) YD%FCM_AI
READ (KLUN) YD%FCM_AL
READ (KLUN) YD%FCM_B_AI
READ (KLUN) YD%FCM_B_AL
READ (KLUN) YD%FCM_B_BI
READ (KLUN) YD%FCM_B_BL
READ (KLUN) YD%FCM_DEL_AI
READ (KLUN) YD%FCM_DEL_AL
READ (KLUN) YD%FCM_DEL_DI
READ (KLUN) YD%FCM_DEL_DL
READ (KLUN) YD%FCM_MU_AI
READ (KLUN) YD%FCM_MU_AL
READ (KLUN) YD%FCM_MU_DI
READ (KLUN) YD%FCM_MU_DL
READ (KLUN) YD%FCM_NU_AI
READ (KLUN) YD%FCM_NU_AL
READ (KLUN) YD%FCM_NU_DI
READ (KLUN) YD%FCM_NU_DL
READ (KLUN) YD%FCM_IWC2DE
READ (KLUN) YD%FCM_LWC2RE
READ (KLUN) YD%FCM_P_AI
READ (KLUN) YD%FCM_P_AL
READ (KLUN) YD%FCM_P_DI
READ (KLUN) YD%FCM_P_DL
READ (KLUN) YD%FCM_P_GI
READ (KLUN) YD%FCM_P_GL
READ (KLUN) YD%FCM_Q_AI
READ (KLUN) YD%FCM_Q_AL
READ (KLUN) YD%FCM_Q_DI
READ (KLUN) YD%FCM_Q_DL
READ (KLUN) YD%FCM_Q_GI
READ (KLUN) YD%FCM_Q_GL
READ (KLUN) YD%FSM_AA
READ (KLUN) YD%FSM_BB
READ (KLUN) YD%FSM_CC
READ (KLUN) YD%FSM_DD
READ (KLUN) YD%FSM_EE
READ (KLUN) YD%FSM_FF
READ (KLUN) YD%FSM_GG
READ (KLUN) YD%FSM_HH
READ (KLUN) YD%FSM_II
READ (KLUN) YD%GOLCA
READ (KLUN) YD%GOLCB
READ (KLUN) YD%GOLCC
READ (KLUN) YD%FGTS_A
READ (KLUN) YD%FGTS_B
READ (KLUN) YD%FGTS_C
READ (KLUN) YD%FGTS_ALPHA
READ (KLUN) YD%FGTS_DELTA0
READ (KLUN) YD%FGTS_D
READ (KLUN) YD%FGTS_P00
READ (KLUN) YD%FGTS_P
READ (KLUN) YD%FGTS_Q
READ (KLUN) YD%FGTS_OA
READ (KLUN) YD%FGTS_OB
READ (KLUN) YD%FGTS_OC
READ (KLUN) YD%FGTS_OD
READ (KLUN) YD%FGTC_A
READ (KLUN) YD%FGTC_B
READ (KLUN) YD%FGTC_C
READ (KLUN) YD%FGTC_ALPHA
READ (KLUN) YD%FGTC_DELTA0
READ (KLUN) YD%FGTC_D
READ (KLUN) YD%FGTC_P00
READ (KLUN) YD%FGTC_P
READ (KLUN) YD%FGTC_Q
READ (KLUN) YD%FGTC_OA
READ (KLUN) YD%FGTC_OB
READ (KLUN) YD%FGTC_OC
READ (KLUN) YD%FGTC_OD
READ (KLUN) YD%FGTT_A
READ (KLUN) YD%FGTT_B
READ (KLUN) YD%FGTT_C
READ (KLUN) YD%FGTT_ALPHA
READ (KLUN) YD%FGTT_DELTA0
READ (KLUN) YD%FGTT_D
READ (KLUN) YD%FGTT_P00
READ (KLUN) YD%FGTT_P
READ (KLUN) YD%FGTT_Q
READ (KLUN) YD%FGTT_OA
READ (KLUN) YD%FGTT_OB
READ (KLUN) YD%FGTT_OC
READ (KLUN) YD%FGTT_OD
READ (KLUN) YD%FRS_K_SCAT0
READ (KLUN) YD%FRS_P_CRIT
READ (KLUN) YD%FRS_BETA
READ (KLUN) YD%RLAMB_SOLID
READ (KLUN) YD%RLAMB_WATER
READ (KLUN) YD%RMIXD
READ (KLUN) YD%RMIXP0
END SUBROUTINE

SUBROUTINE COPY_TPHY3 (YD, LDCREATED)

IMPLICIT NONE
TYPE (TPHY3), INTENT (IN) :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF










































































































































END SUBROUTINE
INTEGER*8 FUNCTION SIZE_TPHY3 (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TPHY3),     INTENT (IN) :: YD
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
LOGICAL,          INTENT (IN) :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE

KSIZE = 0
ISIZE = KIND (YD%N_SPBAND)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%N_SPBAND'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RTL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RTL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%BSFSA) * SIZE (YD%BSFSA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%BSFSA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%BSFSI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%BSFSI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%BSFSN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%BSFSN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%BSFTA) * SIZE (YD%BSFTA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%BSFTA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%BSFTI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%BSFTI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%BSFTN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%BSFTN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%EARRT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%EARRT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%EOASA) * SIZE (YD%EOASA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%EOASA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%EOASI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%EOASI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%EOASN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%EOASN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%EOATA) * SIZE (YD%EOATA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%EOATA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%EOATI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%EOATI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%EOATN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%EOATN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%EODSA) * SIZE (YD%EODSA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%EODSA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%EODSI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%EODSI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%EODSN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%EODSN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%EODTA) * SIZE (YD%EODTA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%EODTA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%EODTI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%EODTI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%EODTN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%EODTN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%EORAY)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%EORAY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCA) * SIZE (YD%GCA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCB) * SIZE (YD%GCB)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCC) * SIZE (YD%GCC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCD4)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCD4'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCE4)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCE4'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GIREC1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GIREC1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GIREC2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GIREC2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GIREC3)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GIREC3'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GIREC4)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GIREC4'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%QCO2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%QCO2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RII0)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RII0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%USAA) * SIZE (YD%USAA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%USAA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%USAI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%USAI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%USAN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%USAN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%USBA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%USBA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%USBI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%USBI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%USBN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%USBN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VDP) * SIZE (YD%VDP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VDP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VNP) * SIZE (YD%VNP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VNP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%REXP_NEB)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%REXP_NEB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_DEL_A) * SIZE (YD%FCM_DEL_A)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_DEL_A'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_DEL_D) * SIZE (YD%FCM_DEL_D)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_DEL_D'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_MU_A) * SIZE (YD%FCM_MU_A)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_MU_A'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_MU_D) * SIZE (YD%FCM_MU_D)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_MU_D'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_N_I)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_N_I'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_N_L)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_N_L'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_AI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_AI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_AL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_AL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_B_AI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_B_AI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_B_AL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_B_AL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_B_BI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_B_BI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_B_BL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_B_BL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_DEL_AI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_DEL_AI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_DEL_AL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_DEL_AL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_DEL_DI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_DEL_DI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_DEL_DL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_DEL_DL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_MU_AI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_MU_AI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_MU_AL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_MU_AL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_MU_DI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_MU_DI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_MU_DL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_MU_DL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_NU_AI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_NU_AI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_NU_AL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_NU_AL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_NU_DI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_NU_DI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_NU_DL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_NU_DL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_IWC2DE) * SIZE (YD%FCM_IWC2DE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_IWC2DE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_LWC2RE) * SIZE (YD%FCM_LWC2RE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_LWC2RE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_P_AI) * SIZE (YD%FCM_P_AI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_P_AI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_P_AL) * SIZE (YD%FCM_P_AL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_P_AL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_P_DI) * SIZE (YD%FCM_P_DI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_P_DI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_P_DL) * SIZE (YD%FCM_P_DL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_P_DL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_P_GI) * SIZE (YD%FCM_P_GI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_P_GI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_P_GL) * SIZE (YD%FCM_P_GL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_P_GL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_Q_AI) * SIZE (YD%FCM_Q_AI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_Q_AI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_Q_AL) * SIZE (YD%FCM_Q_AL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_Q_AL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_Q_DI) * SIZE (YD%FCM_Q_DI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_Q_DI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_Q_DL) * SIZE (YD%FCM_Q_DL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_Q_DL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_Q_GI) * SIZE (YD%FCM_Q_GI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_Q_GI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FCM_Q_GL) * SIZE (YD%FCM_Q_GL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FCM_Q_GL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FSM_AA) * SIZE (YD%FSM_AA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FSM_AA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FSM_BB) * SIZE (YD%FSM_BB)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FSM_BB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FSM_CC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FSM_CC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FSM_DD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FSM_DD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FSM_EE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FSM_EE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FSM_FF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FSM_FF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FSM_GG)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FSM_GG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FSM_HH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FSM_HH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FSM_II)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FSM_II'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GOLCA) * SIZE (YD%GOLCA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GOLCA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GOLCB) * SIZE (YD%GOLCB)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GOLCB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GOLCC) * SIZE (YD%GOLCC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GOLCC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTS_A) * SIZE (YD%FGTS_A)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTS_A'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTS_B) * SIZE (YD%FGTS_B)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTS_B'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTS_C) * SIZE (YD%FGTS_C)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTS_C'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTS_ALPHA) * SIZE (YD%FGTS_ALPHA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTS_ALPHA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTS_DELTA0) * SIZE (YD%FGTS_DELTA0)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTS_DELTA0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTS_D) * SIZE (YD%FGTS_D)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTS_D'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTS_P00) * SIZE (YD%FGTS_P00)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTS_P00'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTS_P) * SIZE (YD%FGTS_P)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTS_P'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTS_Q) * SIZE (YD%FGTS_Q)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTS_Q'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTS_OA) * SIZE (YD%FGTS_OA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTS_OA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTS_OB) * SIZE (YD%FGTS_OB)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTS_OB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTS_OC) * SIZE (YD%FGTS_OC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTS_OC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTS_OD) * SIZE (YD%FGTS_OD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTS_OD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTC_A) * SIZE (YD%FGTC_A)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTC_A'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTC_B) * SIZE (YD%FGTC_B)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTC_B'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTC_C) * SIZE (YD%FGTC_C)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTC_C'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTC_ALPHA) * SIZE (YD%FGTC_ALPHA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTC_ALPHA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTC_DELTA0) * SIZE (YD%FGTC_DELTA0)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTC_DELTA0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTC_D) * SIZE (YD%FGTC_D)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTC_D'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTC_P00) * SIZE (YD%FGTC_P00)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTC_P00'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTC_P) * SIZE (YD%FGTC_P)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTC_P'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTC_Q) * SIZE (YD%FGTC_Q)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTC_Q'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTC_OA) * SIZE (YD%FGTC_OA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTC_OA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTC_OB) * SIZE (YD%FGTC_OB)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTC_OB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTC_OC) * SIZE (YD%FGTC_OC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTC_OC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTC_OD) * SIZE (YD%FGTC_OD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTC_OD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTT_A) * SIZE (YD%FGTT_A)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTT_A'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTT_B) * SIZE (YD%FGTT_B)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTT_B'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTT_C) * SIZE (YD%FGTT_C)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTT_C'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTT_ALPHA) * SIZE (YD%FGTT_ALPHA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTT_ALPHA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTT_DELTA0) * SIZE (YD%FGTT_DELTA0)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTT_DELTA0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTT_D) * SIZE (YD%FGTT_D)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTT_D'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTT_P00) * SIZE (YD%FGTT_P00)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTT_P00'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTT_P) * SIZE (YD%FGTT_P)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTT_P'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTT_Q) * SIZE (YD%FGTT_Q)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTT_Q'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTT_OA) * SIZE (YD%FGTT_OA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTT_OA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTT_OB) * SIZE (YD%FGTT_OB)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTT_OB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTT_OC) * SIZE (YD%FGTT_OC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTT_OC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FGTT_OD) * SIZE (YD%FGTT_OD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FGTT_OD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FRS_K_SCAT0)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FRS_K_SCAT0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FRS_P_CRIT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FRS_P_CRIT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FRS_BETA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FRS_BETA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RLAMB_SOLID)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RLAMB_SOLID'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RLAMB_WATER)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RLAMB_WATER'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RMIXD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RMIXD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RMIXP0)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RMIXP0'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
