MODULE UTIL_TPARAR_MOD

USE YOMPARAR, ONLY : TPARAR

INTERFACE SAVE
MODULE PROCEDURE SAVE_TPARAR
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TPARAR
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TPARAR
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TPARAR
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TPARAR (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPARAR), INTENT (IN) :: YD
LOGICAL :: LXSW_BANDS
WRITE (KLUN) YD%CMICRO
WRITE (KLUN) YD%CSEDIM
WRITE (KLUN) YD%NSPLITR
WRITE (KLUN) YD%NSPLITG
WRITE (KLUN) YD%NRR
WRITE (KLUN) YD%NRRL
WRITE (KLUN) YD%NRRI
WRITE (KLUN) YD%NSV
WRITE (KLUN) YD%NSWB_MNH
WRITE (KLUN) YD%NGPAR
WRITE (KLUN) YD%MINPRR
WRITE (KLUN) YD%MINPRS
WRITE (KLUN) YD%MINPRG
WRITE (KLUN) YD%MACPRR
WRITE (KLUN) YD%MACPRS
WRITE (KLUN) YD%MACPRG
WRITE (KLUN) YD%MALBDIR
WRITE (KLUN) YD%MALBSCA
WRITE (KLUN) YD%MRAIN
WRITE (KLUN) YD%MSNOW
WRITE (KLUN) YD%MGZ0
WRITE (KLUN) YD%MGZ0H
WRITE (KLUN) YD%MVQS
WRITE (KLUN) YD%MVTS
WRITE (KLUN) YD%MVEMIS
WRITE (KLUN) YD%MSWDIR
WRITE (KLUN) YD%MSWDIF
WRITE (KLUN) YD%MLSM
WRITE (KLUN) YD%MCD
LXSW_BANDS = ALLOCATED (YD%XSW_BANDS)
WRITE (KLUN) LXSW_BANDS
IF (LXSW_BANDS) THEN
  WRITE (KLUN) LBOUND (YD%XSW_BANDS)
  WRITE (KLUN) UBOUND (YD%XSW_BANDS)
  WRITE (KLUN) YD%XSW_BANDS
ENDIF
WRITE (KLUN) YD%LOSUBG_COND
WRITE (KLUN) YD%LOSEDIC
WRITE (KLUN) YD%LOWARM
WRITE (KLUN) YD%LOSIGMAS
WRITE (KLUN) YD%LOLSMC
WRITE (KLUN) YD%LOTOWNC
WRITE (KLUN) YD%LOCND2
WRITE (KLUN) YD%LKOGAN
WRITE (KLUN) YD%LMODICEDEP
WRITE (KLUN) YD%LICERAD
WRITE (KLUN) YD%RADGR
WRITE (KLUN) YD%RADSN
WRITE (KLUN) YD%VSIGQSAT
WRITE (KLUN) YD%RFRMIN
WRITE (KLUN) YD%CMF_UPDRAFT
WRITE (KLUN) YD%CMF_CLOUD
WRITE (KLUN) YD%LMIXUV
WRITE (KLUN) YD%LLCRIT
WRITE (KLUN) YD%LTOTPREC
WRITE (KLUN) YD%LTOTPRECL
WRITE (KLUN) YD%LHGT_QS
WRITE (KLUN) YD%XALP_PERT
WRITE (KLUN) YD%XABUO
WRITE (KLUN) YD%XBENTR
WRITE (KLUN) YD%XBDETR
WRITE (KLUN) YD%XCMF
WRITE (KLUN) YD%XENTR_MF
WRITE (KLUN) YD%XCRAD_MF
WRITE (KLUN) YD%XENTR_DRY
WRITE (KLUN) YD%XDETR_DRY
WRITE (KLUN) YD%XDETR_LUP
WRITE (KLUN) YD%XKCF_MF
WRITE (KLUN) YD%XKRC_MF
WRITE (KLUN) YD%XTAUSIGMF
WRITE (KLUN) YD%XPRES_UV
WRITE (KLUN) YD%XFRAC_UP_MAX
WRITE (KLUN) YD%XALPHA_MF
WRITE (KLUN) YD%XSIGMA_MF
WRITE (KLUN) YD%XA1
WRITE (KLUN) YD%XB
WRITE (KLUN) YD%XC
WRITE (KLUN) YD%XBETA1
WRITE (KLUN) YD%XR
WRITE (KLUN) YD%XLAMBDA
WRITE (KLUN) YD%LTHETAS
WRITE (KLUN) YD%LSQUALL
WRITE (KLUN) YD%NREFROI1
WRITE (KLUN) YD%NREFROI2
WRITE (KLUN) YD%VSQUALL
WRITE (KLUN) YD%NPTP
WRITE (KLUN) YD%NPRINTFR
WRITE (KLUN) YD%LDIAGWMAX
WRITE (KLUN) YD%NDIAGWMAX
WRITE (KLUN) YD%NDTCHEM
WRITE (KLUN) YD%LAROBU_ENABLE
WRITE (KLUN) YD%XLINI
WRITE (KLUN) YD%LSTATNW
WRITE (KLUN) YD%LHARATU
WRITE (KLUN) YD%CSUBG_AUCV_RC
WRITE (KLUN) YD%CSUBG_RC_RR_ACCR
WRITE (KLUN) YD%CSUBG_RR_EVAP
WRITE (KLUN) YD%CSUBG_PR_PDF
WRITE (KLUN) YD%RCRIAUTI
WRITE (KLUN) YD%RCRIAUTC
WRITE (KLUN) YD%RT0CRIAUTI
WRITE (KLUN) YD%LCRIAUTI
WRITE (KLUN) YD%XTSTEP_TS
WRITE (KLUN) YD%XMRSTEP
WRITE (KLUN) YD%NMAXITER_MICRO
WRITE (KLUN) YD%CSNOWRIMING
WRITE (KLUN) YD%XFRACM90
WRITE (KLUN) YD%LNULLWETG
WRITE (KLUN) YD%LWETGPOST
WRITE (KLUN) YD%LNULLWETH
WRITE (KLUN) YD%LWETHPOST
WRITE (KLUN) YD%LFEEDBACKT
WRITE (KLUN) YD%LEVLIMIT
WRITE (KLUN) YD%LCONVHG
WRITE (KLUN) YD%LCRFLIMIT
WRITE (KLUN) YD%LDEPOSC
WRITE (KLUN) YD%CFRAC_ICE_ADJUST
WRITE (KLUN) YD%CFRAC_ICE_SHALLOW_MF
WRITE (KLUN) YD%LSEDIM_AFTER
WRITE (KLUN) YD%XSPLIT_MAXCFL
WRITE (KLUN) YD%XVDEPOSC
WRITE (KLUN) YD%LDEPSG
WRITE (KLUN) YD%RDEPSRED
WRITE (KLUN) YD%RDEPGRED
WRITE (KLUN) YD%LFPREC3D
WRITE (KLUN) YD%XCQVR
WRITE (KLUN) YD%GQVPLIM
WRITE (KLUN) YD%GQVTOP
WRITE (KLUN) YD%LQVTOP
END SUBROUTINE
SUBROUTINE LOAD_TPARAR (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPARAR), INTENT (OUT) :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LXSW_BANDS
READ (KLUN) YD%CMICRO
READ (KLUN) YD%CSEDIM
READ (KLUN) YD%NSPLITR
READ (KLUN) YD%NSPLITG
READ (KLUN) YD%NRR
READ (KLUN) YD%NRRL
READ (KLUN) YD%NRRI
READ (KLUN) YD%NSV
READ (KLUN) YD%NSWB_MNH
READ (KLUN) YD%NGPAR
READ (KLUN) YD%MINPRR
READ (KLUN) YD%MINPRS
READ (KLUN) YD%MINPRG
READ (KLUN) YD%MACPRR
READ (KLUN) YD%MACPRS
READ (KLUN) YD%MACPRG
READ (KLUN) YD%MALBDIR
READ (KLUN) YD%MALBSCA
READ (KLUN) YD%MRAIN
READ (KLUN) YD%MSNOW
READ (KLUN) YD%MGZ0
READ (KLUN) YD%MGZ0H
READ (KLUN) YD%MVQS
READ (KLUN) YD%MVTS
READ (KLUN) YD%MVEMIS
READ (KLUN) YD%MSWDIR
READ (KLUN) YD%MSWDIF
READ (KLUN) YD%MLSM
READ (KLUN) YD%MCD
READ (KLUN) LXSW_BANDS
IF (LXSW_BANDS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%XSW_BANDS (IL1(1):IU1(1)))
  READ (KLUN) YD%XSW_BANDS
ENDIF
READ (KLUN) YD%LOSUBG_COND
READ (KLUN) YD%LOSEDIC
READ (KLUN) YD%LOWARM
READ (KLUN) YD%LOSIGMAS
READ (KLUN) YD%LOLSMC
READ (KLUN) YD%LOTOWNC
READ (KLUN) YD%LOCND2
READ (KLUN) YD%LKOGAN
READ (KLUN) YD%LMODICEDEP
READ (KLUN) YD%LICERAD
READ (KLUN) YD%RADGR
READ (KLUN) YD%RADSN
READ (KLUN) YD%VSIGQSAT
READ (KLUN) YD%RFRMIN
READ (KLUN) YD%CMF_UPDRAFT
READ (KLUN) YD%CMF_CLOUD
READ (KLUN) YD%LMIXUV
READ (KLUN) YD%LLCRIT
READ (KLUN) YD%LTOTPREC
READ (KLUN) YD%LTOTPRECL
READ (KLUN) YD%LHGT_QS
READ (KLUN) YD%XALP_PERT
READ (KLUN) YD%XABUO
READ (KLUN) YD%XBENTR
READ (KLUN) YD%XBDETR
READ (KLUN) YD%XCMF
READ (KLUN) YD%XENTR_MF
READ (KLUN) YD%XCRAD_MF
READ (KLUN) YD%XENTR_DRY
READ (KLUN) YD%XDETR_DRY
READ (KLUN) YD%XDETR_LUP
READ (KLUN) YD%XKCF_MF
READ (KLUN) YD%XKRC_MF
READ (KLUN) YD%XTAUSIGMF
READ (KLUN) YD%XPRES_UV
READ (KLUN) YD%XFRAC_UP_MAX
READ (KLUN) YD%XALPHA_MF
READ (KLUN) YD%XSIGMA_MF
READ (KLUN) YD%XA1
READ (KLUN) YD%XB
READ (KLUN) YD%XC
READ (KLUN) YD%XBETA1
READ (KLUN) YD%XR
READ (KLUN) YD%XLAMBDA
READ (KLUN) YD%LTHETAS
READ (KLUN) YD%LSQUALL
READ (KLUN) YD%NREFROI1
READ (KLUN) YD%NREFROI2
READ (KLUN) YD%VSQUALL
READ (KLUN) YD%NPTP
READ (KLUN) YD%NPRINTFR
READ (KLUN) YD%LDIAGWMAX
READ (KLUN) YD%NDIAGWMAX
READ (KLUN) YD%NDTCHEM
READ (KLUN) YD%LAROBU_ENABLE
READ (KLUN) YD%XLINI
READ (KLUN) YD%LSTATNW
READ (KLUN) YD%LHARATU
READ (KLUN) YD%CSUBG_AUCV_RC
READ (KLUN) YD%CSUBG_RC_RR_ACCR
READ (KLUN) YD%CSUBG_RR_EVAP
READ (KLUN) YD%CSUBG_PR_PDF
READ (KLUN) YD%RCRIAUTI
READ (KLUN) YD%RCRIAUTC
READ (KLUN) YD%RT0CRIAUTI
READ (KLUN) YD%LCRIAUTI
READ (KLUN) YD%XTSTEP_TS
READ (KLUN) YD%XMRSTEP
READ (KLUN) YD%NMAXITER_MICRO
READ (KLUN) YD%CSNOWRIMING
READ (KLUN) YD%XFRACM90
READ (KLUN) YD%LNULLWETG
READ (KLUN) YD%LWETGPOST
READ (KLUN) YD%LNULLWETH
READ (KLUN) YD%LWETHPOST
READ (KLUN) YD%LFEEDBACKT
READ (KLUN) YD%LEVLIMIT
READ (KLUN) YD%LCONVHG
READ (KLUN) YD%LCRFLIMIT
READ (KLUN) YD%LDEPOSC
READ (KLUN) YD%CFRAC_ICE_ADJUST
READ (KLUN) YD%CFRAC_ICE_SHALLOW_MF
READ (KLUN) YD%LSEDIM_AFTER
READ (KLUN) YD%XSPLIT_MAXCFL
READ (KLUN) YD%XVDEPOSC
READ (KLUN) YD%LDEPSG
READ (KLUN) YD%RDEPSRED
READ (KLUN) YD%RDEPGRED
READ (KLUN) YD%LFPREC3D
READ (KLUN) YD%XCQVR
READ (KLUN) YD%GQVPLIM
READ (KLUN) YD%GQVTOP
READ (KLUN) YD%LQVTOP
END SUBROUTINE

SUBROUTINE COPY_TPARAR (YD, LDCREATED)

IMPLICIT NONE
TYPE (TPARAR), INTENT (IN) :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LXSW_BANDS

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF





























LXSW_BANDS = ALLOCATED (YD%XSW_BANDS)
IF (LXSW_BANDS) THEN
  !$acc enter data create (YD%XSW_BANDS)
  !$acc update device (YD%XSW_BANDS)
  !$acc enter data attach (YD%XSW_BANDS)
ENDIF






























































































END SUBROUTINE
INTEGER*8 FUNCTION SIZE_TPARAR (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TPARAR),     INTENT (IN) :: YD
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
LOGICAL,          INTENT (IN) :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LXSW_BANDS

KSIZE = 0
ISIZE = KIND (YD%CMICRO) * LEN (YD%CMICRO)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%CMICRO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CSEDIM) * LEN (YD%CSEDIM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%CSEDIM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSPLITR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NSPLITR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSPLITG)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NSPLITG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NRR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NRR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NRRL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NRRL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NRRI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NRRI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NSV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSWB_MNH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NSWB_MNH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NGPAR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NGPAR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MINPRR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%MINPRR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MINPRS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%MINPRS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MINPRG)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%MINPRG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MACPRR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%MACPRR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MACPRS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%MACPRS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MACPRG)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%MACPRG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MALBDIR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%MALBDIR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MALBSCA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%MALBSCA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MRAIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%MRAIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MSNOW)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%MSNOW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MGZ0)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%MGZ0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MGZ0H)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%MGZ0H'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MVQS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%MVQS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MVTS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%MVTS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MVEMIS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%MVEMIS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MSWDIR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%MSWDIR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MSWDIF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%MSWDIF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MLSM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%MLSM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MCD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%MCD'
ENDIF
KSIZE = KSIZE + ISIZE
LXSW_BANDS = ALLOCATED (YD%XSW_BANDS)
IF (LXSW_BANDS) THEN
  ISIZE = KIND (YD%XSW_BANDS) * SIZE (YD%XSW_BANDS)
  IF (LDPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CDPATH)//'%XSW_BANDS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
ISIZE = KIND (YD%LOSUBG_COND)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LOSUBG_COND'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LOSEDIC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LOSEDIC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LOWARM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LOWARM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LOSIGMAS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LOSIGMAS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LOLSMC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LOLSMC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LOTOWNC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LOTOWNC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LOCND2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LOCND2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LKOGAN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LKOGAN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LMODICEDEP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LMODICEDEP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LICERAD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LICERAD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RADGR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RADGR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RADSN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RADSN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VSIGQSAT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VSIGQSAT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RFRMIN) * SIZE (YD%RFRMIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RFRMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CMF_UPDRAFT) * LEN (YD%CMF_UPDRAFT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%CMF_UPDRAFT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CMF_CLOUD) * LEN (YD%CMF_CLOUD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%CMF_CLOUD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LMIXUV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LMIXUV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LLCRIT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LLCRIT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LTOTPREC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LTOTPREC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LTOTPRECL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LTOTPRECL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LHGT_QS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LHGT_QS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XALP_PERT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XALP_PERT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XABUO)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XABUO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XBENTR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XBENTR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XBDETR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XBDETR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XCMF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XCMF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XENTR_MF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XENTR_MF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XCRAD_MF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XCRAD_MF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XENTR_DRY)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XENTR_DRY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XDETR_DRY)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XDETR_DRY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XDETR_LUP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XDETR_LUP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XKCF_MF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XKCF_MF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XKRC_MF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XKRC_MF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XTAUSIGMF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XTAUSIGMF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XPRES_UV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XPRES_UV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XFRAC_UP_MAX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XFRAC_UP_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XALPHA_MF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XALPHA_MF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XSIGMA_MF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XSIGMA_MF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XA1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XA1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XB)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XBETA1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XBETA1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XLAMBDA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XLAMBDA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LTHETAS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LTHETAS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSQUALL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LSQUALL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NREFROI1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NREFROI1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NREFROI2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NREFROI2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VSQUALL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VSQUALL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NPTP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NPTP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NPRINTFR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NPRINTFR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LDIAGWMAX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LDIAGWMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDIAGWMAX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NDIAGWMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDTCHEM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NDTCHEM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LAROBU_ENABLE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LAROBU_ENABLE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XLINI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XLINI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSTATNW)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LSTATNW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LHARATU)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LHARATU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CSUBG_AUCV_RC) * LEN (YD%CSUBG_AUCV_RC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%CSUBG_AUCV_RC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CSUBG_RC_RR_ACCR) * LEN (YD%CSUBG_RC_RR_ACCR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%CSUBG_RC_RR_ACCR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CSUBG_RR_EVAP) * LEN (YD%CSUBG_RR_EVAP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%CSUBG_RR_EVAP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CSUBG_PR_PDF) * LEN (YD%CSUBG_PR_PDF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%CSUBG_PR_PDF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RCRIAUTI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RCRIAUTI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RCRIAUTC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RCRIAUTC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RT0CRIAUTI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RT0CRIAUTI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCRIAUTI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LCRIAUTI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XTSTEP_TS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XTSTEP_TS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XMRSTEP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XMRSTEP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NMAXITER_MICRO)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NMAXITER_MICRO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CSNOWRIMING) * LEN (YD%CSNOWRIMING)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%CSNOWRIMING'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XFRACM90)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XFRACM90'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LNULLWETG)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LNULLWETG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LWETGPOST)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LWETGPOST'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LNULLWETH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LNULLWETH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LWETHPOST)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LWETHPOST'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LFEEDBACKT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LFEEDBACKT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LEVLIMIT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LEVLIMIT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCONVHG)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LCONVHG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCRFLIMIT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LCRFLIMIT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LDEPOSC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LDEPOSC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CFRAC_ICE_ADJUST) * LEN (YD%CFRAC_ICE_ADJUST)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%CFRAC_ICE_ADJUST'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CFRAC_ICE_SHALLOW_MF) * LEN (YD%CFRAC_ICE_SHALLOW_MF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%CFRAC_ICE_SHALLOW_MF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSEDIM_AFTER)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LSEDIM_AFTER'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XSPLIT_MAXCFL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XSPLIT_MAXCFL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XVDEPOSC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XVDEPOSC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LDEPSG)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LDEPSG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDEPSRED)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RDEPSRED'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDEPGRED)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RDEPGRED'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LFPREC3D)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LFPREC3D'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XCQVR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XCQVR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GQVPLIM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GQVPLIM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GQVTOP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GQVTOP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LQVTOP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LQVTOP'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
