MODULE UTIL_TDPRECIPS_MOD

USE YOMDPRECIPS, ONLY : TDPRECIPS

INTERFACE SAVE
MODULE PROCEDURE SAVE_TDPRECIPS
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TDPRECIPS
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TDPRECIPS
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TDPRECIPS
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TDPRECIPS (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDPRECIPS), INTENT (IN) :: YD

WRITE (KLUN) YD%HDPRECIPS
WRITE (KLUN) YD%HDCLWC
WRITE (KLUN) YD%RDHAIL1
WRITE (KLUN) YD%RDHAIL2
WRITE (KLUN) YD%RDSEUIL1
WRITE (KLUN) YD%RDSEUIL2
WRITE (KLUN) YD%RDSEUIL3
WRITE (KLUN) YD%RDSEUIL4
WRITE (KLUN) YD%RDSEUIL5
WRITE (KLUN) YD%RDCLWC
WRITE (KLUN) YD%RPRECSEUIL
WRITE (KLUN) YD%RHTOP
WRITE (KLUN) YD%RTPW
WRITE (KLUN) YD%RAWARM
WRITE (KLUN) YD%RACOLD
WRITE (KLUN) YD%NDTPREC
WRITE (KLUN) YD%NDTPREC2
END SUBROUTINE
SUBROUTINE LOAD_TDPRECIPS (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDPRECIPS), INTENT (OUT) :: YD

READ (KLUN) YD%HDPRECIPS
READ (KLUN) YD%HDCLWC
READ (KLUN) YD%RDHAIL1
READ (KLUN) YD%RDHAIL2
READ (KLUN) YD%RDSEUIL1
READ (KLUN) YD%RDSEUIL2
READ (KLUN) YD%RDSEUIL3
READ (KLUN) YD%RDSEUIL4
READ (KLUN) YD%RDSEUIL5
READ (KLUN) YD%RDCLWC
READ (KLUN) YD%RPRECSEUIL
READ (KLUN) YD%RHTOP
READ (KLUN) YD%RTPW
READ (KLUN) YD%RAWARM
READ (KLUN) YD%RACOLD
READ (KLUN) YD%NDTPREC
READ (KLUN) YD%NDTPREC2
END SUBROUTINE

SUBROUTINE COPY_TDPRECIPS (YD, LDCREATED)

IMPLICIT NONE
TYPE (TDPRECIPS), INTENT (IN) :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF

















END SUBROUTINE
INTEGER*8 FUNCTION SIZE_TDPRECIPS (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TDPRECIPS),     INTENT (IN) :: YD
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
LOGICAL,          INTENT (IN) :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE

KSIZE = 0
ISIZE = KIND (YD%HDPRECIPS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%HDPRECIPS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%HDCLWC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%HDCLWC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDHAIL1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RDHAIL1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDHAIL2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RDHAIL2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDSEUIL1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RDSEUIL1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDSEUIL2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RDSEUIL2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDSEUIL3)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RDSEUIL3'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDSEUIL4)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RDSEUIL4'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDSEUIL5)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RDSEUIL5'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDCLWC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RDCLWC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RPRECSEUIL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RPRECSEUIL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RHTOP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RHTOP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RTPW)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RTPW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RAWARM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RAWARM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RACOLD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RACOLD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDTPREC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NDTPREC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDTPREC2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NDTPREC2'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
