MODULE UTIL_TCST_MOD

USE YOMCST, ONLY : TCST

INTERFACE SAVE
MODULE PROCEDURE SAVE_TCST
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCST
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TCST
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TCST
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TCST (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCST), INTENT (IN) :: YD

WRITE (KLUN) YD%RPI
WRITE (KLUN) YD%RCLUM
WRITE (KLUN) YD%RHPLA
WRITE (KLUN) YD%RKBOL
WRITE (KLUN) YD%RNAVO
WRITE (KLUN) YD%RDAY
WRITE (KLUN) YD%RDAYI
WRITE (KLUN) YD%RHOUR
WRITE (KLUN) YD%REA
WRITE (KLUN) YD%REPSM
WRITE (KLUN) YD%RSIYEA
WRITE (KLUN) YD%RSIDAY
WRITE (KLUN) YD%ROMEGA
WRITE (KLUN) YD%RA
WRITE (KLUN) YD%RG
WRITE (KLUN) YD%R1SA
WRITE (KLUN) YD%DEG2RAD
WRITE (KLUN) YD%RSIGMA
WRITE (KLUN) YD%RI0
WRITE (KLUN) YD%R
WRITE (KLUN) YD%RMD
WRITE (KLUN) YD%RMV
WRITE (KLUN) YD%RMO3
WRITE (KLUN) YD%RD
WRITE (KLUN) YD%RV
WRITE (KLUN) YD%RCPD
WRITE (KLUN) YD%RCPV
WRITE (KLUN) YD%RCVD
WRITE (KLUN) YD%RCVV
WRITE (KLUN) YD%RKAPPA
WRITE (KLUN) YD%RETV
WRITE (KLUN) YD%RMCO2
WRITE (KLUN) YD%RMCH4
WRITE (KLUN) YD%RMN2O
WRITE (KLUN) YD%RMCO
WRITE (KLUN) YD%RMHCHO
WRITE (KLUN) YD%RMNO2
WRITE (KLUN) YD%RMSO2
WRITE (KLUN) YD%RMSO4
WRITE (KLUN) YD%RMCFC11
WRITE (KLUN) YD%RMCFC12
WRITE (KLUN) YD%RMHCFC22
WRITE (KLUN) YD%RMCCL4
WRITE (KLUN) YD%RCW
WRITE (KLUN) YD%RCS
WRITE (KLUN) YD%RATM
WRITE (KLUN) YD%RTT
WRITE (KLUN) YD%RLVTT
WRITE (KLUN) YD%RLSTT
WRITE (KLUN) YD%RLVZER
WRITE (KLUN) YD%RLSZER
WRITE (KLUN) YD%RLMLT
WRITE (KLUN) YD%RDT
WRITE (KLUN) YD%RESTT
WRITE (KLUN) YD%RGAMW
WRITE (KLUN) YD%RBETW
WRITE (KLUN) YD%RALPW
WRITE (KLUN) YD%RGAMS
WRITE (KLUN) YD%RBETS
WRITE (KLUN) YD%RALPS
WRITE (KLUN) YD%RALPD
WRITE (KLUN) YD%RBETD
WRITE (KLUN) YD%RGAMD
END SUBROUTINE
SUBROUTINE LOAD_TCST (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCST), INTENT (OUT) :: YD

READ (KLUN) YD%RPI
READ (KLUN) YD%RCLUM
READ (KLUN) YD%RHPLA
READ (KLUN) YD%RKBOL
READ (KLUN) YD%RNAVO
READ (KLUN) YD%RDAY
READ (KLUN) YD%RDAYI
READ (KLUN) YD%RHOUR
READ (KLUN) YD%REA
READ (KLUN) YD%REPSM
READ (KLUN) YD%RSIYEA
READ (KLUN) YD%RSIDAY
READ (KLUN) YD%ROMEGA
READ (KLUN) YD%RA
READ (KLUN) YD%RG
READ (KLUN) YD%R1SA
READ (KLUN) YD%DEG2RAD
READ (KLUN) YD%RSIGMA
READ (KLUN) YD%RI0
READ (KLUN) YD%R
READ (KLUN) YD%RMD
READ (KLUN) YD%RMV
READ (KLUN) YD%RMO3
READ (KLUN) YD%RD
READ (KLUN) YD%RV
READ (KLUN) YD%RCPD
READ (KLUN) YD%RCPV
READ (KLUN) YD%RCVD
READ (KLUN) YD%RCVV
READ (KLUN) YD%RKAPPA
READ (KLUN) YD%RETV
READ (KLUN) YD%RMCO2
READ (KLUN) YD%RMCH4
READ (KLUN) YD%RMN2O
READ (KLUN) YD%RMCO
READ (KLUN) YD%RMHCHO
READ (KLUN) YD%RMNO2
READ (KLUN) YD%RMSO2
READ (KLUN) YD%RMSO4
READ (KLUN) YD%RMCFC11
READ (KLUN) YD%RMCFC12
READ (KLUN) YD%RMHCFC22
READ (KLUN) YD%RMCCL4
READ (KLUN) YD%RCW
READ (KLUN) YD%RCS
READ (KLUN) YD%RATM
READ (KLUN) YD%RTT
READ (KLUN) YD%RLVTT
READ (KLUN) YD%RLSTT
READ (KLUN) YD%RLVZER
READ (KLUN) YD%RLSZER
READ (KLUN) YD%RLMLT
READ (KLUN) YD%RDT
READ (KLUN) YD%RESTT
READ (KLUN) YD%RGAMW
READ (KLUN) YD%RBETW
READ (KLUN) YD%RALPW
READ (KLUN) YD%RGAMS
READ (KLUN) YD%RBETS
READ (KLUN) YD%RALPS
READ (KLUN) YD%RALPD
READ (KLUN) YD%RBETD
READ (KLUN) YD%RGAMD
END SUBROUTINE

SUBROUTINE COPY_TCST (YD, LDCREATED)

IMPLICIT NONE
TYPE (TCST), INTENT (IN) :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF































































END SUBROUTINE
INTEGER*8 FUNCTION SIZE_TCST (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TCST),     INTENT (IN) :: YD
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
LOGICAL,          INTENT (IN) :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE

KSIZE = 0
ISIZE = KIND (YD%RPI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RPI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RCLUM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RCLUM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RHPLA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RHPLA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RKBOL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RKBOL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RNAVO)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RNAVO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDAY)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RDAY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDAYI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RDAYI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RHOUR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RHOUR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%REA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%REA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%REPSM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%REPSM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RSIYEA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RSIYEA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RSIDAY)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RSIDAY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ROMEGA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ROMEGA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RG)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%R1SA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%R1SA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%DEG2RAD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%DEG2RAD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RSIGMA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RSIGMA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RI0)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RI0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%R)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%R'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RMD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RMD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RMV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RMV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RMO3)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RMO3'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RCPD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RCPD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RCPV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RCPV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RCVD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RCVD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RCVV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RCVV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RKAPPA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RKAPPA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RETV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RETV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RMCO2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RMCO2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RMCH4)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RMCH4'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RMN2O)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RMN2O'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RMCO)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RMCO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RMHCHO)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RMHCHO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RMNO2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RMNO2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RMSO2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RMSO2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RMSO4)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RMSO4'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RMCFC11)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RMCFC11'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RMCFC12)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RMCFC12'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RMHCFC22)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RMHCFC22'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RMCCL4)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RMCCL4'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RCW)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RCW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RCS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RCS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RATM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RATM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RTT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RTT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RLVTT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RLVTT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RLSTT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RLSTT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RLVZER)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RLVZER'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RLSZER)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RLSZER'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RLMLT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RLMLT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RDT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RESTT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RESTT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RGAMW)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RGAMW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RBETW)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RBETW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RALPW)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RALPW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RGAMS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RGAMS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RBETS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RBETS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RALPS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RALPS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RALPD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RALPD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RBETD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RBETD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RGAMD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RGAMD'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
