MODULE UTIL_TDVISI_MOD

USE YOMDVISI, ONLY : TDVISI

INTERFACE SAVE
MODULE PROCEDURE SAVE_TDVISI
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TDVISI
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TDVISI
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TDVISI
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TDVISI (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDVISI), INTENT (IN) :: YD

WRITE (KLUN) YD%HVISI
WRITE (KLUN) YD%COEF_CM1
WRITE (KLUN) YD%COEF_CM2
WRITE (KLUN) YD%COEF_CM3
WRITE (KLUN) YD%COEF_CM4
WRITE (KLUN) YD%COEF_RM1
WRITE (KLUN) YD%COEF_RM2
WRITE (KLUN) YD%COEF_IM1
WRITE (KLUN) YD%COEF_IM2
WRITE (KLUN) YD%COEF_SM1
WRITE (KLUN) YD%COEF_SM2
WRITE (KLUN) YD%COEF_GM1
WRITE (KLUN) YD%COEF_GM2
END SUBROUTINE
SUBROUTINE LOAD_TDVISI (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDVISI), INTENT (OUT) :: YD

READ (KLUN) YD%HVISI
READ (KLUN) YD%COEF_CM1
READ (KLUN) YD%COEF_CM2
READ (KLUN) YD%COEF_CM3
READ (KLUN) YD%COEF_CM4
READ (KLUN) YD%COEF_RM1
READ (KLUN) YD%COEF_RM2
READ (KLUN) YD%COEF_IM1
READ (KLUN) YD%COEF_IM2
READ (KLUN) YD%COEF_SM1
READ (KLUN) YD%COEF_SM2
READ (KLUN) YD%COEF_GM1
READ (KLUN) YD%COEF_GM2
END SUBROUTINE

SUBROUTINE COPY_TDVISI (YD, LDCREATED)

IMPLICIT NONE
TYPE (TDVISI), INTENT (IN) :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF













END SUBROUTINE
INTEGER*8 FUNCTION SIZE_TDVISI (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TDVISI),     INTENT (IN) :: YD
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
LOGICAL,          INTENT (IN) :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE

KSIZE = 0
ISIZE = KIND (YD%HVISI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%HVISI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%COEF_CM1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%COEF_CM1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%COEF_CM2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%COEF_CM2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%COEF_CM3)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%COEF_CM3'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%COEF_CM4)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%COEF_CM4'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%COEF_RM1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%COEF_RM1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%COEF_RM2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%COEF_RM2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%COEF_IM1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%COEF_IM1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%COEF_IM2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%COEF_IM2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%COEF_SM1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%COEF_SM1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%COEF_SM2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%COEF_SM2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%COEF_GM1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%COEF_GM1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%COEF_GM2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%COEF_GM2'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
