MODULE UTIL_TPHY2_MOD

USE YOMPHY2, ONLY : TPHY2

INTERFACE SAVE
MODULE PROCEDURE SAVE_TPHY2
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TPHY2
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TPHY2
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TPHY2
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TPHY2 (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPHY2), INTENT (IN) :: YD

WRITE (KLUN) YD%NTSHM
WRITE (KLUN) YD%NTSML
WRITE (KLUN) YD%TSPHY
WRITE (KLUN) YD%XMUCVPP
WRITE (KLUN) YD%XMULAF
WRITE (KLUN) YD%XDAMP
WRITE (KLUN) YD%HCLP
WRITE (KLUN) YD%HTCLS
WRITE (KLUN) YD%HVCLS
WRITE (KLUN) YD%HTSHM
WRITE (KLUN) YD%HTSML
WRITE (KLUN) YD%HWMOHIGH
WRITE (KLUN) YD%HWMOLOW
WRITE (KLUN) YD%GZ0RAF
WRITE (KLUN) YD%FACRAF
WRITE (KLUN) YD%FACRAFCV
WRITE (KLUN) YD%FACRAFDCAPE
WRITE (KLUN) YD%GCAPERAF
WRITE (KLUN) YD%HTKERAF
WRITE (KLUN) YD%LRAFTUR
WRITE (KLUN) YD%LMULAF
WRITE (KLUN) YD%LWMOCLOUD
WRITE (KLUN) YD%LRAFTKE
END SUBROUTINE
SUBROUTINE LOAD_TPHY2 (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPHY2), INTENT (OUT) :: YD

READ (KLUN) YD%NTSHM
READ (KLUN) YD%NTSML
READ (KLUN) YD%TSPHY
READ (KLUN) YD%XMUCVPP
READ (KLUN) YD%XMULAF
READ (KLUN) YD%XDAMP
READ (KLUN) YD%HCLP
READ (KLUN) YD%HTCLS
READ (KLUN) YD%HVCLS
READ (KLUN) YD%HTSHM
READ (KLUN) YD%HTSML
READ (KLUN) YD%HWMOHIGH
READ (KLUN) YD%HWMOLOW
READ (KLUN) YD%GZ0RAF
READ (KLUN) YD%FACRAF
READ (KLUN) YD%FACRAFCV
READ (KLUN) YD%FACRAFDCAPE
READ (KLUN) YD%GCAPERAF
READ (KLUN) YD%HTKERAF
READ (KLUN) YD%LRAFTUR
READ (KLUN) YD%LMULAF
READ (KLUN) YD%LWMOCLOUD
READ (KLUN) YD%LRAFTKE
END SUBROUTINE

SUBROUTINE COPY_TPHY2 (YD, LDCREATED)

IMPLICIT NONE
TYPE (TPHY2), INTENT (IN) :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF























END SUBROUTINE
INTEGER*8 FUNCTION SIZE_TPHY2 (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TPHY2),     INTENT (IN) :: YD
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
LOGICAL,          INTENT (IN) :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE

KSIZE = 0
ISIZE = KIND (YD%NTSHM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NTSHM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NTSML)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NTSML'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TSPHY)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TSPHY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XMUCVPP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XMUCVPP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XMULAF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XMULAF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XDAMP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XDAMP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%HCLP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%HCLP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%HTCLS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%HTCLS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%HVCLS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%HVCLS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%HTSHM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%HTSHM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%HTSML)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%HTSML'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%HWMOHIGH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%HWMOHIGH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%HWMOLOW)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%HWMOLOW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GZ0RAF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GZ0RAF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FACRAF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FACRAF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FACRAFCV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FACRAFCV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FACRAFDCAPE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FACRAFDCAPE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCAPERAF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCAPERAF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%HTKERAF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%HTKERAF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRAFTUR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LRAFTUR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LMULAF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LMULAF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LWMOCLOUD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LWMOCLOUD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRAFTKE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LRAFTKE'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
