MODULE UTIL_TVDOZ_MOD

USE YOMVDOZ, ONLY : TVDOZ

INTERFACE SAVE
MODULE PROCEDURE SAVE_TVDOZ
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TVDOZ
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TVDOZ
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TVDOZ
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TVDOZ (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVDOZ), INTENT (IN) :: YD

WRITE (KLUN) YD%VDHJS
WRITE (KLUN) YD%VDHJH
WRITE (KLUN) YD%VDHNS
WRITE (KLUN) YD%VDHNH
WRITE (KLUN) YD%VDPJS
WRITE (KLUN) YD%VDPJH
WRITE (KLUN) YD%VDPNS
WRITE (KLUN) YD%VDPNH
WRITE (KLUN) YD%VDEJS
WRITE (KLUN) YD%VDEJH
WRITE (KLUN) YD%VDENS
WRITE (KLUN) YD%VDENH
WRITE (KLUN) YD%VDAJS
WRITE (KLUN) YD%VDAJH
WRITE (KLUN) YD%VDANS
WRITE (KLUN) YD%VDANH
WRITE (KLUN) YD%VDNJS
WRITE (KLUN) YD%VDNJH
WRITE (KLUN) YD%VDNNS
WRITE (KLUN) YD%VDNNH
WRITE (KLUN) YD%VOZNJ
WRITE (KLUN) YD%VOZHS
WRITE (KLUN) YD%LRDIFOZ
WRITE (KLUN) YD%LRDEPOZ
END SUBROUTINE
SUBROUTINE LOAD_TVDOZ (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVDOZ), INTENT (OUT) :: YD

READ (KLUN) YD%VDHJS
READ (KLUN) YD%VDHJH
READ (KLUN) YD%VDHNS
READ (KLUN) YD%VDHNH
READ (KLUN) YD%VDPJS
READ (KLUN) YD%VDPJH
READ (KLUN) YD%VDPNS
READ (KLUN) YD%VDPNH
READ (KLUN) YD%VDEJS
READ (KLUN) YD%VDEJH
READ (KLUN) YD%VDENS
READ (KLUN) YD%VDENH
READ (KLUN) YD%VDAJS
READ (KLUN) YD%VDAJH
READ (KLUN) YD%VDANS
READ (KLUN) YD%VDANH
READ (KLUN) YD%VDNJS
READ (KLUN) YD%VDNJH
READ (KLUN) YD%VDNNS
READ (KLUN) YD%VDNNH
READ (KLUN) YD%VOZNJ
READ (KLUN) YD%VOZHS
READ (KLUN) YD%LRDIFOZ
READ (KLUN) YD%LRDEPOZ
END SUBROUTINE

SUBROUTINE COPY_TVDOZ (YD, LDCREATED)

IMPLICIT NONE
TYPE (TVDOZ), INTENT (IN) :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
























END SUBROUTINE
INTEGER*8 FUNCTION SIZE_TVDOZ (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TVDOZ),     INTENT (IN) :: YD
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
LOGICAL,          INTENT (IN) :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE

KSIZE = 0
ISIZE = KIND (YD%VDHJS) * SIZE (YD%VDHJS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VDHJS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VDHJH) * SIZE (YD%VDHJH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VDHJH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VDHNS) * SIZE (YD%VDHNS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VDHNS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VDHNH) * SIZE (YD%VDHNH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VDHNH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VDPJS) * SIZE (YD%VDPJS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VDPJS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VDPJH) * SIZE (YD%VDPJH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VDPJH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VDPNS) * SIZE (YD%VDPNS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VDPNS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VDPNH) * SIZE (YD%VDPNH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VDPNH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VDEJS) * SIZE (YD%VDEJS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VDEJS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VDEJH) * SIZE (YD%VDEJH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VDEJH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VDENS) * SIZE (YD%VDENS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VDENS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VDENH) * SIZE (YD%VDENH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VDENH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VDAJS) * SIZE (YD%VDAJS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VDAJS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VDAJH) * SIZE (YD%VDAJH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VDAJH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VDANS) * SIZE (YD%VDANS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VDANS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VDANH) * SIZE (YD%VDANH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VDANH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VDNJS) * SIZE (YD%VDNJS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VDNJS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VDNJH) * SIZE (YD%VDNJH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VDNJH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VDNNS) * SIZE (YD%VDNNS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VDNNS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VDNNH) * SIZE (YD%VDNNH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VDNNH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VOZNJ)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VOZNJ'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VOZHS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VOZHS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRDIFOZ)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LRDIFOZ'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRDEPOZ)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LRDEPOZ'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
