MODULE UTIL_TMSE_MOD

USE YOMMSE, ONLY : TMSE

INTERFACE SAVE
MODULE PROCEDURE SAVE_TMSE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TMSE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TMSE
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TMSE
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TMSE (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TMSE), INTENT (IN) :: YD

WRITE (KLUN) YD%LPGDFWR
WRITE (KLUN) YD%LHISFWR
WRITE (KLUN) YD%LFTZERO
WRITE (KLUN) YD%NSURFEXCTLMAX
WRITE (KLUN) YD%NSURFEXCTL
WRITE (KLUN) YD%CPREFIX_SFX1
WRITE (KLUN) YD%CPREFIX_SFX2
WRITE (KLUN) YD%XZSEPS
END SUBROUTINE
SUBROUTINE LOAD_TMSE (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TMSE), INTENT (OUT) :: YD

READ (KLUN) YD%LPGDFWR
READ (KLUN) YD%LHISFWR
READ (KLUN) YD%LFTZERO
READ (KLUN) YD%NSURFEXCTLMAX
READ (KLUN) YD%NSURFEXCTL
READ (KLUN) YD%CPREFIX_SFX1
READ (KLUN) YD%CPREFIX_SFX2
READ (KLUN) YD%XZSEPS
END SUBROUTINE

SUBROUTINE COPY_TMSE (YD, LDCREATED)

IMPLICIT NONE
TYPE (TMSE), INTENT (IN) :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF








END SUBROUTINE
INTEGER*8 FUNCTION SIZE_TMSE (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TMSE),     INTENT (IN) :: YD
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
LOGICAL,          INTENT (IN) :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE

KSIZE = 0
ISIZE = KIND (YD%LPGDFWR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LPGDFWR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LHISFWR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LHISFWR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LFTZERO)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LFTZERO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSURFEXCTLMAX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NSURFEXCTLMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSURFEXCTL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NSURFEXCTL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CPREFIX_SFX1) * LEN (YD%CPREFIX_SFX1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%CPREFIX_SFX1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CPREFIX_SFX2) * LEN (YD%CPREFIX_SFX2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%CPREFIX_SFX2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XZSEPS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XZSEPS'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
