MODULE UTIL_TPHY0_MOD

USE YOMPHY0, ONLY : TPHY0

INTERFACE SAVE
MODULE PROCEDURE SAVE_TPHY0
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TPHY0
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TPHY0
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TPHY0
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TPHY0 (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPHY0), INTENT (IN) :: YD
LOGICAL :: LRHUC, LRN1D, LRQSMOD, LRRC1D, LRSRC1D, LRSURF
WRITE (KLUN) YD%TYM
WRITE (KLUN) YD%NPCLO1
WRITE (KLUN) YD%NPCLO2
WRITE (KLUN) YD%A0ML_AU
WRITE (KLUN) YD%A0ML_AT
WRITE (KLUN) YD%A0ML_BU
WRITE (KLUN) YD%A0ML_BT
WRITE (KLUN) YD%AERCS1
WRITE (KLUN) YD%AERCS3
WRITE (KLUN) YD%AERCS5
WRITE (KLUN) YD%ADJTAU
WRITE (KLUN) YD%ALMAV
WRITE (KLUN) YD%BEDIFV
WRITE (KLUN) YD%ECMNP
WRITE (KLUN) YD%EDB
WRITE (KLUN) YD%EDC
WRITE (KLUN) YD%EDD
WRITE (KLUN) YD%EVAP
WRITE (KLUN) YD%FONT
WRITE (KLUN) YD%GALP
WRITE (KLUN) YD%GCISMIN
WRITE (KLUN) YD%GEVAVF
WRITE (KLUN) YD%GCCSV
WRITE (KLUN) YD%GCVADS
WRITE (KLUN) YD%GCVBETA
WRITE (KLUN) YD%GCVIMPT
WRITE (KLUN) YD%GCVOMGE
WRITE (KLUN) YD%GCVOMGQ
WRITE (KLUN) YD%GCVOMGS
WRITE (KLUN) YD%GCVTURB
WRITE (KLUN) YD%GCVOMDPS
WRITE (KLUN) YD%GCVOMGSX
WRITE (KLUN) YD%GCVRHMIN
WRITE (KLUN) YD%GCVRHMAX
WRITE (KLUN) YD%GCVOMCA
WRITE (KLUN) YD%GCVOMCC
WRITE (KLUN) YD%GDDEVA
WRITE (KLUN) YD%GDDSDE
WRITE (KLUN) YD%GDDFREVS
WRITE (KLUN) YD%GDDINHOM
WRITE (KLUN) YD%GRCVPP
WRITE (KLUN) YD%GWDAMP
WRITE (KLUN) YD%GWDBC
WRITE (KLUN) YD%GWDCCO
WRITE (KLUN) YD%GWDCD
WRITE (KLUN) YD%GWDLT
WRITE (KLUN) YD%GWDSE
WRITE (KLUN) YD%GWDPROF
WRITE (KLUN) YD%GWDVALI
WRITE (KLUN) YD%HOBST
WRITE (KLUN) YD%HUCOE
WRITE (KLUN) YD%HUTIL
WRITE (KLUN) YD%HUTIL1
WRITE (KLUN) YD%HUTIL2
WRITE (KLUN) YD%QSMIN
WRITE (KLUN) YD%QSMODC
WRITE (KLUN) YD%QSNEBC
WRITE (KLUN) YD%QSNEBS
WRITE (KLUN) YD%QSSUSC
WRITE (KLUN) YD%QSSUSS
WRITE (KLUN) YD%QSSUSV
WRITE (KLUN) YD%QSUSXC
WRITE (KLUN) YD%QSUSXS
WRITE (KLUN) YD%RPHI0
WRITE (KLUN) YD%RPHIR
WRITE (KLUN) YD%QXRAL
WRITE (KLUN) YD%QXRAL_ADJ
WRITE (KLUN) YD%QXRDEL
WRITE (KLUN) YD%QXRHX
WRITE (KLUN) YD%QXRR
WRITE (KLUN) YD%QXRTGH
WRITE (KLUN) YD%QXRCDIL
WRITE (KLUN) YD%RCIN
WRITE (KLUN) YD%RCVEVAP
WRITE (KLUN) YD%RDECRD
WRITE (KLUN) YD%RDECRD1
WRITE (KLUN) YD%RDECRD2
WRITE (KLUN) YD%RDECRD3
WRITE (KLUN) YD%RDECRD4
WRITE (KLUN) YD%RDECRDRED
WRITE (KLUN) YD%RDTFAC
WRITE (KLUN) YD%REVAPN
WRITE (KLUN) YD%REVGSL
WRITE (KLUN) YD%RGELSFON
WRITE (KLUN) YD%RFLCHCE
WRITE (KLUN) YD%RTCAPE
WRITE (KLUN) YD%SCO
WRITE (KLUN) YD%SENSL
WRITE (KLUN) YD%SNNBCO
WRITE (KLUN) YD%SPNBCO
WRITE (KLUN) YD%SXNBCO
WRITE (KLUN) YD%TCA
WRITE (KLUN) YD%TCT
WRITE (KLUN) YD%TCW
WRITE (KLUN) YD%TENTR
WRITE (KLUN) YD%TENTRX
WRITE (KLUN) YD%TUDGP
WRITE (KLUN) YD%TDDGP
WRITE (KLUN) YD%TURB
WRITE (KLUN) YD%TVF
WRITE (KLUN) YD%UHDIFV
WRITE (KLUN) YD%USDMLT
WRITE (KLUN) YD%USUPRC
WRITE (KLUN) YD%USURIC
WRITE (KLUN) YD%VCHRNK
WRITE (KLUN) YD%VKARMN
WRITE (KLUN) YD%VZ0CM
WRITE (KLUN) YD%VZIUSTAR0
WRITE (KLUN) YD%XNBMAX
WRITE (KLUN) YD%AECLS3
WRITE (KLUN) YD%AECLS4
WRITE (KLUN) YD%ALD
WRITE (KLUN) YD%AKN
WRITE (KLUN) YD%ALPHAT
WRITE (KLUN) YD%ALPHAE
WRITE (KLUN) YD%EPS
WRITE (KLUN) YD%ETACUT
WRITE (KLUN) YD%ADISI
WRITE (KLUN) YD%ADISE
WRITE (KLUN) YD%ECTMIN
WRITE (KLUN) YD%ECTMAX
WRITE (KLUN) YD%AHCLPV
WRITE (KLUN) YD%RICRLM
WRITE (KLUN) YD%RMULACVG
WRITE (KLUN) YD%XBLM
WRITE (KLUN) YD%XMINLM
WRITE (KLUN) YD%XMAXLM
WRITE (KLUN) YD%XWSALM
WRITE (KLUN) YD%XWSBLM
WRITE (KLUN) YD%GCVALFA
WRITE (KLUN) YD%GCVPSI
WRITE (KLUN) YD%GCVPSIE
WRITE (KLUN) YD%USURICE
WRITE (KLUN) YD%USURICL
WRITE (KLUN) YD%QSSC
WRITE (KLUN) YD%USURID
WRITE (KLUN) YD%GCVNU
WRITE (KLUN) YD%USURIDE
WRITE (KLUN) YD%GCVMLT
WRITE (KLUN) YD%UTILGUST
WRITE (KLUN) YD%RRGAMMA
WRITE (KLUN) YD%RRSCALE
WRITE (KLUN) YD%GPBLHK0
WRITE (KLUN) YD%GPBLHRA
WRITE (KLUN) YD%WMXOV
WRITE (KLUN) YD%ACBRPHIM
WRITE (KLUN) YD%ALMAVE
WRITE (KLUN) YD%ALMAVX
WRITE (KLUN) YD%ARSCH
WRITE (KLUN) YD%ARSCQ
WRITE (KLUN) YD%ARSC1
WRITE (KLUN) YD%ARSB2
WRITE (KLUN) YD%RICRET
WRITE (KLUN) YD%STTBMIN
WRITE (KLUN) YD%UCWSTAR
WRITE (KLUN) YD%UDECT
WRITE (KLUN) YD%UPRETMIN
WRITE (KLUN) YD%UPRETMAX
WRITE (KLUN) YD%USHEARM
WRITE (KLUN) YD%RAUTEFR
WRITE (KLUN) YD%RRAUTCS
WRITE (KLUN) YD%RAUTEFS
WRITE (KLUN) YD%RAUTSBET
WRITE (KLUN) YD%RAUTEFG
WRITE (KLUN) YD%REVASX
WRITE (KLUN) YD%RNINTR
WRITE (KLUN) YD%RNINTS
WRITE (KLUN) YD%RQLCR
WRITE (KLUN) YD%RSPCRR
WRITE (KLUN) YD%RQICRMAX
WRITE (KLUN) YD%RQICRMIN
WRITE (KLUN) YD%RQLCV
WRITE (KLUN) YD%RQICVMAX
WRITE (KLUN) YD%RQICVMIN
WRITE (KLUN) YD%RQICRT1
WRITE (KLUN) YD%RQICRT2
WRITE (KLUN) YD%RQICRSN
WRITE (KLUN) YD%RQCRNS
WRITE (KLUN) YD%RACCEF
WRITE (KLUN) YD%RAGGEF
WRITE (KLUN) YD%RRIMEF
WRITE (KLUN) YD%RHCRIT1
WRITE (KLUN) YD%RHCRIT2
WRITE (KLUN) YD%RETAMIN
WRITE (KLUN) YD%RFACNSM
WRITE (KLUN) YD%TFVL
WRITE (KLUN) YD%TFVI
WRITE (KLUN) YD%TFVR
WRITE (KLUN) YD%TFVS
WRITE (KLUN) YD%GRHCMOD
WRITE (KLUN) YD%RHCEXPDX
WRITE (KLUN) YD%NUPTKE
WRITE (KLUN) YD%TKEMULT
WRITE (KLUN) YD%C_EPSILON
WRITE (KLUN) YD%C3TKEFREE
WRITE (KLUN) YD%ETKE_CTHETA
WRITE (KLUN) YD%ETKE_RIFC_MAF
WRITE (KLUN) YD%ETKE_RIFC
WRITE (KLUN) YD%ETKE_R
WRITE (KLUN) YD%ETKE_OLAM
WRITE (KLUN) YD%ETKE_LAM0
WRITE (KLUN) YD%ETKE_LAM1
WRITE (KLUN) YD%ETKE_LAM2
WRITE (KLUN) YD%ETKE_LAM3
WRITE (KLUN) YD%ETKE_LAM4
WRITE (KLUN) YD%ETKE_KA1
WRITE (KLUN) YD%ETKE_KA2
WRITE (KLUN) YD%ETKE_KA3
WRITE (KLUN) YD%ENT_LAMBDA
WRITE (KLUN) YD%ETKE_CG01
WRITE (KLUN) YD%ETKE_CG02
WRITE (KLUN) YD%ETKE_CG03
WRITE (KLUN) YD%ETKE_BETA_EPS
WRITE (KLUN) YD%ETKE_GAMMA_EPS
WRITE (KLUN) YD%ETKE_GAMD
WRITE (KLUN) YD%ETKE_TALPH
WRITE (KLUN) YD%ETKE_ALPH0
WRITE (KLUN) YD%ETKE_ENTRX
WRITE (KLUN) YD%ETKE_ENTRN
WRITE (KLUN) YD%ETKE_KLM
WRITE (KLUN) YD%ETKE_TAULM
WRITE (KLUN) YD%ETKE_C0SHEAR
WRITE (KLUN) YD%ETKE_R1SIM
WRITE (KLUN) YD%ETKE_R2SIM
WRITE (KLUN) YD%ETKE_GB08A
WRITE (KLUN) YD%ETKE_GB08B
WRITE (KLUN) YD%ETKE_MIN
WRITE (KLUN) YD%ETKE_CRIT
WRITE (KLUN) YD%ETKE_DELTA
WRITE (KLUN) YD%EFB_AZ0
WRITE (KLUN) YD%EFB_UR
WRITE (KLUN) YD%REFB_1
WRITE (KLUN) YD%REFB_2
WRITE (KLUN) YD%REFB_3
WRITE (KLUN) YD%TUDBU
WRITE (KLUN) YD%TDDBU
WRITE (KLUN) YD%TUDFR
WRITE (KLUN) YD%TDDFR
WRITE (KLUN) YD%GCVALMX
WRITE (KLUN) YD%GCVTAUDE
WRITE (KLUN) YD%GCVACHI
WRITE (KLUN) YD%GCVBEE
WRITE (KLUN) YD%GCVEEX
WRITE (KLUN) YD%ECMNPI
WRITE (KLUN) YD%GRRMINA
WRITE (KLUN) YD%GDDBETA
WRITE (KLUN) YD%GDDDP
WRITE (KLUN) YD%GDDFXM
WRITE (KLUN) YD%GDDWPF
WRITE (KLUN) YD%GDDEVF
WRITE (KLUN) YD%TENTRD
WRITE (KLUN) YD%GDDALBU
WRITE (KLUN) YD%GDDFRAC
WRITE (KLUN) YD%GDDENDYMX
WRITE (KLUN) YD%GDDFP
WRITE (KLUN) YD%GDDTAUSIG
WRITE (KLUN) YD%GPEIPHI
WRITE (KLUN) YD%GPETAU
WRITE (KLUN) YD%GPEFDC
WRITE (KLUN) YD%GENVSRH
WRITE (KLUN) YD%GCVKSKV
WRITE (KLUN) YD%GCVALBU
WRITE (KLUN) YD%GCVENDY1
WRITE (KLUN) YD%GCVENDY2
WRITE (KLUN) YD%GCVENDYMX
WRITE (KLUN) YD%GCVIDPBAS
WRITE (KLUN) YD%GCVTAUSIG
WRITE (KLUN) YD%GTRGDPMIX
WRITE (KLUN) YD%GTRGDPHIMN
WRITE (KLUN) YD%GTRGPUSLMN
WRITE (KLUN) YD%GTRGKCK9
WRITE (KLUN) YD%GTRGAIN
WRITE (KLUN) YD%GTRTHRS
WRITE (KLUN) YD%GTRTHCK
WRITE (KLUN) YD%GTRBRC
WRITE (KLUN) YD%GTRKGAIN
WRITE (KLUN) YD%GTRKTHRS
WRITE (KLUN) YD%GTRKTHCK
WRITE (KLUN) YD%GCVCATAU
WRITE (KLUN) YD%GCATHRCAP
WRITE (KLUN) YD%GCATHRMOC
WRITE (KLUN) YD%GCATHRCND
WRITE (KLUN) YD%GCAOMCND
WRITE (KLUN) YD%NWEIGHT
WRITE (KLUN) YD%NCATAU
WRITE (KLUN) YD%NCAPEMAX
WRITE (KLUN) YD%NCVGMAX
WRITE (KLUN) YD%RNEGAT
WRITE (KLUN) YD%RNLCURV
WRITE (KLUN) YD%EDK
WRITE (KLUN) YD%XKLM
WRITE (KLUN) YD%AGRE1
WRITE (KLUN) YD%AGRERICR
WRITE (KLUN) YD%AJBUMIN
WRITE (KLUN) YD%RCOFLM
WRITE (KLUN) YD%TENTRVL
WRITE (KLUN) YD%TRENTRV
WRITE (KLUN) YD%GCVGAMMA
WRITE (KLUN) YD%LKESC
WRITE (KLUN) YD%AGRE2
WRITE (KLUN) YD%AGREF
WRITE (KLUN) YD%ALFX
WRITE (KLUN) YD%ALFX_LR
WRITE (KLUN) YD%ALFX_HR
WRITE (KLUN) YD%TCTC
WRITE (KLUN) YD%TVFC
WRITE (KLUN) YD%GAMAP1
WRITE (KLUN) YD%RKDN
WRITE (KLUN) YD%VVN
WRITE (KLUN) YD%VVX
WRITE (KLUN) YD%FENTRT
WRITE (KLUN) YD%FQLIC
WRITE (KLUN) YD%FNEBC
WRITE (KLUN) YD%FEVAPC
WRITE (KLUN) YD%RDPHIC
WRITE (KLUN) YD%RWBF1
WRITE (KLUN) YD%RWBF2
WRITE (KLUN) YD%SCLESPR
WRITE (KLUN) YD%SCLESPS
WRITE (KLUN) YD%HUCRED
WRITE (KLUN) YD%HUCREDRA
WRITE (KLUN) YD%FSPRAIN
WRITE (KLUN) YD%EFFCOLL
WRITE (KLUN) YD%RSMDNEBX
WRITE (KLUN) YD%RSMDTX
WRITE (KLUN) YD%NSMTPA
WRITE (KLUN) YD%NSMTPB
WRITE (KLUN) YD%RKFBTAU
WRITE (KLUN) YD%RKFBNBX
WRITE (KLUN) YD%GCVHMIN
WRITE (KLUN) YD%GCVRESN
WRITE (KLUN) YD%GCVRESX
WRITE (KLUN) YD%GMIRH
WRITE (KLUN) YD%RLMLH1
WRITE (KLUN) YD%RPRTH
WRITE (KLUN) YD%RSMOOTHMELT
WRITE (KLUN) YD%LADVLIM
WRITE (KLUN) YD%LGDDD
WRITE (KLUN) YD%LCVNHD
WRITE (KLUN) YD%LCVRESDYN
WRITE (KLUN) YD%LCVMICC
WRITE (KLUN) YD%GMUKEDD
WRITE (KLUN) YD%GNHDTAT
WRITE (KLUN) YD%GNHDSMOS
WRITE (KLUN) YD%GNHDSMOT
WRITE (KLUN) YD%GNHDEV
WRITE (KLUN) YD%LGVVEX
WRITE (KLUN) YD%LCVUVM
WRITE (KLUN) YD%NCVENTR
WRITE (KLUN) YD%NCVSIG
WRITE (KLUN) YD%NCVCLOS
WRITE (KLUN) YD%NCVQLI
WRITE (KLUN) YD%GCVENTRN
WRITE (KLUN) YD%GCVENTRX
WRITE (KLUN) YD%ADOE
WRITE (KLUN) YD%RFRAC_ENTR_N
WRITE (KLUN) YD%RFRAC_ENTR_X
WRITE (KLUN) YD%GCVENTR_MIN
WRITE (KLUN) YD%THPCMT
WRITE (KLUN) YD%AJ1PEPS
WRITE (KLUN) YD%AJ1MEPS
WRITE (KLUN) YD%NAJITER
WRITE (KLUN) YD%GAEPS
WRITE (KLUN) YD%GCVEZ
WRITE (KLUN) YD%GCVTRMIN
WRITE (KLUN) YD%LCVFEVV
WRITE (KLUN) YD%GCVFEVV
WRITE (KLUN) YD%LCVCONTAU
WRITE (KLUN) YD%GCVTEXC
WRITE (KLUN) YD%GCVWEXC
WRITE (KLUN) YD%LCVNAUV
WRITE (KLUN) YD%GCVFRR
WRITE (KLUN) YD%GCVPNH
WRITE (KLUN) YD%GCVORGED
WRITE (KLUN) YD%LCVIMPT
WRITE (KLUN) YD%GCVTAUREM
WRITE (KLUN) YD%GCLOEA
WRITE (KLUN) YD%GCLOEB
WRITE (KLUN) YD%GFRAE
WRITE (KLUN) YD%GCVADET
WRITE (KLUN) YD%GCVCINC
WRITE (KLUN) YD%GSDMIN
WRITE (KLUN) YD%GSDMAX
WRITE (KLUN) YD%GALMIN
WRITE (KLUN) YD%GALMAX
WRITE (KLUN) YD%GSDAMIN
WRITE (KLUN) YD%GSDAMAX
WRITE (KLUN) YD%GEXPKD
WRITE (KLUN) YD%LCVEOD
WRITE (KLUN) YD%GREMIN
WRITE (KLUN) YD%GREMAX
WRITE (KLUN) YD%GCHI0
WRITE (KLUN) YD%GFSURF
WRITE (KLUN) YD%GSHELL
WRITE (KLUN) YD%GFRIC
WRITE (KLUN) YD%GUDDD
WRITE (KLUN) YD%GSIGA
WRITE (KLUN) YD%GNHDSMOW
WRITE (KLUN) YD%GDEPTH
WRITE (KLUN) YD%GALTAU
WRITE (KLUN) YD%GKEDDRE
WRITE (KLUN) YD%GNHACC
WRITE (KLUN) YD%GTDCL
WRITE (KLUN) YD%GSINHD
WRITE (KLUN) YD%GSINHR
WRITE (KLUN) YD%GCVFNER
WRITE (KLUN) YD%GCVFNEO
WRITE (KLUN) YD%GCVFNEP1
WRITE (KLUN) YD%GCVFNEP2
WRITE (KLUN) YD%GRBCC
WRITE (KLUN) YD%GTOPDEPTH
WRITE (KLUN) YD%GCVTSMO
WRITE (KLUN) YD%RKDX
WRITE (KLUN) YD%LCAPCIN
WRITE (KLUN) YD%LCORSEDIM
WRITE (KLUN) YD%GNHDTAU
WRITE (KLUN) YD%GRSO
WRITE (KLUN) YD%GRTH
WRITE (KLUN) YD%GRFCS
WRITE (KLUN) YD%GCVRE
WRITE (KLUN) YD%LSBUO
WRITE (KLUN) YD%GREDDI
WRITE (KLUN) YD%GREDDL
WRITE (KLUN) YD%GREDDR
WRITE (KLUN) YD%GREDDS
WRITE (KLUN) YD%LCVTADV
WRITE (KLUN) YD%LCVDS
WRITE (KLUN) YD%GCVUV
WRITE (KLUN) YD%GCVGAW
WRITE (KLUN) YD%GCVGAX
WRITE (KLUN) YD%GCHECKMV_TMIN
WRITE (KLUN) YD%GCHECKMV_TMAX
WRITE (KLUN) YD%GCHECKMV_QVMIN
WRITE (KLUN) YD%GCHECKMV_QVMAX
WRITE (KLUN) YD%LGPRONI1
WRITE (KLUN) YD%NPRONI
WRITE (KLUN) YD%GPRONI
WRITE (KLUN) YD%RNEBCX
WRITE (KLUN) YD%GLIGHTT1
WRITE (KLUN) YD%GLIGHTT2
WRITE (KLUN) YD%GLIGHTT3
WRITE (KLUN) YD%REFLRHC
WRITE (KLUN) YD%TEQH
WRITE (KLUN) YD%REFLKUO
WRITE (KLUN) YD%REFLCAPE
WRITE (KLUN) YD%TEQK
WRITE (KLUN) YD%TEQC
WRITE (KLUN) YD%REPS
LRHUC = ALLOCATED (YD%RHUC)
WRITE (KLUN) LRHUC
IF (LRHUC) THEN
  WRITE (KLUN) LBOUND (YD%RHUC)
  WRITE (KLUN) UBOUND (YD%RHUC)
  WRITE (KLUN) YD%RHUC
ENDIF
LRQSMOD = ALLOCATED (YD%RQSMOD)
WRITE (KLUN) LRQSMOD
IF (LRQSMOD) THEN
  WRITE (KLUN) LBOUND (YD%RQSMOD)
  WRITE (KLUN) UBOUND (YD%RQSMOD)
  WRITE (KLUN) YD%RQSMOD
ENDIF
LRSURF = ALLOCATED (YD%RSURF)
WRITE (KLUN) LRSURF
IF (LRSURF) THEN
  WRITE (KLUN) LBOUND (YD%RSURF)
  WRITE (KLUN) UBOUND (YD%RSURF)
  WRITE (KLUN) YD%RSURF
ENDIF
LRN1D = ALLOCATED (YD%RN1D)
WRITE (KLUN) LRN1D
IF (LRN1D) THEN
  WRITE (KLUN) LBOUND (YD%RN1D)
  WRITE (KLUN) UBOUND (YD%RN1D)
  WRITE (KLUN) YD%RN1D
ENDIF
LRRC1D = ALLOCATED (YD%RRC1D)
WRITE (KLUN) LRRC1D
IF (LRRC1D) THEN
  WRITE (KLUN) LBOUND (YD%RRC1D)
  WRITE (KLUN) UBOUND (YD%RRC1D)
  WRITE (KLUN) YD%RRC1D
ENDIF
LRSRC1D = ALLOCATED (YD%RSRC1D)
WRITE (KLUN) LRSRC1D
IF (LRSRC1D) THEN
  WRITE (KLUN) LBOUND (YD%RSRC1D)
  WRITE (KLUN) UBOUND (YD%RSRC1D)
  WRITE (KLUN) YD%RSRC1D
ENDIF
WRITE (KLUN) YD%RCOEFRAIN
WRITE (KLUN) YD%RCOEFSNOW
END SUBROUTINE
SUBROUTINE LOAD_TPHY0 (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPHY0), INTENT (OUT) :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LRHUC, LRN1D, LRQSMOD, LRRC1D, LRSRC1D, LRSURF
READ (KLUN) YD%TYM
READ (KLUN) YD%NPCLO1
READ (KLUN) YD%NPCLO2
READ (KLUN) YD%A0ML_AU
READ (KLUN) YD%A0ML_AT
READ (KLUN) YD%A0ML_BU
READ (KLUN) YD%A0ML_BT
READ (KLUN) YD%AERCS1
READ (KLUN) YD%AERCS3
READ (KLUN) YD%AERCS5
READ (KLUN) YD%ADJTAU
READ (KLUN) YD%ALMAV
READ (KLUN) YD%BEDIFV
READ (KLUN) YD%ECMNP
READ (KLUN) YD%EDB
READ (KLUN) YD%EDC
READ (KLUN) YD%EDD
READ (KLUN) YD%EVAP
READ (KLUN) YD%FONT
READ (KLUN) YD%GALP
READ (KLUN) YD%GCISMIN
READ (KLUN) YD%GEVAVF
READ (KLUN) YD%GCCSV
READ (KLUN) YD%GCVADS
READ (KLUN) YD%GCVBETA
READ (KLUN) YD%GCVIMPT
READ (KLUN) YD%GCVOMGE
READ (KLUN) YD%GCVOMGQ
READ (KLUN) YD%GCVOMGS
READ (KLUN) YD%GCVTURB
READ (KLUN) YD%GCVOMDPS
READ (KLUN) YD%GCVOMGSX
READ (KLUN) YD%GCVRHMIN
READ (KLUN) YD%GCVRHMAX
READ (KLUN) YD%GCVOMCA
READ (KLUN) YD%GCVOMCC
READ (KLUN) YD%GDDEVA
READ (KLUN) YD%GDDSDE
READ (KLUN) YD%GDDFREVS
READ (KLUN) YD%GDDINHOM
READ (KLUN) YD%GRCVPP
READ (KLUN) YD%GWDAMP
READ (KLUN) YD%GWDBC
READ (KLUN) YD%GWDCCO
READ (KLUN) YD%GWDCD
READ (KLUN) YD%GWDLT
READ (KLUN) YD%GWDSE
READ (KLUN) YD%GWDPROF
READ (KLUN) YD%GWDVALI
READ (KLUN) YD%HOBST
READ (KLUN) YD%HUCOE
READ (KLUN) YD%HUTIL
READ (KLUN) YD%HUTIL1
READ (KLUN) YD%HUTIL2
READ (KLUN) YD%QSMIN
READ (KLUN) YD%QSMODC
READ (KLUN) YD%QSNEBC
READ (KLUN) YD%QSNEBS
READ (KLUN) YD%QSSUSC
READ (KLUN) YD%QSSUSS
READ (KLUN) YD%QSSUSV
READ (KLUN) YD%QSUSXC
READ (KLUN) YD%QSUSXS
READ (KLUN) YD%RPHI0
READ (KLUN) YD%RPHIR
READ (KLUN) YD%QXRAL
READ (KLUN) YD%QXRAL_ADJ
READ (KLUN) YD%QXRDEL
READ (KLUN) YD%QXRHX
READ (KLUN) YD%QXRR
READ (KLUN) YD%QXRTGH
READ (KLUN) YD%QXRCDIL
READ (KLUN) YD%RCIN
READ (KLUN) YD%RCVEVAP
READ (KLUN) YD%RDECRD
READ (KLUN) YD%RDECRD1
READ (KLUN) YD%RDECRD2
READ (KLUN) YD%RDECRD3
READ (KLUN) YD%RDECRD4
READ (KLUN) YD%RDECRDRED
READ (KLUN) YD%RDTFAC
READ (KLUN) YD%REVAPN
READ (KLUN) YD%REVGSL
READ (KLUN) YD%RGELSFON
READ (KLUN) YD%RFLCHCE
READ (KLUN) YD%RTCAPE
READ (KLUN) YD%SCO
READ (KLUN) YD%SENSL
READ (KLUN) YD%SNNBCO
READ (KLUN) YD%SPNBCO
READ (KLUN) YD%SXNBCO
READ (KLUN) YD%TCA
READ (KLUN) YD%TCT
READ (KLUN) YD%TCW
READ (KLUN) YD%TENTR
READ (KLUN) YD%TENTRX
READ (KLUN) YD%TUDGP
READ (KLUN) YD%TDDGP
READ (KLUN) YD%TURB
READ (KLUN) YD%TVF
READ (KLUN) YD%UHDIFV
READ (KLUN) YD%USDMLT
READ (KLUN) YD%USUPRC
READ (KLUN) YD%USURIC
READ (KLUN) YD%VCHRNK
READ (KLUN) YD%VKARMN
READ (KLUN) YD%VZ0CM
READ (KLUN) YD%VZIUSTAR0
READ (KLUN) YD%XNBMAX
READ (KLUN) YD%AECLS3
READ (KLUN) YD%AECLS4
READ (KLUN) YD%ALD
READ (KLUN) YD%AKN
READ (KLUN) YD%ALPHAT
READ (KLUN) YD%ALPHAE
READ (KLUN) YD%EPS
READ (KLUN) YD%ETACUT
READ (KLUN) YD%ADISI
READ (KLUN) YD%ADISE
READ (KLUN) YD%ECTMIN
READ (KLUN) YD%ECTMAX
READ (KLUN) YD%AHCLPV
READ (KLUN) YD%RICRLM
READ (KLUN) YD%RMULACVG
READ (KLUN) YD%XBLM
READ (KLUN) YD%XMINLM
READ (KLUN) YD%XMAXLM
READ (KLUN) YD%XWSALM
READ (KLUN) YD%XWSBLM
READ (KLUN) YD%GCVALFA
READ (KLUN) YD%GCVPSI
READ (KLUN) YD%GCVPSIE
READ (KLUN) YD%USURICE
READ (KLUN) YD%USURICL
READ (KLUN) YD%QSSC
READ (KLUN) YD%USURID
READ (KLUN) YD%GCVNU
READ (KLUN) YD%USURIDE
READ (KLUN) YD%GCVMLT
READ (KLUN) YD%UTILGUST
READ (KLUN) YD%RRGAMMA
READ (KLUN) YD%RRSCALE
READ (KLUN) YD%GPBLHK0
READ (KLUN) YD%GPBLHRA
READ (KLUN) YD%WMXOV
READ (KLUN) YD%ACBRPHIM
READ (KLUN) YD%ALMAVE
READ (KLUN) YD%ALMAVX
READ (KLUN) YD%ARSCH
READ (KLUN) YD%ARSCQ
READ (KLUN) YD%ARSC1
READ (KLUN) YD%ARSB2
READ (KLUN) YD%RICRET
READ (KLUN) YD%STTBMIN
READ (KLUN) YD%UCWSTAR
READ (KLUN) YD%UDECT
READ (KLUN) YD%UPRETMIN
READ (KLUN) YD%UPRETMAX
READ (KLUN) YD%USHEARM
READ (KLUN) YD%RAUTEFR
READ (KLUN) YD%RRAUTCS
READ (KLUN) YD%RAUTEFS
READ (KLUN) YD%RAUTSBET
READ (KLUN) YD%RAUTEFG
READ (KLUN) YD%REVASX
READ (KLUN) YD%RNINTR
READ (KLUN) YD%RNINTS
READ (KLUN) YD%RQLCR
READ (KLUN) YD%RSPCRR
READ (KLUN) YD%RQICRMAX
READ (KLUN) YD%RQICRMIN
READ (KLUN) YD%RQLCV
READ (KLUN) YD%RQICVMAX
READ (KLUN) YD%RQICVMIN
READ (KLUN) YD%RQICRT1
READ (KLUN) YD%RQICRT2
READ (KLUN) YD%RQICRSN
READ (KLUN) YD%RQCRNS
READ (KLUN) YD%RACCEF
READ (KLUN) YD%RAGGEF
READ (KLUN) YD%RRIMEF
READ (KLUN) YD%RHCRIT1
READ (KLUN) YD%RHCRIT2
READ (KLUN) YD%RETAMIN
READ (KLUN) YD%RFACNSM
READ (KLUN) YD%TFVL
READ (KLUN) YD%TFVI
READ (KLUN) YD%TFVR
READ (KLUN) YD%TFVS
READ (KLUN) YD%GRHCMOD
READ (KLUN) YD%RHCEXPDX
READ (KLUN) YD%NUPTKE
READ (KLUN) YD%TKEMULT
READ (KLUN) YD%C_EPSILON
READ (KLUN) YD%C3TKEFREE
READ (KLUN) YD%ETKE_CTHETA
READ (KLUN) YD%ETKE_RIFC_MAF
READ (KLUN) YD%ETKE_RIFC
READ (KLUN) YD%ETKE_R
READ (KLUN) YD%ETKE_OLAM
READ (KLUN) YD%ETKE_LAM0
READ (KLUN) YD%ETKE_LAM1
READ (KLUN) YD%ETKE_LAM2
READ (KLUN) YD%ETKE_LAM3
READ (KLUN) YD%ETKE_LAM4
READ (KLUN) YD%ETKE_KA1
READ (KLUN) YD%ETKE_KA2
READ (KLUN) YD%ETKE_KA3
READ (KLUN) YD%ENT_LAMBDA
READ (KLUN) YD%ETKE_CG01
READ (KLUN) YD%ETKE_CG02
READ (KLUN) YD%ETKE_CG03
READ (KLUN) YD%ETKE_BETA_EPS
READ (KLUN) YD%ETKE_GAMMA_EPS
READ (KLUN) YD%ETKE_GAMD
READ (KLUN) YD%ETKE_TALPH
READ (KLUN) YD%ETKE_ALPH0
READ (KLUN) YD%ETKE_ENTRX
READ (KLUN) YD%ETKE_ENTRN
READ (KLUN) YD%ETKE_KLM
READ (KLUN) YD%ETKE_TAULM
READ (KLUN) YD%ETKE_C0SHEAR
READ (KLUN) YD%ETKE_R1SIM
READ (KLUN) YD%ETKE_R2SIM
READ (KLUN) YD%ETKE_GB08A
READ (KLUN) YD%ETKE_GB08B
READ (KLUN) YD%ETKE_MIN
READ (KLUN) YD%ETKE_CRIT
READ (KLUN) YD%ETKE_DELTA
READ (KLUN) YD%EFB_AZ0
READ (KLUN) YD%EFB_UR
READ (KLUN) YD%REFB_1
READ (KLUN) YD%REFB_2
READ (KLUN) YD%REFB_3
READ (KLUN) YD%TUDBU
READ (KLUN) YD%TDDBU
READ (KLUN) YD%TUDFR
READ (KLUN) YD%TDDFR
READ (KLUN) YD%GCVALMX
READ (KLUN) YD%GCVTAUDE
READ (KLUN) YD%GCVACHI
READ (KLUN) YD%GCVBEE
READ (KLUN) YD%GCVEEX
READ (KLUN) YD%ECMNPI
READ (KLUN) YD%GRRMINA
READ (KLUN) YD%GDDBETA
READ (KLUN) YD%GDDDP
READ (KLUN) YD%GDDFXM
READ (KLUN) YD%GDDWPF
READ (KLUN) YD%GDDEVF
READ (KLUN) YD%TENTRD
READ (KLUN) YD%GDDALBU
READ (KLUN) YD%GDDFRAC
READ (KLUN) YD%GDDENDYMX
READ (KLUN) YD%GDDFP
READ (KLUN) YD%GDDTAUSIG
READ (KLUN) YD%GPEIPHI
READ (KLUN) YD%GPETAU
READ (KLUN) YD%GPEFDC
READ (KLUN) YD%GENVSRH
READ (KLUN) YD%GCVKSKV
READ (KLUN) YD%GCVALBU
READ (KLUN) YD%GCVENDY1
READ (KLUN) YD%GCVENDY2
READ (KLUN) YD%GCVENDYMX
READ (KLUN) YD%GCVIDPBAS
READ (KLUN) YD%GCVTAUSIG
READ (KLUN) YD%GTRGDPMIX
READ (KLUN) YD%GTRGDPHIMN
READ (KLUN) YD%GTRGPUSLMN
READ (KLUN) YD%GTRGKCK9
READ (KLUN) YD%GTRGAIN
READ (KLUN) YD%GTRTHRS
READ (KLUN) YD%GTRTHCK
READ (KLUN) YD%GTRBRC
READ (KLUN) YD%GTRKGAIN
READ (KLUN) YD%GTRKTHRS
READ (KLUN) YD%GTRKTHCK
READ (KLUN) YD%GCVCATAU
READ (KLUN) YD%GCATHRCAP
READ (KLUN) YD%GCATHRMOC
READ (KLUN) YD%GCATHRCND
READ (KLUN) YD%GCAOMCND
READ (KLUN) YD%NWEIGHT
READ (KLUN) YD%NCATAU
READ (KLUN) YD%NCAPEMAX
READ (KLUN) YD%NCVGMAX
READ (KLUN) YD%RNEGAT
READ (KLUN) YD%RNLCURV
READ (KLUN) YD%EDK
READ (KLUN) YD%XKLM
READ (KLUN) YD%AGRE1
READ (KLUN) YD%AGRERICR
READ (KLUN) YD%AJBUMIN
READ (KLUN) YD%RCOFLM
READ (KLUN) YD%TENTRVL
READ (KLUN) YD%TRENTRV
READ (KLUN) YD%GCVGAMMA
READ (KLUN) YD%LKESC
READ (KLUN) YD%AGRE2
READ (KLUN) YD%AGREF
READ (KLUN) YD%ALFX
READ (KLUN) YD%ALFX_LR
READ (KLUN) YD%ALFX_HR
READ (KLUN) YD%TCTC
READ (KLUN) YD%TVFC
READ (KLUN) YD%GAMAP1
READ (KLUN) YD%RKDN
READ (KLUN) YD%VVN
READ (KLUN) YD%VVX
READ (KLUN) YD%FENTRT
READ (KLUN) YD%FQLIC
READ (KLUN) YD%FNEBC
READ (KLUN) YD%FEVAPC
READ (KLUN) YD%RDPHIC
READ (KLUN) YD%RWBF1
READ (KLUN) YD%RWBF2
READ (KLUN) YD%SCLESPR
READ (KLUN) YD%SCLESPS
READ (KLUN) YD%HUCRED
READ (KLUN) YD%HUCREDRA
READ (KLUN) YD%FSPRAIN
READ (KLUN) YD%EFFCOLL
READ (KLUN) YD%RSMDNEBX
READ (KLUN) YD%RSMDTX
READ (KLUN) YD%NSMTPA
READ (KLUN) YD%NSMTPB
READ (KLUN) YD%RKFBTAU
READ (KLUN) YD%RKFBNBX
READ (KLUN) YD%GCVHMIN
READ (KLUN) YD%GCVRESN
READ (KLUN) YD%GCVRESX
READ (KLUN) YD%GMIRH
READ (KLUN) YD%RLMLH1
READ (KLUN) YD%RPRTH
READ (KLUN) YD%RSMOOTHMELT
READ (KLUN) YD%LADVLIM
READ (KLUN) YD%LGDDD
READ (KLUN) YD%LCVNHD
READ (KLUN) YD%LCVRESDYN
READ (KLUN) YD%LCVMICC
READ (KLUN) YD%GMUKEDD
READ (KLUN) YD%GNHDTAT
READ (KLUN) YD%GNHDSMOS
READ (KLUN) YD%GNHDSMOT
READ (KLUN) YD%GNHDEV
READ (KLUN) YD%LGVVEX
READ (KLUN) YD%LCVUVM
READ (KLUN) YD%NCVENTR
READ (KLUN) YD%NCVSIG
READ (KLUN) YD%NCVCLOS
READ (KLUN) YD%NCVQLI
READ (KLUN) YD%GCVENTRN
READ (KLUN) YD%GCVENTRX
READ (KLUN) YD%ADOE
READ (KLUN) YD%RFRAC_ENTR_N
READ (KLUN) YD%RFRAC_ENTR_X
READ (KLUN) YD%GCVENTR_MIN
READ (KLUN) YD%THPCMT
READ (KLUN) YD%AJ1PEPS
READ (KLUN) YD%AJ1MEPS
READ (KLUN) YD%NAJITER
READ (KLUN) YD%GAEPS
READ (KLUN) YD%GCVEZ
READ (KLUN) YD%GCVTRMIN
READ (KLUN) YD%LCVFEVV
READ (KLUN) YD%GCVFEVV
READ (KLUN) YD%LCVCONTAU
READ (KLUN) YD%GCVTEXC
READ (KLUN) YD%GCVWEXC
READ (KLUN) YD%LCVNAUV
READ (KLUN) YD%GCVFRR
READ (KLUN) YD%GCVPNH
READ (KLUN) YD%GCVORGED
READ (KLUN) YD%LCVIMPT
READ (KLUN) YD%GCVTAUREM
READ (KLUN) YD%GCLOEA
READ (KLUN) YD%GCLOEB
READ (KLUN) YD%GFRAE
READ (KLUN) YD%GCVADET
READ (KLUN) YD%GCVCINC
READ (KLUN) YD%GSDMIN
READ (KLUN) YD%GSDMAX
READ (KLUN) YD%GALMIN
READ (KLUN) YD%GALMAX
READ (KLUN) YD%GSDAMIN
READ (KLUN) YD%GSDAMAX
READ (KLUN) YD%GEXPKD
READ (KLUN) YD%LCVEOD
READ (KLUN) YD%GREMIN
READ (KLUN) YD%GREMAX
READ (KLUN) YD%GCHI0
READ (KLUN) YD%GFSURF
READ (KLUN) YD%GSHELL
READ (KLUN) YD%GFRIC
READ (KLUN) YD%GUDDD
READ (KLUN) YD%GSIGA
READ (KLUN) YD%GNHDSMOW
READ (KLUN) YD%GDEPTH
READ (KLUN) YD%GALTAU
READ (KLUN) YD%GKEDDRE
READ (KLUN) YD%GNHACC
READ (KLUN) YD%GTDCL
READ (KLUN) YD%GSINHD
READ (KLUN) YD%GSINHR
READ (KLUN) YD%GCVFNER
READ (KLUN) YD%GCVFNEO
READ (KLUN) YD%GCVFNEP1
READ (KLUN) YD%GCVFNEP2
READ (KLUN) YD%GRBCC
READ (KLUN) YD%GTOPDEPTH
READ (KLUN) YD%GCVTSMO
READ (KLUN) YD%RKDX
READ (KLUN) YD%LCAPCIN
READ (KLUN) YD%LCORSEDIM
READ (KLUN) YD%GNHDTAU
READ (KLUN) YD%GRSO
READ (KLUN) YD%GRTH
READ (KLUN) YD%GRFCS
READ (KLUN) YD%GCVRE
READ (KLUN) YD%LSBUO
READ (KLUN) YD%GREDDI
READ (KLUN) YD%GREDDL
READ (KLUN) YD%GREDDR
READ (KLUN) YD%GREDDS
READ (KLUN) YD%LCVTADV
READ (KLUN) YD%LCVDS
READ (KLUN) YD%GCVUV
READ (KLUN) YD%GCVGAW
READ (KLUN) YD%GCVGAX
READ (KLUN) YD%GCHECKMV_TMIN
READ (KLUN) YD%GCHECKMV_TMAX
READ (KLUN) YD%GCHECKMV_QVMIN
READ (KLUN) YD%GCHECKMV_QVMAX
READ (KLUN) YD%LGPRONI1
READ (KLUN) YD%NPRONI
READ (KLUN) YD%GPRONI
READ (KLUN) YD%RNEBCX
READ (KLUN) YD%GLIGHTT1
READ (KLUN) YD%GLIGHTT2
READ (KLUN) YD%GLIGHTT3
READ (KLUN) YD%REFLRHC
READ (KLUN) YD%TEQH
READ (KLUN) YD%REFLKUO
READ (KLUN) YD%REFLCAPE
READ (KLUN) YD%TEQK
READ (KLUN) YD%TEQC
READ (KLUN) YD%REPS
READ (KLUN) LRHUC
IF (LRHUC) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RHUC (IL1(1):IU1(1)))
  READ (KLUN) YD%RHUC
ENDIF
READ (KLUN) LRQSMOD
IF (LRQSMOD) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RQSMOD (IL1(1):IU1(1)))
  READ (KLUN) YD%RQSMOD
ENDIF
READ (KLUN) LRSURF
IF (LRSURF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RSURF (IL1(1):IU1(1)))
  READ (KLUN) YD%RSURF
ENDIF
READ (KLUN) LRN1D
IF (LRN1D) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RN1D (IL1(1):IU1(1)))
  READ (KLUN) YD%RN1D
ENDIF
READ (KLUN) LRRC1D
IF (LRRC1D) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RRC1D (IL1(1):IU1(1)))
  READ (KLUN) YD%RRC1D
ENDIF
READ (KLUN) LRSRC1D
IF (LRSRC1D) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RSRC1D (IL1(1):IU1(1)))
  READ (KLUN) YD%RSRC1D
ENDIF
READ (KLUN) YD%RCOEFRAIN
READ (KLUN) YD%RCOEFSNOW
END SUBROUTINE

SUBROUTINE COPY_TPHY0 (YD, LDCREATED)

IMPLICIT NONE
TYPE (TPHY0), INTENT (IN) :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LRHUC, LRN1D, LRQSMOD, LRRC1D, LRSRC1D, LRSURF

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
































































































































































































































































































































































































































































LRHUC = ALLOCATED (YD%RHUC)
IF (LRHUC) THEN
  !$acc enter data create (YD%RHUC)
  !$acc update device (YD%RHUC)
  !$acc enter data attach (YD%RHUC)
ENDIF

LRQSMOD = ALLOCATED (YD%RQSMOD)
IF (LRQSMOD) THEN
  !$acc enter data create (YD%RQSMOD)
  !$acc update device (YD%RQSMOD)
  !$acc enter data attach (YD%RQSMOD)
ENDIF

LRSURF = ALLOCATED (YD%RSURF)
IF (LRSURF) THEN
  !$acc enter data create (YD%RSURF)
  !$acc update device (YD%RSURF)
  !$acc enter data attach (YD%RSURF)
ENDIF

LRN1D = ALLOCATED (YD%RN1D)
IF (LRN1D) THEN
  !$acc enter data create (YD%RN1D)
  !$acc update device (YD%RN1D)
  !$acc enter data attach (YD%RN1D)
ENDIF

LRRC1D = ALLOCATED (YD%RRC1D)
IF (LRRC1D) THEN
  !$acc enter data create (YD%RRC1D)
  !$acc update device (YD%RRC1D)
  !$acc enter data attach (YD%RRC1D)
ENDIF

LRSRC1D = ALLOCATED (YD%RSRC1D)
IF (LRSRC1D) THEN
  !$acc enter data create (YD%RSRC1D)
  !$acc update device (YD%RSRC1D)
  !$acc enter data attach (YD%RSRC1D)
ENDIF



END SUBROUTINE
INTEGER*8 FUNCTION SIZE_TPHY0 (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TPHY0),     INTENT (IN) :: YD
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
LOGICAL,          INTENT (IN) :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LRHUC, LRN1D, LRQSMOD, LRRC1D, LRSRC1D, LRSURF

KSIZE = 0
ISIZE = KIND (YD%TYM) * SIZE (YD%TYM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TYM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NPCLO1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NPCLO1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NPCLO2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NPCLO2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%A0ML_AU)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%A0ML_AU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%A0ML_AT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%A0ML_AT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%A0ML_BU)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%A0ML_BU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%A0ML_BT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%A0ML_BT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%AERCS1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%AERCS1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%AERCS3)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%AERCS3'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%AERCS5)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%AERCS5'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ADJTAU)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ADJTAU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ALMAV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ALMAV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%BEDIFV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%BEDIFV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ECMNP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ECMNP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%EDB)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%EDB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%EDC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%EDC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%EDD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%EDD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%EVAP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%EVAP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FONT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FONT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GALP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GALP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCISMIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCISMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GEVAVF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GEVAVF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCCSV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCCSV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVADS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVADS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVBETA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVBETA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVIMPT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVIMPT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVOMGE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVOMGE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVOMGQ)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVOMGQ'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVOMGS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVOMGS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVTURB)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVTURB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVOMDPS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVOMDPS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVOMGSX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVOMGSX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVRHMIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVRHMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVRHMAX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVRHMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVOMCA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVOMCA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVOMCC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVOMCC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GDDEVA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GDDEVA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GDDSDE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GDDSDE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GDDFREVS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GDDFREVS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GDDINHOM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GDDINHOM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GRCVPP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GRCVPP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GWDAMP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GWDAMP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GWDBC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GWDBC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GWDCCO)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GWDCCO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GWDCD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GWDCD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GWDLT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GWDLT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GWDSE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GWDSE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GWDPROF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GWDPROF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GWDVALI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GWDVALI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%HOBST)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%HOBST'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%HUCOE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%HUCOE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%HUTIL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%HUTIL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%HUTIL1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%HUTIL1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%HUTIL2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%HUTIL2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%QSMIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%QSMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%QSMODC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%QSMODC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%QSNEBC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%QSNEBC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%QSNEBS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%QSNEBS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%QSSUSC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%QSSUSC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%QSSUSS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%QSSUSS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%QSSUSV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%QSSUSV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%QSUSXC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%QSUSXC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%QSUSXS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%QSUSXS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RPHI0)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RPHI0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RPHIR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RPHIR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%QXRAL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%QXRAL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%QXRAL_ADJ)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%QXRAL_ADJ'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%QXRDEL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%QXRDEL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%QXRHX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%QXRHX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%QXRR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%QXRR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%QXRTGH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%QXRTGH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%QXRCDIL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%QXRCDIL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RCIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RCIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RCVEVAP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RCVEVAP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDECRD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RDECRD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDECRD1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RDECRD1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDECRD2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RDECRD2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDECRD3)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RDECRD3'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDECRD4)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RDECRD4'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDECRDRED)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RDECRDRED'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDTFAC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RDTFAC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%REVAPN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%REVAPN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%REVGSL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%REVGSL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RGELSFON)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RGELSFON'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RFLCHCE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RFLCHCE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RTCAPE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RTCAPE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%SCO)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%SCO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%SENSL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%SENSL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%SNNBCO)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%SNNBCO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%SPNBCO)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%SPNBCO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%SXNBCO)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%SXNBCO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TCA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TCA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TCT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TCT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TCW)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TCW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TENTR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TENTR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TENTRX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TENTRX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TUDGP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TUDGP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TDDGP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TDDGP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TURB)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TURB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TVF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TVF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%UHDIFV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%UHDIFV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%USDMLT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%USDMLT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%USUPRC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%USUPRC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%USURIC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%USURIC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VCHRNK)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VCHRNK'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VKARMN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VKARMN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VZ0CM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VZ0CM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VZIUSTAR0)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VZIUSTAR0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XNBMAX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XNBMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%AECLS3)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%AECLS3'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%AECLS4)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%AECLS4'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ALD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ALD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%AKN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%AKN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ALPHAT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ALPHAT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ALPHAE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ALPHAE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%EPS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%EPS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETACUT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETACUT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ADISI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ADISI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ADISE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ADISE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ECTMIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ECTMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ECTMAX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ECTMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%AHCLPV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%AHCLPV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RICRLM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RICRLM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RMULACVG)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RMULACVG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XBLM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XBLM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XMINLM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XMINLM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XMAXLM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XMAXLM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XWSALM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XWSALM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XWSBLM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XWSBLM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVALFA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVALFA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVPSI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVPSI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVPSIE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVPSIE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%USURICE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%USURICE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%USURICL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%USURICL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%QSSC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%QSSC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%USURID)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%USURID'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVNU)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVNU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%USURIDE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%USURIDE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVMLT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVMLT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%UTILGUST)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%UTILGUST'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RRGAMMA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RRGAMMA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RRSCALE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RRSCALE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GPBLHK0)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GPBLHK0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GPBLHRA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GPBLHRA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%WMXOV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%WMXOV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ACBRPHIM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ACBRPHIM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ALMAVE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ALMAVE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ALMAVX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ALMAVX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ARSCH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ARSCH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ARSCQ)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ARSCQ'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ARSC1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ARSC1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ARSB2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ARSB2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RICRET)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RICRET'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%STTBMIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%STTBMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%UCWSTAR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%UCWSTAR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%UDECT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%UDECT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%UPRETMIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%UPRETMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%UPRETMAX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%UPRETMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%USHEARM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%USHEARM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RAUTEFR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RAUTEFR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RRAUTCS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RRAUTCS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RAUTEFS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RAUTEFS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RAUTSBET)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RAUTSBET'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RAUTEFG)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RAUTEFG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%REVASX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%REVASX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RNINTR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RNINTR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RNINTS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RNINTS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RQLCR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RQLCR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RSPCRR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RSPCRR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RQICRMAX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RQICRMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RQICRMIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RQICRMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RQLCV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RQLCV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RQICVMAX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RQICVMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RQICVMIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RQICVMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RQICRT1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RQICRT1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RQICRT2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RQICRT2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RQICRSN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RQICRSN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RQCRNS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RQCRNS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RACCEF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RACCEF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RAGGEF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RAGGEF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RRIMEF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RRIMEF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RHCRIT1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RHCRIT1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RHCRIT2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RHCRIT2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RETAMIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RETAMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RFACNSM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RFACNSM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TFVL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TFVL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TFVI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TFVI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TFVR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TFVR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TFVS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TFVS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GRHCMOD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GRHCMOD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RHCEXPDX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RHCEXPDX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NUPTKE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NUPTKE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TKEMULT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TKEMULT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%C_EPSILON)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%C_EPSILON'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%C3TKEFREE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%C3TKEFREE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_CTHETA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_CTHETA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_RIFC_MAF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_RIFC_MAF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_RIFC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_RIFC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_R)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_R'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_OLAM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_OLAM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_LAM0)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_LAM0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_LAM1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_LAM1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_LAM2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_LAM2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_LAM3)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_LAM3'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_LAM4)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_LAM4'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_KA1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_KA1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_KA2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_KA2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_KA3)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_KA3'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ENT_LAMBDA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ENT_LAMBDA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_CG01)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_CG01'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_CG02)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_CG02'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_CG03)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_CG03'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_BETA_EPS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_BETA_EPS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_GAMMA_EPS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_GAMMA_EPS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_GAMD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_GAMD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_TALPH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_TALPH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_ALPH0)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_ALPH0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_ENTRX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_ENTRX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_ENTRN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_ENTRN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_KLM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_KLM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_TAULM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_TAULM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_C0SHEAR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_C0SHEAR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_R1SIM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_R1SIM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_R2SIM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_R2SIM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_GB08A)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_GB08A'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_GB08B)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_GB08B'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_MIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_CRIT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_CRIT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETKE_DELTA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETKE_DELTA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%EFB_AZ0)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%EFB_AZ0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%EFB_UR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%EFB_UR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%REFB_1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%REFB_1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%REFB_2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%REFB_2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%REFB_3)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%REFB_3'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TUDBU)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TUDBU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TDDBU)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TDDBU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TUDFR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TUDFR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TDDFR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TDDFR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVALMX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVALMX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVTAUDE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVTAUDE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVACHI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVACHI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVBEE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVBEE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVEEX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVEEX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ECMNPI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ECMNPI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GRRMINA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GRRMINA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GDDBETA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GDDBETA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GDDDP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GDDDP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GDDFXM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GDDFXM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GDDWPF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GDDWPF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GDDEVF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GDDEVF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TENTRD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TENTRD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GDDALBU)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GDDALBU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GDDFRAC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GDDFRAC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GDDENDYMX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GDDENDYMX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GDDFP) * SIZE (YD%GDDFP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GDDFP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GDDTAUSIG)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GDDTAUSIG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GPEIPHI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GPEIPHI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GPETAU)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GPETAU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GPEFDC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GPEFDC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GENVSRH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GENVSRH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVKSKV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVKSKV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVALBU)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVALBU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVENDY1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVENDY1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVENDY2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVENDY2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVENDYMX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVENDYMX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVIDPBAS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVIDPBAS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVTAUSIG)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVTAUSIG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GTRGDPMIX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GTRGDPMIX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GTRGDPHIMN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GTRGDPHIMN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GTRGPUSLMN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GTRGPUSLMN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GTRGKCK9)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GTRGKCK9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GTRGAIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GTRGAIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GTRTHRS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GTRTHRS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GTRTHCK)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GTRTHCK'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GTRBRC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GTRBRC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GTRKGAIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GTRKGAIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GTRKTHRS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GTRKTHRS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GTRKTHCK)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GTRKTHCK'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVCATAU)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVCATAU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCATHRCAP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCATHRCAP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCATHRMOC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCATHRMOC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCATHRCND)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCATHRCND'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCAOMCND)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCAOMCND'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NWEIGHT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NWEIGHT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NCATAU)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NCATAU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NCAPEMAX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NCAPEMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NCVGMAX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NCVGMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RNEGAT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RNEGAT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RNLCURV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RNLCURV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%EDK)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%EDK'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XKLM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XKLM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%AGRE1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%AGRE1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%AGRERICR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%AGRERICR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%AJBUMIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%AJBUMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RCOFLM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RCOFLM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TENTRVL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TENTRVL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TRENTRV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TRENTRV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVGAMMA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVGAMMA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LKESC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LKESC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%AGRE2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%AGRE2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%AGREF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%AGREF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ALFX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ALFX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ALFX_LR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ALFX_LR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ALFX_HR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ALFX_HR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TCTC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TCTC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TVFC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TVFC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GAMAP1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GAMAP1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RKDN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RKDN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VVN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VVN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VVX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VVX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FENTRT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FENTRT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FQLIC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FQLIC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FNEBC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FNEBC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FEVAPC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FEVAPC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDPHIC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RDPHIC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RWBF1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RWBF1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RWBF2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RWBF2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%SCLESPR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%SCLESPR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%SCLESPS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%SCLESPS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%HUCRED)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%HUCRED'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%HUCREDRA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%HUCREDRA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%FSPRAIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%FSPRAIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%EFFCOLL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%EFFCOLL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RSMDNEBX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RSMDNEBX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RSMDTX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RSMDTX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSMTPA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NSMTPA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSMTPB)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NSMTPB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RKFBTAU)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RKFBTAU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RKFBNBX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RKFBNBX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVHMIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVHMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVRESN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVRESN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVRESX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVRESX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GMIRH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GMIRH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RLMLH1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RLMLH1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RPRTH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RPRTH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RSMOOTHMELT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RSMOOTHMELT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LADVLIM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LADVLIM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LGDDD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LGDDD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVNHD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LCVNHD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVRESDYN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LCVRESDYN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVMICC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LCVMICC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GMUKEDD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GMUKEDD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GNHDTAT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GNHDTAT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GNHDSMOS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GNHDSMOS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GNHDSMOT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GNHDSMOT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GNHDEV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GNHDEV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LGVVEX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LGVVEX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVUVM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LCVUVM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NCVENTR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NCVENTR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NCVSIG)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NCVSIG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NCVCLOS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NCVCLOS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NCVQLI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NCVQLI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVENTRN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVENTRN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVENTRX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVENTRX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ADOE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ADOE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RFRAC_ENTR_N)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RFRAC_ENTR_N'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RFRAC_ENTR_X)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RFRAC_ENTR_X'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVENTR_MIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVENTR_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%THPCMT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%THPCMT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%AJ1PEPS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%AJ1PEPS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%AJ1MEPS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%AJ1MEPS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NAJITER)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NAJITER'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GAEPS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GAEPS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVEZ)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVEZ'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVTRMIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVTRMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVFEVV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LCVFEVV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVFEVV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVFEVV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVCONTAU)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LCVCONTAU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVTEXC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVTEXC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVWEXC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVWEXC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVNAUV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LCVNAUV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVFRR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVFRR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVPNH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVPNH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVORGED)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVORGED'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVIMPT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LCVIMPT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVTAUREM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVTAUREM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCLOEA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCLOEA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCLOEB)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCLOEB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GFRAE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GFRAE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVADET)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVADET'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVCINC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVCINC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GSDMIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GSDMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GSDMAX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GSDMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GALMIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GALMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GALMAX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GALMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GSDAMIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GSDAMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GSDAMAX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GSDAMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GEXPKD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GEXPKD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVEOD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LCVEOD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GREMIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GREMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GREMAX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GREMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCHI0)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCHI0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GFSURF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GFSURF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GSHELL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GSHELL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GFRIC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GFRIC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GUDDD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GUDDD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GSIGA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GSIGA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GNHDSMOW)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GNHDSMOW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GDEPTH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GDEPTH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GALTAU)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GALTAU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GKEDDRE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GKEDDRE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GNHACC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GNHACC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GTDCL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GTDCL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GSINHD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GSINHD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GSINHR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GSINHR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVFNER)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVFNER'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVFNEO)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVFNEO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVFNEP1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVFNEP1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVFNEP2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVFNEP2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GRBCC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GRBCC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GTOPDEPTH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GTOPDEPTH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVTSMO)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVTSMO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RKDX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RKDX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCAPCIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LCAPCIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCORSEDIM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LCORSEDIM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GNHDTAU)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GNHDTAU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GRSO)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GRSO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GRTH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GRTH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GRFCS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GRFCS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVRE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVRE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSBUO)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LSBUO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GREDDI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GREDDI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GREDDL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GREDDL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GREDDR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GREDDR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GREDDS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GREDDS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVTADV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LCVTADV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVDS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LCVDS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVUV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVUV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVGAW)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVGAW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCVGAX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCVGAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCHECKMV_TMIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCHECKMV_TMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCHECKMV_TMAX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCHECKMV_TMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCHECKMV_QVMIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCHECKMV_QVMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GCHECKMV_QVMAX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GCHECKMV_QVMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LGPRONI1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LGPRONI1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NPRONI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NPRONI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GPRONI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GPRONI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RNEBCX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RNEBCX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GLIGHTT1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GLIGHTT1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GLIGHTT2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GLIGHTT2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GLIGHTT3)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%GLIGHTT3'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%REFLRHC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%REFLRHC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TEQH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TEQH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%REFLKUO)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%REFLKUO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%REFLCAPE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%REFLCAPE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TEQK)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TEQK'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TEQC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TEQC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%REPS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%REPS'
ENDIF
KSIZE = KSIZE + ISIZE
LRHUC = ALLOCATED (YD%RHUC)
IF (LRHUC) THEN
  ISIZE = KIND (YD%RHUC) * SIZE (YD%RHUC)
  IF (LDPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CDPATH)//'%RHUC'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRQSMOD = ALLOCATED (YD%RQSMOD)
IF (LRQSMOD) THEN
  ISIZE = KIND (YD%RQSMOD) * SIZE (YD%RQSMOD)
  IF (LDPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CDPATH)//'%RQSMOD'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRSURF = ALLOCATED (YD%RSURF)
IF (LRSURF) THEN
  ISIZE = KIND (YD%RSURF) * SIZE (YD%RSURF)
  IF (LDPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CDPATH)//'%RSURF'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRN1D = ALLOCATED (YD%RN1D)
IF (LRN1D) THEN
  ISIZE = KIND (YD%RN1D) * SIZE (YD%RN1D)
  IF (LDPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CDPATH)//'%RN1D'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRRC1D = ALLOCATED (YD%RRC1D)
IF (LRRC1D) THEN
  ISIZE = KIND (YD%RRC1D) * SIZE (YD%RRC1D)
  IF (LDPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CDPATH)//'%RRC1D'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRSRC1D = ALLOCATED (YD%RSRC1D)
IF (LRSRC1D) THEN
  ISIZE = KIND (YD%RSRC1D) * SIZE (YD%RSRC1D)
  IF (LDPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CDPATH)//'%RSRC1D'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
ISIZE = KIND (YD%RCOEFRAIN) * SIZE (YD%RCOEFRAIN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RCOEFRAIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RCOEFSNOW) * SIZE (YD%RCOEFSNOW)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RCOEFSNOW'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
