MODULE UTIL_TPHYDS_MOD

USE YOMPHYDS, ONLY : TPHYDS

INTERFACE SAVE
MODULE PROCEDURE SAVE_TPHYDS
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TPHYDS
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TPHYDS
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TPHYDS
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TPHYDS (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPHYDS), INTENT (IN) :: YD

WRITE (KLUN) YD%JPVXP
WRITE (KLUN) YD%JPVXP2
WRITE (KLUN) YD%JPCXP
WRITE (KLUN) YD%JPVEXTR
WRITE (KLUN) YD%JPVEXTRDI
WRITE (KLUN) YD%JPVXTR2
WRITE (KLUN) YD%JPVPRECIP
WRITE (KLUN) YD%JPVPRECIP2
WRITE (KLUN) YD%CEXTRP
WRITE (KLUN) YD%CXTRP2
WRITE (KLUN) YD%CVEXTRA
WRITE (KLUN) YD%CVEXRAD
WRITE (KLUN) YD%CVEXTRDI
WRITE (KLUN) YD%CVEXTR2
WRITE (KLUN) YD%CVPRECIP
WRITE (KLUN) YD%CVPRECIP2
WRITE (KLUN) YD%NEXTRPGB
WRITE (KLUN) YD%NXTRP2GB
WRITE (KLUN) YD%NVEXTRAGB
WRITE (KLUN) YD%NVEXRADGB
WRITE (KLUN) YD%NVEXTR2GB
WRITE (KLUN) YD%NVEXTRDIGB
WRITE (KLUN) YD%NVPRECIPGB
WRITE (KLUN) YD%NVPRECIPGB2
WRITE (KLUN) YD%NSFLUX
WRITE (KLUN) YD%NSFORC
WRITE (KLUN) YD%NPPVCLIX
WRITE (KLUN) YD%EXTRPDF
WRITE (KLUN) YD%XTRP2DF
WRITE (KLUN) YD%VEXTRADF
WRITE (KLUN) YD%VEXRADDF
WRITE (KLUN) YD%VEXTR2DF
WRITE (KLUN) YD%VEXTRDI
WRITE (KLUN) YD%VPRECIP
WRITE (KLUN) YD%VPRECIP2
WRITE (KLUN) YD%LREQIN_VEXTRDI
WRITE (KLUN) YD%LREQOUT_VEXTRDI
END SUBROUTINE
SUBROUTINE LOAD_TPHYDS (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPHYDS), INTENT (OUT) :: YD

READ (KLUN) YD%JPVXP
READ (KLUN) YD%JPVXP2
READ (KLUN) YD%JPCXP
READ (KLUN) YD%JPVEXTR
READ (KLUN) YD%JPVEXTRDI
READ (KLUN) YD%JPVXTR2
READ (KLUN) YD%JPVPRECIP
READ (KLUN) YD%JPVPRECIP2
READ (KLUN) YD%CEXTRP
READ (KLUN) YD%CXTRP2
READ (KLUN) YD%CVEXTRA
READ (KLUN) YD%CVEXRAD
READ (KLUN) YD%CVEXTRDI
READ (KLUN) YD%CVEXTR2
READ (KLUN) YD%CVPRECIP
READ (KLUN) YD%CVPRECIP2
READ (KLUN) YD%NEXTRPGB
READ (KLUN) YD%NXTRP2GB
READ (KLUN) YD%NVEXTRAGB
READ (KLUN) YD%NVEXRADGB
READ (KLUN) YD%NVEXTR2GB
READ (KLUN) YD%NVEXTRDIGB
READ (KLUN) YD%NVPRECIPGB
READ (KLUN) YD%NVPRECIPGB2
READ (KLUN) YD%NSFLUX
READ (KLUN) YD%NSFORC
READ (KLUN) YD%NPPVCLIX
READ (KLUN) YD%EXTRPDF
READ (KLUN) YD%XTRP2DF
READ (KLUN) YD%VEXTRADF
READ (KLUN) YD%VEXRADDF
READ (KLUN) YD%VEXTR2DF
READ (KLUN) YD%VEXTRDI
READ (KLUN) YD%VPRECIP
READ (KLUN) YD%VPRECIP2
READ (KLUN) YD%LREQIN_VEXTRDI
READ (KLUN) YD%LREQOUT_VEXTRDI
END SUBROUTINE

SUBROUTINE COPY_TPHYDS (YD, LDCREATED)

IMPLICIT NONE
TYPE (TPHYDS), INTENT (IN) :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF





































END SUBROUTINE
INTEGER*8 FUNCTION SIZE_TPHYDS (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TPHYDS),     INTENT (IN) :: YD
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
LOGICAL,          INTENT (IN) :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE

KSIZE = 0
ISIZE = KIND (YD%JPVXP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%JPVXP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%JPVXP2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%JPVXP2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%JPCXP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%JPCXP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%JPVEXTR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%JPVEXTR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%JPVEXTRDI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%JPVEXTRDI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%JPVXTR2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%JPVXTR2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%JPVPRECIP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%JPVPRECIP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%JPVPRECIP2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%JPVPRECIP2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CEXTRP) * SIZE (YD%CEXTRP) * LEN (YD%CEXTRP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%CEXTRP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CXTRP2) * SIZE (YD%CXTRP2) * LEN (YD%CXTRP2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%CXTRP2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CVEXTRA) * SIZE (YD%CVEXTRA) * LEN (YD%CVEXTRA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%CVEXTRA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CVEXRAD) * SIZE (YD%CVEXRAD) * LEN (YD%CVEXRAD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%CVEXRAD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CVEXTRDI) * SIZE (YD%CVEXTRDI) * LEN (YD%CVEXTRDI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%CVEXTRDI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CVEXTR2) * SIZE (YD%CVEXTR2) * LEN (YD%CVEXTR2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%CVEXTR2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CVPRECIP) * SIZE (YD%CVPRECIP) * LEN (YD%CVPRECIP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%CVPRECIP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CVPRECIP2) * SIZE (YD%CVPRECIP2) * LEN (YD%CVPRECIP2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%CVPRECIP2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NEXTRPGB) * SIZE (YD%NEXTRPGB)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NEXTRPGB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NXTRP2GB) * SIZE (YD%NXTRP2GB)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NXTRP2GB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NVEXTRAGB) * SIZE (YD%NVEXTRAGB)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NVEXTRAGB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NVEXRADGB) * SIZE (YD%NVEXRADGB)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NVEXRADGB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NVEXTR2GB) * SIZE (YD%NVEXTR2GB)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NVEXTR2GB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NVEXTRDIGB) * SIZE (YD%NVEXTRDIGB)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NVEXTRDIGB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NVPRECIPGB) * SIZE (YD%NVPRECIPGB)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NVPRECIPGB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NVPRECIPGB2) * SIZE (YD%NVPRECIPGB2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NVPRECIPGB2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSFLUX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NSFLUX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSFORC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NSFORC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NPPVCLIX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NPPVCLIX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%EXTRPDF) * SIZE (YD%EXTRPDF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%EXTRPDF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XTRP2DF) * SIZE (YD%XTRP2DF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XTRP2DF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VEXTRADF) * SIZE (YD%VEXTRADF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VEXTRADF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VEXRADDF) * SIZE (YD%VEXRADDF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VEXRADDF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VEXTR2DF) * SIZE (YD%VEXTR2DF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VEXTR2DF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VEXTRDI) * SIZE (YD%VEXTRDI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VEXTRDI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VPRECIP) * SIZE (YD%VPRECIP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VPRECIP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VPRECIP2) * SIZE (YD%VPRECIP2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%VPRECIP2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LREQIN_VEXTRDI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LREQIN_VEXTRDI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LREQOUT_VEXTRDI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LREQOUT_VEXTRDI'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
