MODULE UTIL_TARPHY_MOD

USE YOMARPHY, ONLY : TARPHY

INTERFACE SAVE
MODULE PROCEDURE SAVE_TARPHY
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TARPHY
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TARPHY
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TARPHY
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TARPHY (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TARPHY), INTENT (IN) :: YD

WRITE (KLUN) YD%LMPA
WRITE (KLUN) YD%LMSE
WRITE (KLUN) YD%LMICRO
WRITE (KLUN) YD%LTURB
WRITE (KLUN) YD%LKFBCONV
WRITE (KLUN) YD%LKFBD
WRITE (KLUN) YD%LKFBS
WRITE (KLUN) YD%LMFSHAL
WRITE (KLUN) YD%LUSECHEM
WRITE (KLUN) YD%LORILAM
WRITE (KLUN) YD%LRDUST
WRITE (KLUN) YD%LRCO2
WRITE (KLUN) YD%LINITCHEM
WRITE (KLUN) YD%LINITORILAM
WRITE (KLUN) YD%LINITDUST
WRITE (KLUN) YD%LRDEPOS
WRITE (KLUN) YD%LBUFLUX
WRITE (KLUN) YD%CCOUPLING
WRITE (KLUN) YD%LMDUST
WRITE (KLUN) YD%LSURFEX_KFROM
WRITE (KLUN) YD%LGRADHPHY
WRITE (KLUN) YD%NFLDCORE
WRITE (KLUN) YD%NGRADIENTS
END SUBROUTINE
SUBROUTINE LOAD_TARPHY (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TARPHY), INTENT (OUT) :: YD

READ (KLUN) YD%LMPA
READ (KLUN) YD%LMSE
READ (KLUN) YD%LMICRO
READ (KLUN) YD%LTURB
READ (KLUN) YD%LKFBCONV
READ (KLUN) YD%LKFBD
READ (KLUN) YD%LKFBS
READ (KLUN) YD%LMFSHAL
READ (KLUN) YD%LUSECHEM
READ (KLUN) YD%LORILAM
READ (KLUN) YD%LRDUST
READ (KLUN) YD%LRCO2
READ (KLUN) YD%LINITCHEM
READ (KLUN) YD%LINITORILAM
READ (KLUN) YD%LINITDUST
READ (KLUN) YD%LRDEPOS
READ (KLUN) YD%LBUFLUX
READ (KLUN) YD%CCOUPLING
READ (KLUN) YD%LMDUST
READ (KLUN) YD%LSURFEX_KFROM
READ (KLUN) YD%LGRADHPHY
READ (KLUN) YD%NFLDCORE
READ (KLUN) YD%NGRADIENTS
END SUBROUTINE

SUBROUTINE COPY_TARPHY (YD, LDCREATED)

IMPLICIT NONE
TYPE (TARPHY), INTENT (IN) :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF























END SUBROUTINE
INTEGER*8 FUNCTION SIZE_TARPHY (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TARPHY),     INTENT (IN) :: YD
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
LOGICAL,          INTENT (IN) :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE

KSIZE = 0
ISIZE = KIND (YD%LMPA)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LMPA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LMSE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LMSE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LMICRO)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LMICRO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LTURB)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LTURB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LKFBCONV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LKFBCONV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LKFBD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LKFBD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LKFBS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LKFBS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LMFSHAL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LMFSHAL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LUSECHEM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LUSECHEM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LORILAM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LORILAM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRDUST)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LRDUST'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRCO2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LRCO2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LINITCHEM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LINITCHEM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LINITORILAM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LINITORILAM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LINITDUST)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LINITDUST'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRDEPOS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LRDEPOS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LBUFLUX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LBUFLUX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CCOUPLING) * LEN (YD%CCOUPLING)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%CCOUPLING'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LMDUST)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LMDUST'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSURFEX_KFROM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LSURFEX_KFROM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LGRADHPHY)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LGRADHPHY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NFLDCORE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NFLDCORE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NGRADIENTS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NGRADIENTS'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
