MODULE UTIL_TLOUIS_MOD

USE YOMLOUIS, ONLY : TLOUIS

INTERFACE SAVE
MODULE PROCEDURE SAVE_TLOUIS
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TLOUIS
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TLOUIS
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TLOUIS
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TLOUIS (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TLOUIS), INTENT (IN) :: YD

WRITE (KLUN) YD%RLOUIS_S0
WRITE (KLUN) YD%PLOUIS_S0
WRITE (KLUN) YD%RLOUIS_GU1
WRITE (KLUN) YD%RLOUIS_GU2
WRITE (KLUN) YD%PLOUIS_GU1
WRITE (KLUN) YD%PLOUIS_GU2
WRITE (KLUN) YD%RLOUIS_GS1
WRITE (KLUN) YD%RLOUIS_GS2
WRITE (KLUN) YD%RLOUIS_GS3
WRITE (KLUN) YD%RLOUIS_GS4
WRITE (KLUN) YD%PLOUIS_GS1
WRITE (KLUN) YD%PLOUIS_GS2
WRITE (KLUN) YD%PLOUIS_GS3
WRITE (KLUN) YD%PLOUIS_GS4
END SUBROUTINE
SUBROUTINE LOAD_TLOUIS (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TLOUIS), INTENT (OUT) :: YD

READ (KLUN) YD%RLOUIS_S0
READ (KLUN) YD%PLOUIS_S0
READ (KLUN) YD%RLOUIS_GU1
READ (KLUN) YD%RLOUIS_GU2
READ (KLUN) YD%PLOUIS_GU1
READ (KLUN) YD%PLOUIS_GU2
READ (KLUN) YD%RLOUIS_GS1
READ (KLUN) YD%RLOUIS_GS2
READ (KLUN) YD%RLOUIS_GS3
READ (KLUN) YD%RLOUIS_GS4
READ (KLUN) YD%PLOUIS_GS1
READ (KLUN) YD%PLOUIS_GS2
READ (KLUN) YD%PLOUIS_GS3
READ (KLUN) YD%PLOUIS_GS4
END SUBROUTINE

SUBROUTINE COPY_TLOUIS (YD, LDCREATED)

IMPLICIT NONE
TYPE (TLOUIS), INTENT (IN) :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF














END SUBROUTINE
INTEGER*8 FUNCTION SIZE_TLOUIS (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TLOUIS),     INTENT (IN) :: YD
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
LOGICAL,          INTENT (IN) :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE

KSIZE = 0
ISIZE = KIND (YD%RLOUIS_S0)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RLOUIS_S0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%PLOUIS_S0)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%PLOUIS_S0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RLOUIS_GU1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RLOUIS_GU1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RLOUIS_GU2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RLOUIS_GU2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%PLOUIS_GU1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%PLOUIS_GU1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%PLOUIS_GU2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%PLOUIS_GU2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RLOUIS_GS1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RLOUIS_GS1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RLOUIS_GS2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RLOUIS_GS2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RLOUIS_GS3)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RLOUIS_GS3'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RLOUIS_GS4)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RLOUIS_GS4'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%PLOUIS_GS1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%PLOUIS_GS1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%PLOUIS_GS2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%PLOUIS_GS2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%PLOUIS_GS3)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%PLOUIS_GS3'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%PLOUIS_GS4)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%PLOUIS_GS4'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
