MODULE UTIL_TCVMNH_MOD

USE YOMCVMNH, ONLY : TCVMNH

INTERFACE SAVE
MODULE PROCEDURE SAVE_TCVMNH
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCVMNH
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TCVMNH
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TCVMNH
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TCVMNH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCVMNH), INTENT (IN) :: YD

WRITE (KLUN) YD%LDEEP
WRITE (KLUN) YD%LSHALLOW
WRITE (KLUN) YD%LDIAGCONV
WRITE (KLUN) YD%LSETTADJ
WRITE (KLUN) YD%LREFRESH_ALL
WRITE (KLUN) YD%LDOWN
WRITE (KLUN) YD%LSMOOTH
WRITE (KLUN) YD%OTADJD
WRITE (KLUN) YD%OTADJS
WRITE (KLUN) YD%NSETENS
WRITE (KLUN) YD%NIICE
WRITE (KLUN) YD%XA25
WRITE (KLUN) YD%XCRAD
WRITE (KLUN) YD%XCDEPTH
WRITE (KLUN) YD%XCDEPTH_D
WRITE (KLUN) YD%XDTPERT
WRITE (KLUN) YD%XENTR
WRITE (KLUN) YD%XZLCL
WRITE (KLUN) YD%XZPBL
WRITE (KLUN) YD%XWTRIG
WRITE (KLUN) YD%XNHGAM
WRITE (KLUN) YD%XTFRZ1
WRITE (KLUN) YD%XTFRZ2
WRITE (KLUN) YD%XSTABT
WRITE (KLUN) YD%XSTABC
WRITE (KLUN) YD%XAW
WRITE (KLUN) YD%XBW
WRITE (KLUN) YD%XATPERT
WRITE (KLUN) YD%XBTPERT
END SUBROUTINE
SUBROUTINE LOAD_TCVMNH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCVMNH), INTENT (OUT) :: YD

READ (KLUN) YD%LDEEP
READ (KLUN) YD%LSHALLOW
READ (KLUN) YD%LDIAGCONV
READ (KLUN) YD%LSETTADJ
READ (KLUN) YD%LREFRESH_ALL
READ (KLUN) YD%LDOWN
READ (KLUN) YD%LSMOOTH
READ (KLUN) YD%OTADJD
READ (KLUN) YD%OTADJS
READ (KLUN) YD%NSETENS
READ (KLUN) YD%NIICE
READ (KLUN) YD%XA25
READ (KLUN) YD%XCRAD
READ (KLUN) YD%XCDEPTH
READ (KLUN) YD%XCDEPTH_D
READ (KLUN) YD%XDTPERT
READ (KLUN) YD%XENTR
READ (KLUN) YD%XZLCL
READ (KLUN) YD%XZPBL
READ (KLUN) YD%XWTRIG
READ (KLUN) YD%XNHGAM
READ (KLUN) YD%XTFRZ1
READ (KLUN) YD%XTFRZ2
READ (KLUN) YD%XSTABT
READ (KLUN) YD%XSTABC
READ (KLUN) YD%XAW
READ (KLUN) YD%XBW
READ (KLUN) YD%XATPERT
READ (KLUN) YD%XBTPERT
END SUBROUTINE

SUBROUTINE COPY_TCVMNH (YD, LDCREATED)

IMPLICIT NONE
TYPE (TCVMNH), INTENT (IN) :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF





























END SUBROUTINE
INTEGER*8 FUNCTION SIZE_TCVMNH (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TCVMNH),     INTENT (IN) :: YD
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
LOGICAL,          INTENT (IN) :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE

KSIZE = 0
ISIZE = KIND (YD%LDEEP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LDEEP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSHALLOW)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LSHALLOW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LDIAGCONV)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LDIAGCONV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSETTADJ)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LSETTADJ'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LREFRESH_ALL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LREFRESH_ALL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LDOWN)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LDOWN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSMOOTH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%LSMOOTH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%OTADJD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%OTADJD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%OTADJS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%OTADJS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSETENS)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NSETENS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NIICE)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NIICE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XA25)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XA25'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XCRAD)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XCRAD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XCDEPTH)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XCDEPTH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XCDEPTH_D)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XCDEPTH_D'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XDTPERT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XDTPERT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XENTR)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XENTR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XZLCL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XZLCL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XZPBL)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XZPBL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XWTRIG)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XWTRIG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XNHGAM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XNHGAM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XTFRZ1)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XTFRZ1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XTFRZ2)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XTFRZ2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XSTABT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XSTABT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XSTABC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XSTABC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XAW)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XAW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XBW)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XBW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XATPERT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XATPERT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XBTPERT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XBTPERT'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
