MODULE UTIL_TTOPH_MOD

USE YOMTOPH, ONLY : TTOPH

INTERFACE SAVE
MODULE PROCEDURE SAVE_TTOPH
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TTOPH
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TTOPH
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TTOPH
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TTOPH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TTOPH), INTENT (IN) :: YD
LOGICAL :: LRMESOQ, LRMESOT, LRMESOU, LRQREL, LRTREL, LRUREL, LRVREL
LRMESOU = ALLOCATED (YD%RMESOU)
WRITE (KLUN) LRMESOU
IF (LRMESOU) THEN
  WRITE (KLUN) LBOUND (YD%RMESOU)
  WRITE (KLUN) UBOUND (YD%RMESOU)
  WRITE (KLUN) YD%RMESOU
ENDIF
LRMESOT = ALLOCATED (YD%RMESOT)
WRITE (KLUN) LRMESOT
IF (LRMESOT) THEN
  WRITE (KLUN) LBOUND (YD%RMESOT)
  WRITE (KLUN) UBOUND (YD%RMESOT)
  WRITE (KLUN) YD%RMESOT
ENDIF
LRMESOQ = ALLOCATED (YD%RMESOQ)
WRITE (KLUN) LRMESOQ
IF (LRMESOQ) THEN
  WRITE (KLUN) LBOUND (YD%RMESOQ)
  WRITE (KLUN) UBOUND (YD%RMESOQ)
  WRITE (KLUN) YD%RMESOQ
ENDIF
LRUREL = ALLOCATED (YD%RUREL)
WRITE (KLUN) LRUREL
IF (LRUREL) THEN
  WRITE (KLUN) LBOUND (YD%RUREL)
  WRITE (KLUN) UBOUND (YD%RUREL)
  WRITE (KLUN) YD%RUREL
ENDIF
LRVREL = ALLOCATED (YD%RVREL)
WRITE (KLUN) LRVREL
IF (LRVREL) THEN
  WRITE (KLUN) LBOUND (YD%RVREL)
  WRITE (KLUN) UBOUND (YD%RVREL)
  WRITE (KLUN) YD%RVREL
ENDIF
LRTREL = ALLOCATED (YD%RTREL)
WRITE (KLUN) LRTREL
IF (LRTREL) THEN
  WRITE (KLUN) LBOUND (YD%RTREL)
  WRITE (KLUN) UBOUND (YD%RTREL)
  WRITE (KLUN) YD%RTREL
ENDIF
LRQREL = ALLOCATED (YD%RQREL)
WRITE (KLUN) LRQREL
IF (LRQREL) THEN
  WRITE (KLUN) LBOUND (YD%RQREL)
  WRITE (KLUN) UBOUND (YD%RQREL)
  WRITE (KLUN) YD%RQREL
ENDIF
WRITE (KLUN) YD%RFMESOQ
WRITE (KLUN) YD%NTQSAT
WRITE (KLUN) YD%NTDIFU
WRITE (KLUN) YD%NTCOEF
WRITE (KLUN) YD%NTDRAG
WRITE (KLUN) YD%NTCVIM
WRITE (KLUN) YD%NT850
WRITE (KLUN) YD%NT950
WRITE (KLUN) YD%NTPLUI
WRITE (KLUN) YD%NTRADI
WRITE (KLUN) YD%NTNEBU
WRITE (KLUN) YD%NTOZON
WRITE (KLUN) YD%NTDRME
WRITE (KLUN) YD%NTCOET
WRITE (KLUN) YD%NTAJUC
WRITE (KLUN) YD%NTRELAXT
WRITE (KLUN) YD%NTRELAXQ
WRITE (KLUN) YD%NTRELAXU
WRITE (KLUN) YD%ETQSAT
WRITE (KLUN) YD%ETDIFU
WRITE (KLUN) YD%ETCOEF
WRITE (KLUN) YD%ETDRAG
WRITE (KLUN) YD%ETCVIM
WRITE (KLUN) YD%ET850
WRITE (KLUN) YD%ET950
WRITE (KLUN) YD%ETPLUI
WRITE (KLUN) YD%ETRADI
WRITE (KLUN) YD%ETNEBU
WRITE (KLUN) YD%ETOZON
WRITE (KLUN) YD%ETDRME
WRITE (KLUN) YD%ETCOET
WRITE (KLUN) YD%ETAJUC
WRITE (KLUN) YD%ETRELAXT
WRITE (KLUN) YD%ETRELAXQ
WRITE (KLUN) YD%ETRELAXU
WRITE (KLUN) YD%XDRMUK
WRITE (KLUN) YD%XDRMUX
WRITE (KLUN) YD%XDRMUP
WRITE (KLUN) YD%XDRMTK
WRITE (KLUN) YD%XDRMTX
WRITE (KLUN) YD%XDRMTP
WRITE (KLUN) YD%XDRMQK
WRITE (KLUN) YD%XDRMQP
WRITE (KLUN) YD%XDRMQX
WRITE (KLUN) YD%RCLX
WRITE (KLUN) YD%TPSCLIM
END SUBROUTINE
SUBROUTINE LOAD_TTOPH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TTOPH), INTENT (OUT) :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LRMESOQ, LRMESOT, LRMESOU, LRQREL, LRTREL, LRUREL, LRVREL
READ (KLUN) LRMESOU
IF (LRMESOU) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RMESOU (IL1(1):IU1(1)))
  READ (KLUN) YD%RMESOU
ENDIF
READ (KLUN) LRMESOT
IF (LRMESOT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RMESOT (IL1(1):IU1(1)))
  READ (KLUN) YD%RMESOT
ENDIF
READ (KLUN) LRMESOQ
IF (LRMESOQ) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RMESOQ (IL1(1):IU1(1)))
  READ (KLUN) YD%RMESOQ
ENDIF
READ (KLUN) LRUREL
IF (LRUREL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RUREL (IL1(1):IU1(1)))
  READ (KLUN) YD%RUREL
ENDIF
READ (KLUN) LRVREL
IF (LRVREL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RVREL (IL1(1):IU1(1)))
  READ (KLUN) YD%RVREL
ENDIF
READ (KLUN) LRTREL
IF (LRTREL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RTREL (IL1(1):IU1(1)))
  READ (KLUN) YD%RTREL
ENDIF
READ (KLUN) LRQREL
IF (LRQREL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RQREL (IL1(1):IU1(1)))
  READ (KLUN) YD%RQREL
ENDIF
READ (KLUN) YD%RFMESOQ
READ (KLUN) YD%NTQSAT
READ (KLUN) YD%NTDIFU
READ (KLUN) YD%NTCOEF
READ (KLUN) YD%NTDRAG
READ (KLUN) YD%NTCVIM
READ (KLUN) YD%NT850
READ (KLUN) YD%NT950
READ (KLUN) YD%NTPLUI
READ (KLUN) YD%NTRADI
READ (KLUN) YD%NTNEBU
READ (KLUN) YD%NTOZON
READ (KLUN) YD%NTDRME
READ (KLUN) YD%NTCOET
READ (KLUN) YD%NTAJUC
READ (KLUN) YD%NTRELAXT
READ (KLUN) YD%NTRELAXQ
READ (KLUN) YD%NTRELAXU
READ (KLUN) YD%ETQSAT
READ (KLUN) YD%ETDIFU
READ (KLUN) YD%ETCOEF
READ (KLUN) YD%ETDRAG
READ (KLUN) YD%ETCVIM
READ (KLUN) YD%ET850
READ (KLUN) YD%ET950
READ (KLUN) YD%ETPLUI
READ (KLUN) YD%ETRADI
READ (KLUN) YD%ETNEBU
READ (KLUN) YD%ETOZON
READ (KLUN) YD%ETDRME
READ (KLUN) YD%ETCOET
READ (KLUN) YD%ETAJUC
READ (KLUN) YD%ETRELAXT
READ (KLUN) YD%ETRELAXQ
READ (KLUN) YD%ETRELAXU
READ (KLUN) YD%XDRMUK
READ (KLUN) YD%XDRMUX
READ (KLUN) YD%XDRMUP
READ (KLUN) YD%XDRMTK
READ (KLUN) YD%XDRMTX
READ (KLUN) YD%XDRMTP
READ (KLUN) YD%XDRMQK
READ (KLUN) YD%XDRMQP
READ (KLUN) YD%XDRMQX
READ (KLUN) YD%RCLX
READ (KLUN) YD%TPSCLIM
END SUBROUTINE

SUBROUTINE COPY_TTOPH (YD, LDCREATED)

IMPLICIT NONE
TYPE (TTOPH), INTENT (IN) :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LRMESOQ, LRMESOT, LRMESOU, LRQREL, LRTREL, LRUREL, LRVREL

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LRMESOU = ALLOCATED (YD%RMESOU)
IF (LRMESOU) THEN
  !$acc enter data create (YD%RMESOU)
  !$acc update device (YD%RMESOU)
  !$acc enter data attach (YD%RMESOU)
ENDIF

LRMESOT = ALLOCATED (YD%RMESOT)
IF (LRMESOT) THEN
  !$acc enter data create (YD%RMESOT)
  !$acc update device (YD%RMESOT)
  !$acc enter data attach (YD%RMESOT)
ENDIF

LRMESOQ = ALLOCATED (YD%RMESOQ)
IF (LRMESOQ) THEN
  !$acc enter data create (YD%RMESOQ)
  !$acc update device (YD%RMESOQ)
  !$acc enter data attach (YD%RMESOQ)
ENDIF

LRUREL = ALLOCATED (YD%RUREL)
IF (LRUREL) THEN
  !$acc enter data create (YD%RUREL)
  !$acc update device (YD%RUREL)
  !$acc enter data attach (YD%RUREL)
ENDIF

LRVREL = ALLOCATED (YD%RVREL)
IF (LRVREL) THEN
  !$acc enter data create (YD%RVREL)
  !$acc update device (YD%RVREL)
  !$acc enter data attach (YD%RVREL)
ENDIF

LRTREL = ALLOCATED (YD%RTREL)
IF (LRTREL) THEN
  !$acc enter data create (YD%RTREL)
  !$acc update device (YD%RTREL)
  !$acc enter data attach (YD%RTREL)
ENDIF

LRQREL = ALLOCATED (YD%RQREL)
IF (LRQREL) THEN
  !$acc enter data create (YD%RQREL)
  !$acc update device (YD%RQREL)
  !$acc enter data attach (YD%RQREL)
ENDIF















































END SUBROUTINE
INTEGER*8 FUNCTION SIZE_TTOPH (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TTOPH),     INTENT (IN) :: YD
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
LOGICAL,          INTENT (IN) :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LRMESOQ, LRMESOT, LRMESOU, LRQREL, LRTREL, LRUREL, LRVREL

KSIZE = 0
LRMESOU = ALLOCATED (YD%RMESOU)
IF (LRMESOU) THEN
  ISIZE = KIND (YD%RMESOU) * SIZE (YD%RMESOU)
  IF (LDPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CDPATH)//'%RMESOU'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRMESOT = ALLOCATED (YD%RMESOT)
IF (LRMESOT) THEN
  ISIZE = KIND (YD%RMESOT) * SIZE (YD%RMESOT)
  IF (LDPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CDPATH)//'%RMESOT'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRMESOQ = ALLOCATED (YD%RMESOQ)
IF (LRMESOQ) THEN
  ISIZE = KIND (YD%RMESOQ) * SIZE (YD%RMESOQ)
  IF (LDPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CDPATH)//'%RMESOQ'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRUREL = ALLOCATED (YD%RUREL)
IF (LRUREL) THEN
  ISIZE = KIND (YD%RUREL) * SIZE (YD%RUREL)
  IF (LDPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CDPATH)//'%RUREL'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRVREL = ALLOCATED (YD%RVREL)
IF (LRVREL) THEN
  ISIZE = KIND (YD%RVREL) * SIZE (YD%RVREL)
  IF (LDPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CDPATH)//'%RVREL'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRTREL = ALLOCATED (YD%RTREL)
IF (LRTREL) THEN
  ISIZE = KIND (YD%RTREL) * SIZE (YD%RTREL)
  IF (LDPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CDPATH)//'%RTREL'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRQREL = ALLOCATED (YD%RQREL)
IF (LRQREL) THEN
  ISIZE = KIND (YD%RQREL) * SIZE (YD%RQREL)
  IF (LDPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CDPATH)//'%RQREL'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
ISIZE = KIND (YD%RFMESOQ)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RFMESOQ'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NTQSAT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NTQSAT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NTDIFU)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NTDIFU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NTCOEF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NTCOEF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NTDRAG)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NTDRAG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NTCVIM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NTCVIM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NT850)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NT850'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NT950)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NT950'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NTPLUI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NTPLUI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NTRADI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NTRADI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NTNEBU)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NTNEBU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NTOZON)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NTOZON'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NTDRME)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NTDRME'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NTCOET)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NTCOET'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NTAJUC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NTAJUC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NTRELAXT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NTRELAXT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NTRELAXQ)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NTRELAXQ'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NTRELAXU)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%NTRELAXU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETQSAT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETQSAT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETDIFU)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETDIFU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETCOEF)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETCOEF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETDRAG)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETDRAG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETCVIM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETCVIM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ET850)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ET850'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ET950)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ET950'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETPLUI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETPLUI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETRADI)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETRADI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETNEBU)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETNEBU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETOZON)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETOZON'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETDRME)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETDRME'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETCOET)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETCOET'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETAJUC)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETAJUC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETRELAXT)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETRELAXT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETRELAXQ)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETRELAXQ'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ETRELAXU)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%ETRELAXU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XDRMUK)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XDRMUK'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XDRMUX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XDRMUX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XDRMUP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XDRMUP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XDRMTK)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XDRMTK'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XDRMTX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XDRMTX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XDRMTP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XDRMTP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XDRMQK)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XDRMQK'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XDRMQP)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XDRMQP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XDRMQX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%XDRMQX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RCLX)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%RCLX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TPSCLIM)
IF (LDPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CDPATH)//'%TPSCLIM'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
