PROGRAM WRAP_ACTKE
!SUBROUTINE WRAP_ACTKE ()

!**** *ACTKE * - SCHEMA DE TURBULENCE TKE

!     Sujet.
!     ------
!     - APPEL DES SOUS-PROGRAMMES ACBL89, ACTURB, ACEVOLET

!**   Interface.
!     ----------
!        *CALL* *ACTKE*

!-----------------------------------------------------------------------

!     Auteur.
!     -------
!       04-11, Francois Bouyssel

!   Modifications.
!   --------------
!      2006-04-11 E. Bazile : Ajout de CDLOCK.
!      2006-05-04 E. Bazile : Possibilite de passer l'ECT sur Full-level 
!                             (LECTFL) pour l'advection.
!      2007-05-10 E. Bazile : PXTXX en sortie, PQC0, PNEBS0 pour rayt.
!      2008-04-28 E. Bazile : Introduction of PPROTH and removal PRS, PSTAB
!      K. Yessad (Jul 2009): remove CDLOCK + some cleanings
!      2009-11-10 E. Bazile : Input of PDELP for ACEVOLET.
!      2010-12-01 E. Bazile : Output for AROCLDIA of TKE(t+dt)
!      2011-10-01 E. Bazile : TKE fluxes for DDH and use of HL2FL and FL2HL
!      2014-10-14 E. Bazile : EDR : Output similar to TKE dissipation (>0)
!      2015-03-11 J.M Piriou: fix bug in case of LFLEXDIA=T: introduce ZDIAG array.
!      2016-10-04 P. Marguinaud: Port to single precision
!      2018-09-19 R. Roehrig: Add convection index LLCONV and PKQROV/PKQLROV (from JF Guérémy)
!-----------------------------------------------------------------------


! -   ARGUMENTS D'ENTREE.
!   -------------------

! - NOM DES PARAMETRES DE DIMENSIONNEMENT DE LA PHYSIQUE.

! KIDIA      : INDICE DE DEPART DES BOUCLES VECTORISEES SUR L'HORIZONT.
! KFDIA      : INDICE DE FIN DES BOUCLES VECTORISEES SUR L'HORIZONTALE.
! KLON       : DIMENSION HORIZONTALE DES TABLEAUX.
! KTDIAT     : INDICE DE DEPART DES BOUCLES VERTICALES (1 EN GENERAL)
!              POUR LES CALCULS DE TURBULENCE.
! KTDIAN     : INDICE DE DEPART DES BOUCLES VERTICALES (1 EN GENERAL)
!              POUR LES CALCULS DE TURBULENCE + NEBULOSITE.
! KLEV       : DIMENSION VERTICALE DES TABLEAUX "FULL LEVEL".

! - 2D (0:KLEV) .

! PAPHI      : GEOPOTENTIEL AUX DEMI-NIVEAUX.
! PAPRS      : PRESSION AUX DEMI-NIVEAUX.
! PPRODTH    : PRODUCTION THERMIQUE DU A AU SCHEMA SHALLOW.

! - 2D (1:KLEV) .

! PAPHIF     : GEOPOTENTIEL AUX NIVEAUX DES COUCHES.
! PAPRSF     : PRESSION AUX NIVEAUX DES COUCHES.
! PDELP      : EPAISSEUR EN PRESSION DE LA COUCHE.
! PR         : CONSTANTE DES GAZ POUR L'AIR.
! PT         : TEMPERATURE (APRES AJUSTEMENT CONVECTIF).
! PU         : COMPOSANTE EN X DU VENT.
! PV         : COMPOSANTE EN Y DU VENT.
! PQ         : HUMIDITE SPECIFIQUE DE LA VAPEUR D'EAU.
! PQICONV    : EAU LIQUIDE CONVECTIVE.
! PQLCONV    : EAU SOLIDE CONVECTIVE.
! PLSCPE     : RAPPORT EFECTIF DES L ET CP EN CONDENSATION/EVAPORATION.
! PECT       : ENERGIE CINETIQUE TURBULENTE.

! - 1D (DIAGNOSTIQUE) .

! PCD        : COEFFICIENT D'ECHANGE EN SURFACE POUR U ET V
! PCH        : COEFFICIENT D'ECHANGE EN SURFACE POUR T ET Q
! PGZ0       : G FOIS LA LONGUEUR DE RUGOSITE COURANTE.
! PTS        : TEMPERATURE DE SURFACE
! PQS        : HUMIDITE SPECIFIQUE DE SURFACE.

!-----------------------------------------------------------------------

! -   ARGUMENTS EN ENTREE/SORTIE.
!     ---------------------------

! - 2D (1:KLEV) .

! PQICE      : HUMIDITE SPECIFIQUE  SOLIDE "PRONOSTIQUE".
! PQLI       : HUMIDITE SPECIFIQUE LIQUIDE "PRONOSTIQUE".
! PNLAB      : Si 1 Presence d'un nuage Shallow (used in ACBL89)
! PNLABCVP   : Si 1 Presence d'un nuage Deep    (used in ACBL89)


!-----------------------------------------------------------------------

! -   ARGUMENTS DE SORTIE.
!     --------------------

! - NOM DES VARIABLES DE LA PHYSIQUE (PAR ORDRE ALPHABETIQUE DANS CHAQUE
!   CATEGORIE).

! - 2D (0:KLEV) .

! PKTROV     : COEFFICIENT D'ECHANGE VERTICAL DE T EN KG/(M*M*S).
! PKQROV     : COEFFICIENT D'ECHANGE VERTICAL DE Q EN KG/(M*M*S).
! PKQLROV    : COEFFICIENT D'ECHANGE VERTICAL DE QL EN KG/(M*M*S).
! PKUROV     : COEFFICIENT D'ECHANGE VERTICAL DE U ET V EN KG/(M*M*S).
! PXTROV     : MULTIPLICATEUR "ANTI-FIBRILLATION" DE PKTROV.
! PXUROV     : MULTIPLICATEUR "ANTI-FIBRILLATION" DE PKUROV.
! PNBVNO     : CARRE DE FR. BRUNT-VAISALA DIVISEE PAR G FOIS LA DENSITE.

! - 2D (1:KLEV) .

! PNEBS      : NEBULOSITE PARTIELLE STRATIFORME.
! PQCS       : EAU CONDENSEE STRATIFORME.
! PNEBS      : NEBULOSITE PARTIELLE STRATIFORME APRES AJUSTEMENT.
!            : STRATIFORM FRACTIONAL CLOUDINESS APRES AJUSTEMENT.
! PQCS0      : CONTENU "STRATIFORME" EN CONDENSAT NUAGEUX POUR RAYT.
!            : STRATIRORM CLOUD WATER (LIQUID + SOLID) FOR RADIATION.
! PNEBS0     : NEBULOSITE PARTIELLE STRATIFORME POUR RAYT.
! PCOEFN     : COEFFICIENT STATISTIQUE POUR LES FLUX D'EAUX CONDENSEES.
! PTPRDY     : tendance de TKE due a la production dynamique.
! PEDR       : EDR tendance de TKE due a la dissipation (calcul specifique)

!-----------------------------------------------------------------------

USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE YOMMDDH              , ONLY : TMDDH
USE PARKIND1             , ONLY : JPIM,    JPRB
USE YOMHOOK              , ONLY : LHOOK,   DR_HOOK


USE YOMCT3               , ONLY : NSTEP
USE YOMMP0               , ONLY : MYPROC

USE YOMCST               , ONLY : TCST
USE YOMLSFORC            , ONLY : LMUSCLFA,NMUSCLFA
USE YOMLDDH              , ONLY : TLDDH
USE DDH_MIX              , ONLY : ADD_FIELD_3D, TYP_DDH, NEW_ADD_FIELD_3D 


USE UTIL_TCST_MOD
USE UTIL_MODEL_PHYSICS_MF_TYPE_MOD
USE GETDATA_MOD
USE CHECK_UTILS_MOD
USE XRD_GETOPTIONS

!-----------------------------------------------------------------------

IMPLICIT NONE

TYPE (TCST) :: YDCST
TYPE(TLDDH)        :: YDLDDH
TYPE(TMDDH)        :: YDMDDH
TYPE(MODEL_PHYSICS_MF_TYPE) :: YDML_PHY_MF
INTEGER(KIND=JPIM)    :: KIDIA 
INTEGER(KIND=JPIM)    :: KFDIA 
INTEGER(KIND=JPIM)    :: KLON 
INTEGER(KIND=JPIM)    :: KTDIAT 
INTEGER(KIND=JPIM)    :: KTDIAN 
INTEGER(KIND=JPIM)    :: KLEV 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PAPHI(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PAPHIF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PAPRS(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PAPRSF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PDELP(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PR(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PT(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PU(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PV(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PQ(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PQICONV(:,:,:)
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PQLCONV(:,:,:)
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PLSCPE(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PCD(:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PCH(:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PGZ0(:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PTS(:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PQS(:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PQICE(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PQLI(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PECT(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PPRODTH(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PNLAB(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PNLABCVP(:,:,:) 


REAL(KIND=JPRB)   ,ALLOCATABLE   :: PKTROV(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PKQROV(:,:,:)
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PKQLROV(:,:,:)
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PKUROV(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PXTROV(:,:,:)
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PXUROV(:,:,:)
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PNBVNO(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PNEBS(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PQCS(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PNEBS0(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PQCS0(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PCOEFN(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PECT1(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PFECT(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PFECTI(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PTPRDY(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PEDR(:,:,:) 


REAL(KIND=JPRB)   ,ALLOCATABLE    :: PQICE_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PQLI_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PECT_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PPRODTH_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PNLAB_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE    :: PNLABCVP_REF(:,:,:) 

REAL(KIND=JPRB)   ,ALLOCATABLE   :: PKTROV_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PKQROV_REF(:,:,:)
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PKQLROV_REF(:,:,:)
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PKUROV_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PXTROV_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PXUROV_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PNBVNO_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PNEBS_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PQCS_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PNEBS0_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PQCS0_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PCOEFN_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PECT1_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PFECT_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PFECTI_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PTPRDY_REF(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PEDR_REF(:,:,:) 


#include "actke.intfb.h"

INTEGER :: ILUN
CHARACTER*32 :: CLCASE
CHARACTER*64 :: FILENAME
INTEGER :: CLCASE_NUM, CLCASE_MIN, CLCASE_MAX
INTEGER(KIND=JPIM)    :: NPROMA, NGPBLKS, NGPTOT, KLONTOT
LOGICAL :: LLCHECK
INTEGER :: I, J, IBL

NPROMA = 0
NGPBLKS = 0

CALL INITOPTIONS ()
CALL GETOPTION ("--blocks", NGPBLKS)
CALL GETOPTION ("--nproma", NPROMA)
CALL GETOPTION ("--check",  LLCHECK)
CALL GETOPTION ("--case", CLCASE, MND=.TRUE.)
CALL GETOPTION ("--casenum", CLCASE_NUM, MND=.TRUE.)
CALL GETOPTION ("--casemin", CLCASE_MIN, MND=.TRUE.)
CALL GETOPTION ("--casemax", CLCASE_MAX, MND=.TRUE.)

CALL CHECKOPTIONS ()

write(*,*) "nproma, blks = ", NPROMA, NGPBLKS

ILUN = 77

KLONTOT = 0
DO I = CLCASE_MIN, CLCASE_MAX
  write(FILENAME, '(A,I0.4,A,I0.4)' ) TRIM(CLCASE)//"."//"IN.",CLCASE_NUM, ".", I
  write(*,*) FILENAME


  OPEN (ILUN, FILE=FILENAME, FORM="UNFORMATTED")
  READ (ILUN) KLON
  READ (ILUN) KTDIAT
  READ (ILUN) KTDIAN
  READ (ILUN) KLEV
  CLOSE (ILUN)
  KLONTOT = KLONTOT + KLON

END DO

WRITE(*,*) "KLON total : ", KLONTOT

  I = 1
  write(FILENAME, '(A,I0.4,A,I0.4)' ) TRIM(CLCASE)//"."//"CONST.",CLCASE_NUM, ".", I
  write(*,*) FILENAME

  OPEN (ILUN, FILE=FILENAME, FORM="UNFORMATTED")

  ! OPEN (ILUN, FILE="../ACTKE.CONST.0001.0001", FORM="UNFORMATTED")
  CALL LOAD (ILUN, YDML_PHY_MF)
  CALL LOAD (ILUN, YDCST)
  CLOSE (ILUN)

IF (NPROMA == 0 .AND. NGPBLKS == 0) THEN
  NPROMA = KLONTOT
  NGPBLKS = 1
ELSE IF (NGPBLKS == 0) THEN
  NGPBLKS = 1+ (KLONTOT-1) / NPROMA
END IF
NGPTOT = NPROMA * NGPBLKS

WRITE(*,*) "NGPTOT, blocks, klon total ", NGPTOT, NGPBLKS, KLONTOT

! CALL exit(0)
CALL GETDATA(CLCASE, CLCASE_NUM, CLCASE_MIN, CLCASE_MAX, KLONTOT, KLEV, NPROMA, NGPBLKS, &
  PAPHI, PAPHIF, PAPRS, PAPRSF, PDELP, PR, PT, PU, PV, PQ, &
  PQICONV, PQLCONV, PLSCPE, PCD, PCH, PGZ0, PTS, & 
  PQS, PQICE, PQLI, PECT, PPRODTH, PNLAB, PNLABCVP, &
  PQICE_REF, PQLI_REF, PECT_REF, PPRODTH_REF, PNLAB_REF, PNLABCVP_REF, &
  PKTROV_REF,PKQROV_REF,PKQLROV_REF,PKUROV_REF,PXTROV_REF,&
  PXUROV_REF,PNBVNO_REF,PNEBS_REF,PQCS_REF,PNEBS0_REF,PQCS0_REF,&
  PCOEFN_REF,PECT1_REF,PFECT_REF,PFECTI_REF,PTPRDY_REF,PEDR_REF)

ALLOCATE (PKTROV(NPROMA,0:KLEV,NGPBLKS) )
ALLOCATE (PKQROV(NPROMA,0:KLEV,NGPBLKS))
ALLOCATE (PKQLROV(NPROMA,0:KLEV,NGPBLKS))
ALLOCATE (PKUROV(NPROMA,0:KLEV,NGPBLKS) )
ALLOCATE (PXTROV(NPROMA,0:KLEV,NGPBLKS) )
ALLOCATE (PXUROV(NPROMA,0:KLEV,NGPBLKS) )
ALLOCATE (PNBVNO(NPROMA,0:KLEV,NGPBLKS) )
ALLOCATE (PNEBS(NPROMA,KLEV,NGPBLKS) )
ALLOCATE (PQCS(NPROMA,KLEV,NGPBLKS) )
ALLOCATE (PNEBS0(NPROMA,KLEV,NGPBLKS) )
ALLOCATE (PQCS0(NPROMA,KLEV,NGPBLKS) )
ALLOCATE (PCOEFN(NPROMA,KLEV,NGPBLKS) )
ALLOCATE (PECT1(NPROMA,KLEV,NGPBLKS) )
ALLOCATE (PFECT(NPROMA,0:KLEV,NGPBLKS) )
ALLOCATE (PFECTI(NPROMA,0:KLEV,NGPBLKS) )
ALLOCATE (PTPRDY(NPROMA,KLEV,NGPBLKS) )
ALLOCATE (PEDR(NPROMA,KLEV,NGPBLKS) )

write(*,*) "call ACTKE   blocks : ", NGPBLKS

KIDIA = 1
KFDIA = NPROMA

DO IBL = 1, NGPBLKS
CALL ACTKE ( YDCST, YDLDDH,YDMDDH,YDML_PHY_MF,KIDIA, KFDIA, NPROMA, KTDIAT, KTDIAN, KLEV,&
            & PAPHI(:,:,IBL), PAPHIF(:,:,IBL), PAPRS(:,:,IBL), PAPRSF(:,:,IBL), PDELP(:,:,IBL), PR(:,:,IBL), PT(:,:,IBL),&
            & PU(:,:,IBL), PV(:,:,IBL), PQ(:,:,IBL), PQICONV(:,:,IBL), PQLCONV(:,:,IBL), PLSCPE(:,:,IBL), &
            & PCD(:,IBL), PCH(:,IBL), PGZ0(:,IBL), PTS(:,IBL), PQS(:,IBL), &
            & PQICE(:,:,IBL), PQLI(:,:,IBL), PECT(:,:,IBL), PPRODTH(:,:,IBL), PNLAB(:,:,IBL), PNLABCVP(:,:,IBL) ,&
            & PKTROV(:,:,IBL), PKQROV(:,:,IBL), PKQLROV(:,:,IBL), PKUROV(:,:,IBL), PXTROV(:,:,IBL), PXUROV(:,:,IBL), PNBVNO(:,:,IBL),&
            & PNEBS(:,:,IBL), PQCS(:,:,IBL), PNEBS0(:,:,IBL), PQCS0(:,:,IBL), PCOEFN(:,:,IBL) , &
            & PFECT(:,:,IBL) , PFECTI(:,:,IBL), PECT1(:,:,IBL) , PTPRDY(:,:,IBL), PEDR(:,:,IBL))
END DO

! PQICE_REF, PQLI_REF, PECT_REF, PPRODTH_REF, PNLAB_REF, PNLABCVP_REF, &
WRITE(*,*) "check diff on PQICE"
CALL COMPARE_VALUES(PQICE, PQICE_REF, NGPTOT * KLEV)
WRITE(*,*) "check diff on PQLI"
CALL COMPARE_VALUES(PQLI, PQLI_REF, NGPTOT * KLEV)
WRITE(*,*) "check diff on PECT"
CALL COMPARE_VALUES(PECT, PECT_REF, NGPTOT* KLEV)
WRITE(*,*) "check diff on PPRODTH"
CALL COMPARE_VALUES(PPRODTH, PPRODTH_REF, NGPTOT * (KLEV+1) )
WRITE(*,*) "check diff on PNLAB"
CALL COMPARE_VALUES(PNLAB, PNLAB_REF, NGPTOT * KLEV)
WRITE(*,*) "check diff on PNLABCVP"
CALL COMPARE_VALUES(PNLABCVP, PNLABCVP_REF, NGPTOT * KLEV)
WRITE(*,*) "check diff on PKTROV"
CALL COMPARE_VALUES(PKTROV, PKTROV_REF, NGPTOT * (KLEV+1))
WRITE(*,*) "check diff on PKQROV"
CALL COMPARE_VALUES(PKQROV, PKQROV_REF, NGPTOT * (KLEV+1))
WRITE(*,*) "check diff on PKQLROV"
CALL COMPARE_VALUES(PKQLROV, PKQLROV_REF, NGPTOT * (KLEV+1))
WRITE(*,*) "check diff on PKUROV"
CALL COMPARE_VALUES(PKUROV, PKUROV_REF, NGPTOT * (KLEV+1))
WRITE(*,*) "check diff on PXTROV"
CALL COMPARE_VALUES(PXTROV, PXTROV_REF, NGPTOT * (KLEV+1))
WRITE(*,*) "check diff on PXUROV"
CALL COMPARE_VALUES(PXUROV, PXUROV_REF, NGPTOT * (KLEV+1))
WRITE(*,*) "check diff on PNBVNO"
CALL COMPARE_VALUES(PNBVNO, PNBVNO_REF, NGPTOT * (KLEV+1))
WRITE(*,*) "check diff on PNEBS"
CALL COMPARE_VALUES(PNEBS, PNEBS_REF, NGPTOT * KLEV)
WRITE(*,*) "check diff on PQCS"
CALL COMPARE_VALUES(PQCS, PQCS_REF, NGPTOT * KLEV)
WRITE(*,*) "check diff on PNEBS0"
CALL COMPARE_VALUES(PNEBS0, PNEBS0_REF, NGPTOT * KLEV)
WRITE(*,*) "check diff on PQCS0"
CALL COMPARE_VALUES(PQCS0, PQCS0_REF, NGPTOT * KLEV)
WRITE(*,*) "check diff on PCOEFN"
CALL COMPARE_VALUES(PCOEFN, PCOEFN_REF, NGPTOT * KLEV)
WRITE(*,*) "check diff on PECT1"
CALL COMPARE_VALUES(PECT1, PECT1_REF, NGPTOT * KLEV)
WRITE(*,*) "check diff on PFECT"
CALL COMPARE_VALUES(PFECT, PFECT_REF, NGPTOT * (KLEV+1))
WRITE(*,*) "check diff on PFECTI"
CALL COMPARE_VALUES(PFECTI, PFECTI_REF, NGPTOT * (KLEV+1))
WRITE(*,*) "check diff on PTPRDY"
CALL COMPARE_VALUES(PTPRDY, PTPRDY_REF, NGPTOT * KLEV)
WRITE(*,*) "check diff on PEDR"
CALL COMPARE_VALUES(PEDR, PEDR_REF, NGPTOT * KLEV)

! END SUBROUTINE WRAP_ACTKE

END PROGRAM WRAP_ACTKE
